### ISSUE TITLE
Not working for Laravel 5

### ISSUE THREAD

**Issue by michellaurent** [bradcornford/Googlmapper#1]
It looks like the package doesn't work with Laravel 5.
I think that you have to update your service provider to be compliant with the last versions of Laravel.

```
 [BadMethodCallException]            
  Call to undefined method [package]
```

**Comment by bradcornford** [comment]
Hi there,

Yes your are correct, i had missed the updates i had done to the provider and the views in my initial version. These have now been added and work as expected.

**Comment by michellaurent** [comment]
Thanks. It works better now :)

Maybe you should use "googlmapper" as config filename instead of config to avoid conflict.

Also, the command line to publish config file is now ``php artisan vendor:publish``

You can also publish only the resources of the package giving the --provider flag
``php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"``

**Comment by bradcornford** [comment]
Okay, that should now be pushed to the develop branch, would you mind giving it a once over. I'm not as familiar with version 5, as I am with version 4!

**Comment by michellaurent** [comment]
I think it will work if you replace
```$this->publishes([$configPath => config_path('config.php')], 'googlmapper');```

with

```$this->publishes([$configPath => config_path('googlmapper.php')]);```

**Comment by bradcornford** [comment]
Okay, i've made that, and re-tagged the version. Thanks for your help!
