### ISSUE TITLE
Is there a way to disable Scroll Wheel ? 

### ISSUE THREAD

**Issue by zbora23** [bradcornford/Googlmapper#10]
Is there a way to disable scroll wheel? It is possible with standard JavaScript Maps API, however I am having trouble finding it here ?

Forgot to mention I am forced to edit your source but is it something you are looking to add in or is it already in somewhere ?

**Comment by bradcornford** [comment]
Yeah, this is possible, but you'd have to use something along the lines of 'map_0.disableScrollWheelZoom();'

**Comment by bradcornford** [comment]
Have you had any luck with this?
