### ISSUE TITLE
How do I add a custom map marker?

### ISSUE THREAD

**Issue by matbar20** [bradcornford/Googlmapper#101]
I've changed the markers.icon to my marker url of my custom marker image in the config.php file, but it doesn't display in rendered map. How do I go about adding custom javascript to the map?

**Comment by bradcornford** [comment]
Hi there,

You can add an icon to each marker as follows:

```php
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['icon' => 'URL']]);
```

You can add custom javascript as follows using an after load event:

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventBeforeLoad' => 'console.log("before load");']);
```

**Comment by leewillis77** [comment]
Hi Brad; 

I think there's actually a bug / regression here. Take the following code sample:

```php
Mapper::marker(
    $lat,
    $lng,
    [
        'icon'       => 'https://d2hlvggafz1wn0.cloudfront.net/2c100855-fc25-4e8e-8eb1-62c515c4cccf/photo-1-tiny.jpeg',
    ]
);
```

When run with v2.20.0 this produces a custom icon on the map as expected, with the JS output being:

```js
var markerPosition_5 = new google.maps.LatLng(54.920911222222, -2.9188648333333);
var marker_5 = new google.maps.Marker({
	position: markerPosition_5,
			title: "",
	animation:  '' ,
			icon: 'https://d2hlvggafz1wn0.cloudfront.net/2c100855-fc25-4e8e-8eb1-62c515c4cccf/photo-1-tiny.jpeg'
	});
```

However, when run with the latest release (or also with 2.21.0), the same code generate just a normal google maps flag on the map, not the custom icon, and the JS generated is missing the icon URL, e.g.

```js
var markerPosition_5 = new google.maps.LatLng(54.920911222222, -2.9188648333333);
var marker_5 = new google.maps.Marker({
	position: markerPosition_5,
			title: "",
	animation:  '' ,
			icon: ''
	});
```

So, it looks like this broke somewhere between 2.20 and 2.21. I suspect that the bug may be why the OP was having a problem getting custom icons to work - but let me know if you would prefer it as a separate bug report.

**Comment by bradcornford** [comment]
Hi there,

I'll take a look into this, i'm sure its something as simple as flipping the array_merge parameters, but ill check that something more drastic isn't happening.

**Comment by lfroidmo** [comment]
Hello,  

It seems like the regression is back in 2.23.0. I cannot set custom markers, just like described above. But it do works fine in 2.22.0. I saw that there was quite a few modifications to the Marker.php file. 

Thx

**Comment by leewillis77** [comment]
Marker icons seem to be working fine for me in 2.23.0..

**Comment by bradcornford** [comment]
@lfroidmo Can you provide me with you controller code for testing? As far as I am aware, markers are working correctly in version 2.23.0.

**Comment by lfroidmo** [comment]
I have the following code

**Comment by lfroidmo** [comment]
I have the following code 
`\Mapper::map(47.997290, 2.736291, ['marker' => false, 'zoom' => 6]);
foreach ($dealers as $dealer) {
            $content = view('dealers.informationWindow')->with('dealer', $dealer)->render();
            \Mapper::informationWindow($dealer->people->addresses[0]->lat, $dealer->people->addresses[0]->lng, $content, ['markers' => ['icon' => 'http://maps.google.com/mapfiles/ms/icons/'.$categoryColors[$dealer->category] .'-dot.png']]);
        }`

This work perfectly in 2.22.0, but the default marker is used in 2.23.0

**Comment by bradcornford** [comment]
Thanks for providing the above.

I think i've spotted the issue, it seems the markers options are being overwrote. I'm planning on refactoring this to remedy the issue.

**Comment by codec64** [comment]
Hi Brad, is there any update on this bug ? Thanks

**Comment by codec64** [comment]
If that can help, it's just a switch to do in Marker Model, to make it work :
```

  public function __construct(array $parameters = [])
    {
        $this->options = $parameters;
        if (isset($parameters['markers'])) {
            $this->options = array_replace_recursive(
                $this->options,
                $parameters['markers'],
                ($parameters['markers']['content'] !== '' ? ['content' => $parameters['markers']['content']] : [])
            );
        }
    }

```

**Comment by bradcornford** [comment]
Hi there,

I've started to refactor the markers / information windows into separate models. Which should hopefully reduce the impact on changes in the future. 

The only problem with the above is that configuration isn't inherited from parent items, for example if you set marker settings when creating a map, those get overwritten. Im not sure what the best way to allow both is at the moment.
