### ISSUE TITLE
problems to see map in blade laravel

### ISSUE THREAD

**Issue by xtsolucoes** [bradcornford/Googlmapper#103]
i have a problem trying to see the map in the view.blade.php i'm taking the information from the datebase i'm sending a printscreen

![screen shot 2017-01-11 at 17 18 42](https://cloud.githubusercontent.com/assets/11356150/21863483/ce03e4fa-d824-11e6-81d9-4fff821ed9dd.png)

and in streetview
![screen shot 2017-01-11 at 17 32 44](https://cloud.githubusercontent.com/assets/11356150/21863502/e1be1c7c-d824-11e6-9810-9833abc7d3d8.png)

thanks

**Comment by bradcornford** [comment]
Hi there,

Have you changed the Google API key? They one with the package tends to get blocked fairly quickly as people most people use it and it has a limit on map displays.

Can you check your browsers console too to see any errors?

**Comment by xtsolucoes** [comment]
Yes, i changed the key adn it's ok now but i can't to center the localization
![screen shot 2017-01-12 at 16 19 00](https://cloud.githubusercontent.com/assets/11356150/21902364/db67cba2-d8e2-11e6-82ad-856d5c85be2a.png)

**Comment by xtsolucoes** [comment]
look mais function

   public function maps(){
       $lat = \Request::get('lat');
       $long = \Request::get('long');
       Mapper::map($lat, $long);
       $div  = Mapper::render();
       print  $div;
   }

**Comment by bradcornford** [comment]
Hi there,

If you extend your mapping call as such, it should center the location with a marker.

```php
Mapper::map($lat, $long, ['center' => true, 'marker' => true]);

```

**Comment by xtsolucoes** [comment]
Sorry, but it did not work
![screen shot 2017-01-12 at 16 39 50](https://cloud.githubusercontent.com/assets/11356150/21903396/e61e7380-d8e6-11e6-8958-48df53f95bbd.png)
![screen shot 2017-01-12 at 16 48 35](https://cloud.githubusercontent.com/assets/11356150/21903420/fc74bdd8-d8e6-11e6-964b-c200e4f2c3c2.png)

**Comment by bradcornford** [comment]
Have you published the packages items?

**Comment by xtsolucoes** [comment]
yes, look
![screen shot 2017-01-17 at 12 19 41](https://cloud.githubusercontent.com/assets/11356150/22023963/8e26df24-dcaf-11e6-8230-cfd563b2a6ac.png)

**Comment by bradcornford** [comment]
Can you confirm in your controller you have: 

use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

**Comment by xtsolucoes** [comment]
What I'm checking is that using div works
sample 

<div style="width: 500px; height: 500px;">
    {!! Mapper::render() !!}
</div>


But I'm not using div and yes iframe

**Comment by bradcornford** [comment]
I've just tested this myself and it seems to be working as expected:

Routes:
```php
Route::get('/', function () {
    return view('index');
});

Route::get('/googlmapper', 'GooglmapperController@index');
```

Controller (GooglMapperController.php):
```php
<?php

    namespace App\Http\Controllers;

    use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

    class GooglmapperController extends Controller

    public function index()
    {
        Mapper::map(3.152109, 101.666041, ['center' => true, 'marker' => true]);

        print Mapper::render();
    }
```

View (index.blade.php):
```php
<iframe src="http://localhost/Laravel-5.3/public/googlmapper"></iframe>
```

**Comment by xtsolucoes** [comment]
Sorry, but it did not work, I do not understand what could be wrong.

in view
![screen shot 2017-01-17 at 17 52 32](https://cloud.githubusercontent.com/assets/11356150/22037304/cf52818c-dcdd-11e6-8766-8637d214af2e.png)

in controller
![screen shot 2017-01-17 at 17 53 46](https://cloud.githubusercontent.com/assets/11356150/22037346/ec6a2c7a-dcdd-11e6-92ef-8ccf6084565b.png)


code in view.blade.php
![screen shot 2017-01-17 at 17 54 55](https://cloud.githubusercontent.com/assets/11356150/22037384/14e5cf88-dcde-11e6-8d44-3c6bea5df1de.png)
