### ISSUE TITLE
Show information box when marker is clicked.

### ISSUE THREAD

**Issue by douglasspringer** [bradcornford/Googlmapper#104]
This is an issue that stems for a lack of knowledge on my part. I simply want to show the information window when a marker is clicked.

**Comment by bradcornford** [comment]
Hi there,

This can be achieved simply, try the below:

```php

Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 15, 'center' => false, 'marker' => false]);
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content');

```

**Comment by rickjm540** [comment]
Hmmm - this doesn't work - this code just shows a marker, but nothing happens when you click it

  Mapper::location(60640)->map(['zoom' => 15, 'center' => false, 'marker' => false]);
   Mapper::informationWindow(41.965379,-87.653939, 'Content');

**Comment by DeltaBiz** [comment]
Hi Brad.

I have been using this for a while now and around the same time as your last round of updates I started seeing the same issue. Info windows are not loading on click. Viewing src it doesn't appear they are being added at all.

Would you mind having a look?

Here is a brief example.

$center = Mapper::location("Richmond, BC");
 Mapper::map($center->getLatitude(), $center->getLongitude(), ['zoom' => 10, 'center' => false]);            

$location = {I get location here.}.

Mapper::informationWindow($location->latitude, $location->longitude, $annotation, ['markers' => ['animation' => 'DROP']]);


Marker's load, map loads. But no info window. And I have verified $annotation contains the correct string.

**Comment by bradcornford** [comment]
I'll investigate this further.

**Comment by bradcornford** [comment]
Looking into this further, it seems my fix to allow items to inherit parent options has caused this issue. I'll look at putting a fix together today. In the mean time, just pin your version to on version v2.20.0/v1.16.0.

**Comment by bradcornford** [comment]
I've now pushed a fix to current versions v2.20.1/v1.16.1. I will back patch previous versions soon.

**Comment by rickjm540** [comment]
Thanks much for looking into this Brad - this is an extremely helpful class!

**Comment by DeltaBiz** [comment]
Thanks Brad. Much appreciated.

**Comment by bradcornford** [comment]
No problem. All previous versions have now been back patched. Closing this issue now.
