### ISSUE TITLE
Artisan Command: "Nothing to publish for tag []"

### ISSUE THREAD

**Issue by CoryDean** [bradcornford/Googlmapper#105]
Composer.json
        "cornford/googlmapper": "2.*",

app.php
        'Cornford\Googlmapper\MapperServiceProvider',
        'Mapper'        => 'Cornford\Googlmapper\Facades\MapperFacade',

Laravel Framework version 5.3.29
Composer version 1.4-dev
PHP 7.0.13 (cli)

**Comment by CoryDean** [comment]
I've tried artisan config:clear and retried artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" with no avail.

**Comment by CoryDean** [comment]
Reran composer update command with a result of: "Nothing to install or update"
Reran `artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"` with no avail.

**Comment by CoryDean** [comment]
Tried:

`composer dump-autoload -o
php artisan vendor:publish --tag="googlmapper"`

via #45 with no avail.

Output from command:
Nothing to publish for tag ["googlmapper"].

**Comment by CoryDean** [comment]
Pasted the following into the console and executed and it seems to have worked:

`php artisan vendor:publish --tag=googlmapper`

Go the following idea from #8 

The difference in this command and previously tried command was the lack of quotes surrounding googlmapper.

Output from command:

Copied File [\vendor\cornford\googlmapper\src\config\config.php] To [\config\googlmapper.php]
Copied Directory [\vendor\cornford\googlmapper\src\views] To [\resources\views\cornford\googlmapper]
Publishing complete for tag [googlmapper]!

**Comment by bradcornford** [comment]
Glad you got it figured out. I may have to update the README to reflect your findings soon.

**Comment by bradcornford** [comment]
I have updated the README.md to reflect your findings.
