### ISSUE TITLE
Basic setup not working `htmlspecialchars() expects parameter 1 to be string, object given`

### ISSUE THREAD

**Issue by dbr0** [bradcornford/Googlmapper#106]
Hi, I'm having some really simple issue here (hopefully).

Adding `{{ Mapper::map(53.381128999999990000, -1.470085000000040000); }}` to my Blade template returns error:

`htmlspecialchars() expects parameter 1 to be string, object given`

And adding `{!! Mapper::map(53.381128999999990000, -1.470085000000040000) !!}` returns

`Object of class Cornford\Googlmapper\Mapper could not be converted to string`

Using 
 * Laravel  v5.3.29
 * Googlmapper v2.20.1

**Comment by bradcornford** [comment]
Hi there,

Move the map call to your controller, and then use the render method in your view.

**Comment by dbr0** [comment]
Oh, so in controller `Mapper::map(53.381128999999990000, -1.470085000000040000)` and then `{!! Mapper::render() !!}` in Blade?

**Comment by bradcornford** [comment]
Yeah thats the one. No nothing needs passing to the view.

**Comment by dbr0** [comment]
Got it, thanks for the fast response! 

A suggestion to update docs to something like this to make it more straightforward?

**Usage**

Initialize (not sure if this is the right word here) the map in your controller `MyController.php` as:

`public function renderMap()
{
    Mapper::map(53.381128999999990000, -1.470085000000040000);
    
    return view('my_view')
}`

Then in the view `my_view.blade.php` add:

` <div style="width:500px;height:500px;">{!! Mapper::render() !!}</div>`
