### ISSUE TITLE
Can see the div and js inside but map doesn't show up, height and width of parent div are set

### ISSUE THREAD

**Issue by dbr0** [bradcornford/Googlmapper#109]
Here is the generated html:

```
<div class="map" style="width: 400px;height: 400px; background: olivedrab;">
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&amp;region=HR&amp;language=en-gb&amp;key=here_goes_my_API_key&amp;signed_in=false&amp;libraries=places"></script>    
    <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script>
</div>
```

I have no idea what's wrong. I can see the green block but it's empty.

In console I get warning `Google Maps API warning: SignedInDeprecated` but that shouldn't be a problem.

**Comment by bradcornford** [comment]
Hi there,

Can you provide your controller, and the view please.

**Comment by dbr0** [comment]
I had the second return for the API and I've put the `Mapper::map(53.3811289,-1.47008);` behind the return for the web. I went to extract it to a separate controller/view and only then I noticed so thanks!
