### ISSUE TITLE
How do I create multiple map and render it at two places in view

### ISSUE THREAD

**Issue by alok108** [bradcornford/Googlmapper#11]
I need to display multiple maps in same page or atleast with a click of button change the markers. I am not able to figure out how can I send multiple map data from controller and render it in view.

Please guide. Also make you documentation more proper and give examples for all the available options as on searching I can find there had been one commit for multiple maps but there is nothing in documentation which can guide how to implement multiple maps.

**Comment by bradcornford** [comment]
Hi, multiple maps can be achieved like this:

'''php
Mapper::map(53.381128999999990000, -1.470085000000040000);
Mapper::map(53.381128999999990000, -1.470085000000040000);
Mapper::map(53.381128999999990000, -1.470085000000040000);
'''

Then the method render accepts an input parameter of a zero based key for each of the maps:

'''php
Mapper::render(0);
'''

**Comment by alok108** [comment]
Ok I can create multiple maps in one page but it doesnt work when I put them in tabs. I am using bootstrap tabs where different tab panel will have different map. But only first one renders and others just remain blank (gray background with google logo at bottom-left). 

My situation is like this I need to display upcoming event and past event and toggle between them. 
Is there any way I can just toggle the markers with a button click because I am using same map.
