### ISSUE TITLE
Declare markers globally

### ISSUE THREAD

**Issue by DeltaBiz** [bradcornford/Googlmapper#110]
I am wondering if you could declare the map markers globally. Currently there is no way to interact with the markers from your application. Only on initialization.

I have a requirement to click a Marker icon outside the map and trigger the click event on the marker within the map. It would also be a nice feature to be able to name the markers or provide an id for targeting.

Thanks for your work on this project.

**Comment by bradcornford** [comment]
Hi there,

They should be globally accessible via the maps global variable.

For example:

`maps[0].markers` will give you all markers for the first map.

`maps[0].markers[0]` will give you the first marker for the first map.
