### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by Facerafter** [bradcornford/Googlmapper#113]
I believe i've done everything right but the map is simply not showing.
When inspecting the source the div does seems to be empty..

MapController
```
use Cornford\Googlmapper\Mapper;

class MapController extends Controller
{
  public function index()
  {
    Mapper::map(53.381128999999990000, -1.470085000000040000);
    return view('eventmap')
  }
}
```

View
```
@extends('layouts.app')
@section('content')
  <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="embed-responsive embed-responsive-16by9">
              <div id="map_canvas" class="embed-responsive-item">
                  {!! Mapper::render() !!}
              </div>
          </div>
      </div>
  </div>
@endsection
```

**Comment by bradcornford** [comment]
Hi there,

Can you confirm if there are any console errors? I have tried the above and it works fine for me.

**Comment by Facerafter** [comment]
No errors.
http://37.97.248.157

**Comment by Facerafter** [comment]
Fixed something so the source now shows the script tag inside the div. But it still doesnt show a map.

**Comment by bradcornford** [comment]
What version of Laravel are you using? What version of this package?

**Comment by bradcornford** [comment]
Have you published the package items too?

**Comment by Facerafter** [comment]
Laravel 5.3.29
Googlmapper 2.21.0

The vendor:publish cmd? Yep.

**Comment by bradcornford** [comment]
This is what i've used to test, and it seems to work as expected. Have you also filled out your API key?

view.blade.php:
```php

        <div class="container">

            <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                    <div class="embed-responsive embed-responsive-16by9">

                        <div id="map_canvas" class="embed-responsive-item">

                            {!! Mapper::render () !!}

                        </div>

                    </div>

                </div>

            </div>

        </div>

```

Controller.php:
```php

    public function index()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);

        return view('view');
    }
```

**Comment by Facerafter** [comment]
Yep. Filled API key in /config/googlmapper.php

http://37.97.248.157/view
Still nothing..

**Comment by bradcornford** [comment]
Is there anything in your logs? storage/logs/laravel.log?

**Comment by Facerafter** [comment]
A whole bunch of stuff but nothing related to this.

Just making sure...
What Google APIs need to be enabled to get it to work?

**Comment by bradcornford** [comment]
I've just tried your API get and again its working in my example.

Here is the docs around API keys: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by Facerafter** [comment]
Well.. you can see in the links I send it doesnt work for me. 

I can see the my API key in the script tag src, but I meant which API do I have to enable? At the moment I have only enabled the Google Maps Javascript API

**Comment by bradcornford** [comment]
Yes, that is the correct API, only Google MapsJavascript API is required. Can you update the view with the updated above comment so i can see the result ^^^^^

**Comment by Facerafter** [comment]
Updated

**Comment by bradcornford** [comment]
Within `Cornford/Googlmapper/src/Cornford/Googlmapper/Mapper.php` can you add a line at the top of the `render` method of:

```php

dd($this->getItems());

```

**Comment by Facerafter** [comment]
Done

**Comment by bradcornford** [comment]
Okay, so there appears to be no items for the package to render.

Within `Cornford/Googlmapper/src/Cornford/Googlmapper/Mapper.php` can you add a line at the bottom of the `map` method of:

```php
dd($item);
```

**Comment by Facerafter** [comment]
Done.
Added it inbetween
''''
$this->addItem($item);

return $this;
""

**Comment by bradcornford** [comment]
So it looks like your not even calling the map method. Can you confirm that you are?

**Comment by Facerafter** [comment]
Im currently using the ViewController.php you posted here so. Or do you mean something else?

**Comment by bradcornford** [comment]
Can you add a `var_dump();` above each of the `dd()` calls with the method name please.

**Comment by Facerafter** [comment]
So a `var_dump($this);` ? Done

**Comment by bradcornford** [comment]
No, so in method render `var_dump('render');` and in method map `var_dump('map');`

**Comment by Facerafter** [comment]
Ah.. done

**Comment by bradcornford** [comment]
Okay, i've confirmed my assumption, the Mapper::map method is never actually being called. Can you provide me with your routes file? Also can you try adding the below to your view:

```php
<?php Mapper::map(53.381128999999990000, -1.470085000000040000); ?>
{!! Mapper::render () !!}
```

**Comment by bradcornford** [comment]
Now remove the `dd` and `var_dump` calls.

**Comment by Facerafter** [comment]
Oeps.  Your last comment made by realise my mistake. I was not using the ViewController... 

Apologies, im feeling incredibly stupid right now.

Thanks.

**Comment by bradcornford** [comment]
No problem, glad you found the issue!
