### ISSUE TITLE
How to send marker user profile.

### ISSUE THREAD

**Issue by GajdosGabriel** [bradcornford/Googlmapper#115]
I do not know how to send information about the user when the mouse is over. Something like 
\ Mapper :: marker ($ user-> lat, $ user-> LNG [ 'eventClick' => 'showProfile ($user->name)']);

not working.

Thx. Gabriel

**Comment by bradcornford** [comment]
Hi there,

Marker events are defined in the option parameters under a key of markers. See the following:

```php
 Mapper::map($user->lat, $user->lng, ['markers' => ['eventClick' => "showProfile('{$user->name}');"]]);
```

**Comment by GajdosGabriel** [comment]
Please. how can pass html element in title for tooltip. I have this code:
$options = ['marker' => true, 'title' => 'title for map', 'eventMouseOver' => 'showProfile( '. json_encode( $user ) .' )', 'eventMouseOut' => 'hideProfile()'];
                \Mapper::marker($user->lat, $user->lng, $options);

**Comment by bradcornford** [comment]
I don't think this is possible i'm afraid.
