### ISSUE TITLE
Laravel 5.4 Upgrade Error

### ISSUE THREAD

**Issue by jackkitley** [bradcornford/Googlmapper#116]
> php artisan optimize
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in /Applications/XAMPP/xamppfiles/htdocs/projects/ford_approved/vendor/cornford/googlmapper/src/Cornford/Googlmapper/MapperServiceProvider.php on line 43

                                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()  
   
                                                                    
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

See: https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736

**Comment by jackkitley** [comment]
Fix:MapperServiceProvider
	/**
	 * Register the service provider.
	 *
	 * @return void
	 */
	public function register()
	{
		$configPath = __DIR__ . '/../../config/config.php';
		$this->mergeConfigFrom($configPath, 'googlmapper');

		$this->app->singleton('mapper',function($app)
		{
			return new Mapper(
				$this->app->view,
				$app['config']->get('googlmapper')
			);
		});
	}

**Comment by bradcornford** [comment]
Hi there,

Thank you for this, i'll put a patch together for this.

**Comment by bradcornford** [comment]
I've pushed a fix for this onto current version 2.22.0.
