### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexeisein** [bradcornford/Googlmapper#118]
Where do I place this?: "Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper

**Comment by haubix** [comment]
In the console you enter the following command:
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper

**Comment by alexeisein** [comment]
Nothing to publish for tag [googlmappe].
I get this response when I tried it, but when I tried only "php artisan vendor:publish --provider", it was able to copy the files to view

**Comment by haubix** [comment]
> Nothing to publish for tag [googlmappe].
Maybe you are missing the "r" at the end? 
It's "--tag=googlmapper" not "--tag=googlmappe"

**Comment by alexeisein** [comment]
Oh, you are right. The "r" was missing.
Thanks

**Comment by bradcornford** [comment]
Has your issue been resolved?

**Comment by alexeisein** [comment]
yes. Thanks
