### ISSUE TITLE
Expired Key Error

### ISSUE THREAD

**Issue by freakken** [bradcornford/Googlmapper#119]
I tried this on a newly installed laravel 5.3 and followed the instructions, unfortunately console is giving me an ExpiredKeyMapError.

**Comment by bradcornford** [comment]
Hi there,

Have you updated the API key within the configuration file to use your own key? config/googlmapper.php?

**Comment by freakken** [comment]
Yes I have updated the API key on the config. while troubleshooting though, as I remove other attributes aside from the key and the init method on javascript blade src. the error has disappeared. Could it be I have misconfigured something on the config/googlmapper?

**Comment by bradcornford** [comment]
Perhaps the key needs to be activated agains the places and visualisation libraries. Out of interest what have you removed?

**Comment by freakken** [comment]
from:
//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&signed_in={!! $options['user'] ? 'true' : 'false' !!}&libraries=places&callback=initialize_method

to

//maps.googleapis.com/maps/api/js?key={!! $options['key'] !!}&callback=initialize_method

**Comment by bradcornford** [comment]
Try:

maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&callback=initialize_method

**Comment by freakken** [comment]
Error still persists.

**Comment by bradcornford** [comment]
Have you updated the region and language to the API keys region?

**Comment by bradcornford** [comment]
Available options exist within: src/Cornford/Googlmapper/MapperBase.php

**Comment by freakken** [comment]
Yup along with other options like async

**Comment by bradcornford** [comment]
According to Google's docs, 

"The API key included in the script element that loads the API has expired. You may need to generate a new API key in the Google API Console."

[See Obtaining an API key](https://developers.google.com/maps/documentation/javascript/get-api-key).

**Comment by freakken** [comment]
It now works, thanks for the help. The key was the issue.

**Comment by jumenta1960** [comment]
@freakken por favor me puede colaborar tengo problemas iguales y no he podido en siberian cms gustavobernal1954@yahoo.es

**Comment by bradcornford** [comment]
Hi, 

Sorry i don't speak Spanish. But you will need to follow the instructions at https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by jumenta1960** [comment]
Buenos dias
He recibido su mensaje por favor en que le puedo colaborar?
Cordial saludo
 GUSTAVO BERNAL ORTIZ
Contador Público 
Especializado en Derecho Tributario
https://www.appcolombia.net.co
Ayúdenos a Ayudarle
  
 

    El Viernes 31 de marzo de 2017 6:26, Bradley Cornford <notifications@github.com> escribió:
 

 Hi,Sorry i don't speak Spanish. But you will need to follow the instructions at https://developers.google.com/maps/documentation/javascript/get-api-key—

**Comment by freakken** [comment]
@jumenta1960 Hi, Sorry I also don't speak spanish but I fixed the problem by adding the key directly to the map.blade.php instead on the config as for some reason it does not read the code.
