### ISSUE TITLE
Create map based on Zip Code

### ISSUE THREAD

**Issue by isbkch** [bradcornford/Googlmapper#12]
Is there a way to center a map using an address or a zip code ?

**Comment by bradcornford** [comment]
No, not currently, without using another service, something like the below:

```php

$zipcode = 'ZIPCODE';
$json = file_get_contents("http://maps.googleapis.com/maps/api/geocode/json?address=$zipcode&sensor=false");
$object = json_decode($json);

$latitude = $object->results[0]->geometry->location->lat;
$longitude = $object->results[0]->geometry->location->lng;

Mapper::map($latitude, $longitude);

```

**Comment by bradcornford** [comment]
I will however look into adding something into Googlmapper to support this functionality.

**Comment by bradcornford** [comment]
I've had some time to look into implementing this feature and have created a branch based off develop called "feature-Create_map_based_on_location" which has the functionality you require.

It can be used as follows:

```php

$location = Mapper::location('ZIPCODE');
$location->map(['markers' => ['title' => 'Marker Title']]);

Mapper::location('ZIPCODE')->map(['markers' => ['title' => 'Marker Title']]);

```

or

```php

$location = Mapper::location('ZIPCODE');
$location->streetview(5, 10);

Mapper::location('ZIPCODE')->streetview(5, 10);

```

The method location, will either return a Location object, or throw a relevant exception:

MapperArgumentException - if a blank / null search is performed
MapperSearchException - if a search request against Google Maps Api fails
MapperSearchResultException - if a search request against Google Maps Api returns no results
MapperException - if the search request against Google Maps Api returns malformed data

The Location object has the following methods:

getSearch
getAddress
getType
getLatitude
getLongitude
getPlaceId
map
streetview

**Comment by bradcornford** [comment]
Did you have any luck with this?

**Comment by isbkch** [comment]
Oh I missed that. I will be playing with it this weekend.
Thx man

**Comment by bradcornford** [comment]
I've now added this to current version v2.5.0.
