### ISSUE TITLE
Map is not updated with new location when using geocomplete

### ISSUE THREAD

**Issue by lckamal** [bradcornford/Googlmapper#120]
I am using [geocomplete](https://github.com/ubilabs/geocomplete) to autocomplete places.
I have rendered map with googlmapper but when location is searched and selected with geocomplete map doesn't get updated.

Here is code I used: https://monosnap.com/file/W9lm13Xsi7fD70qeRt3Oi9JUieSuw6

Any Idea how to link googlmapper and geocomplete?

**Comment by bradcornford** [comment]
Hi there,

Take a look at this: https://github.com/bradcornford/Googlmapper/issues/114#issuecomment-274348919
