### ISSUE TITLE
informationWindow content not preserving white space

### ISSUE THREAD

**Issue by rickjm540** [bradcornford/Googlmapper#122]
Hi!

The content field for putting information on the marker isn't preserving white space - it's getting stripped somewhere when being rendered. Where would I look  for that?

ie: Mapper::informationWindow($row->lat, $row->lng, $content, ['markers' => ['icon' => '/images/markers/ion_mapMarkers_' . $cnt . '.png']] );

The $content parameter has some whitespace, but when rendered, everything after the whitespace is ignored..

Thanks!

**Comment by bradcornford** [comment]
Hi there,

This is something a browser does by default, this can be overwritten using CSS, see below:

```html

.gm-style-iw div div {
    white-space: pre;
}

```

**Comment by rickjm540** [comment]
Thanks for the reply, Brad!
I'll give that a try - What I'm seeing is, when $content contains a string like "Chicago IL 60640" it just displays "Chicago" on the marker.

**Comment by bradcornford** [comment]
How strange, i've just given your content string a go and it seems to work. Make sure your up to date with the latest version too.

<img width="318" alt="screen shot 2017-03-09 at 10 59 27" src="https://cloud.githubusercontent.com/assets/2913887/23747447/8ea486e2-04b7-11e7-9926-7d4facb86ca6.png">

**Comment by rickjm540** [comment]
I'll check - it's highly possible I'm losing it in translation somewhere :)
Thanks again for your quick replies!

**Comment by bradcornford** [comment]
No worries. Hope you work it out!
