### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by hughescp** [bradcornford/Googlmapper#123]
Hi, I've tried following along the steps to install GooglMapper, however when I run the command:
`php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper`

It returns:
`Nothing to publish for tag [googlmapper].`

I've looked at other posts and tried the suggestions however nothing has worked for me

**Comment by bradcornford** [comment]
Hi there,

Have you added the service provider and facade to you `config/app.php`?

You could try running:

```
composer dump-autoload -o
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper
php artisan vendor:publish --tag=googlmapper
```

Can you check that the following directory exists: `resources/views/cornford/googlmapper`?
 If it does then everything has been published.

**Comment by hughescp** [comment]
Hi Brad,

Yes I have added it in to those two places like below in config/app.php
```
'providers' => [
...
        Cornford\Googlmapper\MapperServiceProvider::class,
],

'aliases' => [
...
        'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class
]


I have run the commands you suggested but got the same message of `Nothing to publish for tag [googlmapper].`

And the directory `resources/views/cornford/googlmapper` doesn't exist :(

**Comment by bradcornford** [comment]
Okay, can you try:

```
php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper
```

**Comment by sm4rtm3n** [comment]
try `php artisan config:cache` first
