### ISSUE TITLE
not showing map

### ISSUE THREAD

**Issue by Galez** [bradcornford/Googlmapper#125]
my controller
![screenshot 43](https://cloud.githubusercontent.com/assets/9381648/23717808/e9210fd6-03fa-11e7-99e1-a6d1adba2d42.png)

my view
![screenshot 42](https://cloud.githubusercontent.com/assets/9381648/23717723/9d2998e6-03fa-11e7-9120-3a49368a88a5.png)

my css
![screenshot 44](https://cloud.githubusercontent.com/assets/9381648/23717854/11b4b02e-03fb-11e7-9b3c-b6151bd8f312.png)

doesn't show a thing
![screenshot 41](https://cloud.githubusercontent.com/assets/9381648/23717577/fb0aa046-03f9-11e7-9828-448e8e7f9937.png)

I'm using laravel 5.3

**Comment by berkapavel** [comment]
try to look here - https://github.com/bradcornford/Googlmapper/issues/113

**Comment by bradcornford** [comment]
Hi there, 

This looks to be an issue with GoogleMaps itself, as the height is dynamically calculated via CSS. I would suggest adding like the following:

```html
<style type="text/css">

.map-container {
                display: block;
                position: relative;
                width: 100%;
                height: 100%;
                padding-bottom: calc(50% - 60px);
            }

            .map {
                position: absolute;
                width: 100%;
                height: 100%;
            }
</style>

<div class="map-container">
    <div class="map">{!! Mapper::render () !!}</div>
</div>
```

**Comment by Galez** [comment]
console show me this error, I have print the mapper items and is not using my API key
![screenshot 49](https://cloud.githubusercontent.com/assets/9381648/23757437/799406fc-04ac-11e7-885e-88ce27eaeb82.png)

**Comment by bradcornford** [comment]
Hi there, 

Did you get to the bottom of this? I assume it was something to do with you Vue configuration?

**Comment by Galez** [comment]
I actually did solve it, wasn't aware that maps doesn't show if in the height you use % it wasn't never a Vue configuration problem, although it did give me some problems, it was all about the CSS

**Comment by bradcornford** [comment]
Ah great, yeah that is a strange requirement that Google set for there maps.
