### ISSUE TITLE
pin marker colours

### ISSUE THREAD

**Issue by bikedel** [bradcornford/Googlmapper#126]
Hello
How do I change the colour of the pin marker.

**Comment by bikedel** [comment]
ok I figured it out - thanks

**Comment by bradcornford** [comment]
Glad you figured it out.

**Comment by bikedel** [comment]
:) thanks for the reply and the good work.
 

Sent: Thursday, March 09, 2017 at 12:56 PM

**Comment by danilosantosdev** [comment]
Would be nice if you put the solution here.

**Comment by bikedel** [comment]
Hello Nice

Reference the colour you want in the icon field.

Hope you can get an idea from the code below.

I check for certain variables and accordingly set the icon field to reference the correct colour icon.

You can of course use your own icons.

Hope this helps.



            if ($property->long && $property->lat) {

                if ($property->sale_type_id == 2) {
                    Mapper::marker($property->long, $property->lat, ['draggable' => 'true', 'title' => 'Type: ' . $types[$property->type] . ' Erf: ' . $property->erf, 'eventRightClick' => 'window.prompt("Copy and save co-ordinates.","lat: "+event.latLng.lat() + "  lng: "+event.latLng.lng() );', 'content' => $content . '<br> <img src=' . $image . '  style="width:120px;" />', 'scale' => 13, 'animation' => 'DROP', 'icon' => "http://maps.google.com/mapfiles/ms/icons/green-dot.png"]);
                } elseif ($property->sale_type_id == 1) {
                    Mapper::marker($property->long, $property->lat, ['draggable' => 'true', 'title' => 'Type: ' . $types[$property->type] . ' Erf: ' . $property->erf, 'eventRightClick' => 'window.prompt("Copy and save co-ordinates.","lat"+event.latLng.lat() + "  lng: "+event.latLng.lng() );', 'content' => $content . '<br> <img src=' . $image . '  style="width:120px;" />', 'scale' => 13, 'animation' => 'DROP', 'icon' => "http://maps.google.com/mapfiles/ms/icons/yellow-dot.png"]);
                } else {
                    Mapper::marker($property->long, $property->lat, ['draggable' => 'true', 'title' => 'Type: ' . $types[$property->type] . ' Erf: ' . $property->erf, 'eventRightClick' => 'window.prompt("Copy and save co-ordinates.","lat"+event.latLng.lat()  + " lng: "+event.latLng.lng() );', 'content' => $content . '<br> <img src=' . $image . '  style="width:120px;" />', 'scale' => 13, 'animation' => 'DROP', 'icon' => "http://maps.google.com/mapfiles/ms/icons/red-dot.png"]);
                }
            }

**Comment by danilosantosdev** [comment]
Thanks for reply, help a lot.
