### ISSUE TITLE
Multi marker on single map render

### ISSUE THREAD

**Issue by vanndy** [bradcornford/Googlmapper#128]
Hi,

I want to know how to display multi marker point on single map when render map in the blade template. Could you guide me?

Thanks,
Vanndy

**Comment by sergiuwd** [comment]
Use the `Mapper::map()` function to initialize the map (maybe you will want to use the `'marker' => false` attribute, them use `Mapper::marker()` function to add markers. On the view, use `Mapper::render()` and it should work.

**Comment by bradcornford** [comment]
Hi there,

You should be able to do the following, within your controller:

```php
Mapper::map(3.152109, 101.666041, ['center' => true, 'marker' => true]);
Mapper::marker(3.252109, 101.766041);
Mapper::marker(3.352109, 101.866041);
```

and within your view:

```html
{!! Mapper::render () !!}
```
