### ISSUE TITLE
Information Window not styling the marker

### ISSUE THREAD

**Issue by sergiuwd** [bradcornford/Googlmapper#129]
Hello!
I am trying to add a marker and style it like this:
`        Mapper::map($loc->getLatitude(), $loc->getLongitude(), ['zoom' => 10, 'fullscreenControl' => false, 'center' => true, 'marker' => false, 'cluster' => false, 'language' => 'en']);
Mapper::informationWindow($clinic->profile->lat, $clinic->profile->lng, (string)view('internalapi.maps.info', compact(['clinic'])), ['maxWidth'=> 300, 'markers' => ['title' => 'Title']]);
`
It is adding the information window, but not styling the marker. Why?

**Comment by bradcornford** [comment]
Hi there,

You should be able to achieve the above with the following:

```php

Mapper::map(54.9, -2.9, ['zoom' => 10, 'fullscreenControl' => false, 'center' => true, 'marker' => false, 'cluster' => false, 'language' => 'en']);
        Mapper::informationWindow(54.9, -2.9, 'test', ['maxWidth'=> 300, 'title' => 'Title', 'icon' => 'http://cdn.images.express.co.uk/img/static/comments/newshare/g-plus.png']);

```

**Comment by sergiuwd** [comment]
Yep, that worked! Thank you very much! Also, I need the documentation should be changed, because it sais that the marker styling should be put inside the `markers` attribute.

**Comment by bradcornford** [comment]
Yeah, I am looking into this at the moment. I believe it is a bug, and it was introduced as a side effect of another change.
