### ISSUE TITLE
prob with publish config files

### ISSUE THREAD

**Issue by atefBB** [bradcornford/Googlmapper#130]
Hi, I'm using laravel 5.4.15 and and this command : `php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper` seem to publish nothing ! 
any ideas?

**Comment by atefBB** [comment]
solved ! I replace `php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper` with `php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper` and it's work !

**Comment by bradcornford** [comment]
Hi there,

Thanks for this. I'll get that updated on the README.md, and push it to master ASAP.

**Comment by atefBB** [comment]
Thanks !

**Comment by bradcornford** [comment]
Updated README.md in master now.

**Comment by atefBB** [comment]
so thank you !

**Comment by atefBB** [comment]
I'm using laravel 5.4, so I put `Cornford\Googlmapper\Facades\MapperFacade::class` instead of `Cornford\Googlmapper\Facades\MapperFacade` !
need update README.md?

**Comment by atefBB** [comment]
see https://github.com/bradcornford/Googlmapper/pull/131

**Comment by bradcornford** [comment]
Yeah, either way actually works, the ::class notation refers back to a string for class name and namespace. I've now merged that PR.

**Comment by atefBB** [comment]
Thanks ! very nice !

**Comment by sugengsuprayogi** [comment]
Hi, I'm using laravel 5.2 and and this command : php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper seem to publish nothing !
any ideas?

**Comment by atefBB** [comment]
I want to help but can't figure it out, sorry !
@bradcornford HELP needed here ! ^__^

**Comment by bradcornford** [comment]
Hi there,

Can you try the following:

`php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper`

**Comment by StevenWilliams** [comment]
it's not publishing anything for me in laravel 5.4.

**Comment by bradcornford** [comment]
Can you try this @StevenWilliams 

```
php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper
```
