### ISSUE TITLE
Clusters' size and zoom have no effect

### ISSUE THREAD

**Issue by ttasovac** [bradcornford/Googlmapper#133]
Hi. I have a map which uses clusters and sets them up like this:

`'clusters' => ['center' => false, 'zoom' => 9, 'size'=> 4]`

The clusters are created, but these settings seem to have no effect. Clusters appear well beyond zoom 9 and also contain as few as 2 markers, even though the size parameter is set to 4. 

I wonder if this is a known issue. 

All best,
Toma

**Comment by bradcornford** [comment]
Hi there,

The above you provided should work as expected. You could try setting these within `config/googlmapper.php` configuration file.

I'll test the above also works as expected too.

**Comment by bradcornford** [comment]
I've done some testing, and it appears that it doesn't function as expected. It also seems to be noted  in a number of issues, this being one https://github.com/googlemaps/v3-utility-library/issues/277.

**Comment by expdev** [comment]
Hello! This problem not only for clusters. 
It doesn't work either if define 'center' to false:
Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 15, 'center' => false, 'marker' => false, 'type' => 'HYBRID', 'overlay' => 'TRAFFIC']);

**Comment by dambridge** [comment]
Same issue here.

**Comment by bradcornford** [comment]
@expdev Are you still seeing the issue?

@dambridge Did you find a solution?

**Comment by dambridge** [comment]
@bradcornford In my case it was a simple js conflict, my own fault. Fixed it and everything works.
