### ISSUE TITLE
How do I change the icon according to a condition?

### ISSUE THREAD

**Issue by edilsonsilvapro** [bradcornford/Googlmapper#134]
How do I change the icon according to a condition?

I tried that way, but it did not work

Mapper::informationWindow($address->latitude, $address->longitude, $content, ['markers' => ['icon' => 'http://www.endlessicons.com/wp-content/uploads/2012/12/pin-map-icon-614x460.png', 'animation' => 'DROP']]);

**Comment by bradcornford** [comment]
Hi there,

Because an information is basically a marker with an event listener, you don't have to utilise the markers array to define its properties. For example:

```php
Mapper::informationWindow($address->latitude, $address->longitude, $content, ['icon' => 'http://www.endlessicons.com/wp-content/uploads/2012/12/pin-map-icon-614x460.png', 'animation' => 'DROP']);
```

**Comment by edilsonsilvapro** [comment]
What I want is that different markers appear on the same map according to a condition. how to do this? I only found in the configuration how to change the default icon, but I would like different markers on the same map. Could you show me an example?

**Comment by zubinkadva** [comment]
You need to somehow get the index of your marker. For example
````
foreach ($locations as $index => $location) {
    Mapper::marker(lat, lng, ['center' => true, 'eventClick' => 'show("' . $index . '")']);
}

function show (index) {
    maps[0].markers[index].setIcon('<your icon path here>');
}
````

**Comment by bradcornford** [comment]
Hi there,

You could group your makers by location in your database, then loop though each group itself adding a different icon, for example:

```
foreach ($groups as $group) {
    foreach ($addresses as $address) {
        Mapper::informationWindow($address->latitude, $address->longitude, $content, ['icon' => $icon, 'animation' => 'DROP']);
    }
}
```
