### ISSUE TITLE
Unable to perform location search

### ISSUE THREAD

**Issue by jsjtzyy** [bradcornford/Googlmapper#136]
Hi, I am trying to use Mapper::location and encounter an error as follows.

Unable to perform location search, the error was: "file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0".

I have set allow_url_fopen = On in php.ini but the error still exist. Any suggestions? Thanks in advance.

**Comment by jsjtzyy** [comment]
I fixed problem. Thanks anyway.

**Comment by bradcornford** [comment]
Hi there,

Glad you came to a solution. Any chance you can post your findings here please.
