### ISSUE TITLE
Unable to set values for multiple markers

### ISSUE THREAD

**Issue by tedmasterweb** [bradcornford/Googlmapper#137]
*Summary*

Given a map with multiple markers, I am unable to set individual values for the title, content, icon, etc. for each marker. Rather, markers are using blank or default values.

*Preconditions*
* A map has been initialized via Mapper::map($long, $lat, [options]);

*Steps to Reproduce*

1. Set one or more markers using the following code:

```
Mapper::marker($long, $lat, [
    'title' => 'First marker',
    'symbol' => 'circle',
    'scale' => 1000
]);
Mapper::marker($long2, $lat2, [
    'title' => 'Second marker',
    'symbol' => 'circle',
    'scale' => 1000
]);
```

*Expected Result*
* The map has two markers, one with a title attribute of 'First marker' and the second with a title attribute of 'Second marker'

*Actual Result*
* The title attribute of both markers is blank

*Workaround*
* None that I know of

*Notes*
The documentation hints that I am doing this correctly but values seem be getting overwritten [about here](https://github.com/bradcornford/Googlmapper/blob/master/src/Cornford/Googlmapper/Mapper.php#L262).

Am I doing it wrong or is this a known problem?

Kind regards,

Ted Stresen-Reuter

**Comment by bradcornford** [comment]
Hi there,

What version are you currently using? I've given this a whirl on v2.23.0/v1.18.0, and it seems to be working as expected.

You are doing this correctly, i've used the below as a test:

```php
        Mapper::map(54.9, -2.9, ['zoom' => 10, 'fullscreenControl' => false, 'center' => true, 'marker' => false, 'cluster' => true, 'clusters' => ['center' => false, 'zoom' => 15, 'size'=> 4], 'language' => 'en']);

        $lat = 54.8;
        $lng = -2.8;

        $icons = [
            'https://support.xbox.com/Content/Images/live_status_active_icon.png',
            'http://www.cityofukiah.com/NewWeb/wp-content/themes/deepblue/images/icon-dollar-small.png',
            'http://h30434.www3.hp.com/html/assets/comm_alert_icon.png',
            'https://i.stack.imgur.com/1luXA.png',
            'https://d30fqisedfc4ds.cloudfront.net/rensupv1/images/rss-icon.png',
        ];

        for ($i = 1; $i <= 5; $i ++) {
            Mapper::marker(($lat - ($i * 0.1)), $lng - ($i * 0.1), ['title' => $i . ' test', 'animation' => 'DROP', 'icon' => $icons[$i - 1]]);
        }

```

With the following result:

<img width="1042" alt="screen shot 2017-04-10 at 09 59 04" src="https://cloud.githubusercontent.com/assets/2913887/24853926/83a50e0c-1dd4-11e7-8649-7526b87813cc.png">

**Comment by tedmasterweb** [comment]
Thanks for the quick reply. 

Not sure how to know which version, but I have the following line in composer.json and everything is updated:

`"cornford/googlmapper": "2.*"`

How can I tell what version I'm using (or updated to a more recent version, like 2.23?). Also, using this from inside Laravel (not that that matters much).

**Comment by tedmasterweb** [comment]
Seconds after writing the above, I found the problem. I'm following the marker generation loop with this:

`Mapper::informationWindow($item->getLatitude(), $item->getLongitude(), $item->mapInfoWindow());`

and it seems to be overwriting the markers. If I reverse the order, then the information windows are empty. Any idea how I should be doing this?

marker() first
![image](https://cloud.githubusercontent.com/assets/99979/24858170/0e7f92d2-1de3-11e7-8366-ac90c9e24463.png)

informationWindow() first
![image](https://cloud.githubusercontent.com/assets/99979/24858099/ad28cb2a-1de2-11e7-8274-8095c7f6e5ce.png)

**Comment by bradcornford** [comment]
Are you adding both a marker and an information window? An information window is just a marker itself, with a bound event.

**Comment by bradcornford** [comment]
Could you possibly give me some sample code to test my end please?

**Comment by tedmasterweb** [comment]
> An information window is just a marker itself, with a bound event.

That makes sense and was a key piece of info in helping me understand what was missing… And I think I spotted a typo in the documentation (which lead to much of this confusion).

In the docs you have:

`Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content', ['open' => true, 'maxWidth'=> 300, markers' => ['title' => 'Title']]);`

There are a couple of issues:

1. You seem to be missing a single quote before **markers** (but this wasn't my problem)
2. The 'markers' array was not being recognized. If I just listed the individual marker elements ('title', 'animation', 'icon', etc.) as the members of the array (without 'markers'), it worked fine. E.g. this works:

```
Mapper::informationWindow(
    $lat, 
    $long, 
    '<div class="infowin"><h1>window title</h1><p>content</p></div>',
    [
        'title' => $mytitle,
        'animation' => 'NONE',
        'icon' => 'http://cutekittens/calico.jpg'
    ]
);
```

Thank you so much for taking the time to help me track this down. I really appreciate it.

Kind regards,

Ted Stresen-Reuter

**Comment by danilosantosdev** [comment]
In this context, can i put new values in the marker? For example:

```
Mapper::informationWindow(
                $escola->info->lat,
                $escola->info->long,
                $escola->info->nome,
                [
                    'title' => $escola->info->nome,
                    'id' => $escola->info->id,
                    'open' => true,
                    'maxWidth'=> 300,
                    'icon' => url(asset('imagens/unidadeensino-black.png'))   
                ]
            );
```

**Comment by bradcornford** [comment]
@danilosantosdev Yes, that is correct.

**Comment by danilosantosdev** [comment]
@bradcornford Ok, but when i inspect the element in the console, this "id" attribute doesn't appear.

**Comment by bradcornford** [comment]
Yes, the ID isn't actually set on the element. I'm assuming this is something that Google have put in place as i cant seem to find any documentation on achieving this.
