### ISSUE TITLE
How do I use different keys?

### ISSUE THREAD

**Issue by tedmasterweb** [bradcornford/Googlmapper#138]
Google Maps provides a few methods for verifying access to the API.

For our web app we use "HTTP Referrers". For seeding the database, though, where no referrer is sent, we need to use "IP addresses (web servers, cron jobs, etc.)"

We set the API key in config. We're wondering if there is a way to use a different API key for seeding the database. Any ideas?

**Comment by bradcornford** [comment]
Hi there,

This would be possible with something like the following:

```php
Mapper::setKey('abc');
Mapper::map(53.381128999999990000, -1.470085000000040000);
```

**Comment by tedmasterweb** [comment]
That is fantastic. Thanks!
