### ISSUE TITLE
Maps not loading

### ISSUE THREAD

**Issue by theSpondge** [bradcornford/Googlmapper#139]
I have set this up correclty, as when i open the "Inspect Element" i am using chrome the map loads.....

![screen shot 2017-04-12 at 12 46 41](https://cloud.githubusercontent.com/assets/2730493/24956126/1b19b788-1f7e-11e7-8d47-eef60df0e401.png)

Any ideas???

**Comment by bradcornford** [comment]
Hi there,

Is there anything in your console? Any errors?

**Comment by theSpondge** [comment]
I just get this:
![screen shot 2017-04-12 at 14 03 49](https://cloud.githubusercontent.com/assets/2730493/24958916/eacd5af2-1f88-11e7-9267-eab7e5138a2f.png)

**Comment by bradcornford** [comment]
Can you show me the controller code your using, and your view?

**Comment by theSpondge** [comment]
I have fixed the issue, i was using jQuery hide on the element. removed it and all works

Can be closed now.

**Comment by bradcornford** [comment]
Excellent, glad you found the issue.
