### ISSUE TITLE
Custom marker icons suddenly not showing up

### ISSUE THREAD

**Issue by rickjm540** [bradcornford/Googlmapper#140]
Suddenly my custom markers are not showing up - just the default ones - did something change?

My code = 
 Mapper::informationWindow($row->lat, $row->lng, $content, ['markers' => ['icon' => '/images/markers/ion_mapMarkers_' . $cnt . '.png']] );

I can see the custom marker if I link directly to it in a browser window, and they used to show fine.

**Comment by rickjm540** [comment]
Oh wait - It works with 
Mapper::informationWindow($row->lat, $row->lng, $content, ['icon' => '/images/markers/ion_mapMarkers_' . $cnt . '.png'] );

Did that change?

**Comment by bradcornford** [comment]
Hi there,

Yes this did change recently however both methods should work. I am looking into this at the moment as I see it as a bug. I the second method seems more natural as the information window is a marker in itself. However the markers options should also be compatible both ways.
