### ISSUE TITLE
Gray boxes surrounding everything

### ISSUE THREAD

**Issue by MaximeDawn** [bradcornford/Googlmapper#141]
Hi, 

I have a strange issue, everytime i add something to the map (Marker, InfoWindow, Rectangle...) it is surrounded by a gray box (see images below). Any suggestions ?

![image](https://cloud.githubusercontent.com/assets/20993007/25040170/0c3dcfac-2108-11e7-97dc-a87ee0f78973.png)
![image](https://cloud.githubusercontent.com/assets/20993007/25040186/213d2ce0-2108-11e7-8738-a97dd783ae46.png)

**Comment by MaximeDawn** [comment]
Interessant thing is, when I set the marker animation to 'BOUNCE' i don't have those gray boxes 😄

**Comment by bradcornford** [comment]
Hi there,

I am almost certain that this is some of your css affecting the map in some way. It looks like you have a rule that adds a border radius and grey border. Can you track this down?

**Comment by MaximeDawn** [comment]
Ok thank you that was the problem. A border on the "canvas" class in my custom CSS 😄

**Comment by bradcornford** [comment]
Ah that explains it. Glad you found the cause.
