### ISSUE TITLE
Add an event listener to infowindow or marker?

### ISSUE THREAD

**Issue by gflauder** [bradcornford/Googlmapper#143]
Is it possible to to have an event listener on a marker or infobox like this? I see you have some events as options  built into the Blade view, but I'm a little lost how I could add a 'domready' event fire and style each infowindow

`google.maps.event.addListener(infowindow, 'domready', function() { //some styling calls here}`

    `@foreach (['eventClick', 'eventRightClick', 'eventMouseOver', 'eventMouseDown', 'eventMouseUp', 'eventMouseOut', 'eventDrag', 'eventDragStart', 'eventDragEnd'] as $event)

Already in Blade :

	@if (isset($options[$event]))

		google.maps.event.addListener(marker_{!! $id !!}, '{!! str_replace('event', '', strtolower($event)) !!}', function (event) {
			{!! $options[$event] !!}
		});

	@endif

@endforeach`

Is it a simple as adding the event as an option? 

Many thanks in advance for any suggestions!

**Comment by bradcornford** [comment]
Hi there,

At the moment the package doesn't support the 'domready' event. However, ill add this to my list of feature as i don't think this will take too much time to implement.

You do have another option, It's a simple as adding an event parameter to the map, this will fire when the map as loaded using the event 'tilesloaded', for example:

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'console.log("after load");']);
```

Or if you want to fire an event before the map as loaded, for example:

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventBeforeLoad' => 'console.log("before load");']);
```

If the above don't suffice, you can amend the file `resources/views/cornford/googlmapper/maker.blade` line 100 to:

```
@foreach (['eventClick', 'eventRightClick', 'eventMouseOver', 'eventMouseDown', 'eventMouseUp', 'eventMouseOut', 'eventDrag', 'eventDragStart', 'eventDragEnd', 'eventDomReady'] as $event)
```

**Comment by gflauder** [comment]
Going to give this a try! 
Again, thank you for the quick reply and such a great add on. Really appreciate your effort and help!

**Comment by bradcornford** [comment]
I've now pushed the above functionality into current version 2.25.0/1.20.0. 

You can now achieve the above as follows:

```php
Mapper::marker(
    0,
    0,
    [
        'title' => 'SVG Marker',
        'eventDomReady' => 'console.log(1);'
    ]
);
```

**Comment by xandedj** [comment]
Good afternoon.

How can I style the label label, I need it to stay up instead of in the middle of the marker, need to put a backgorund of the label how can I do and add padding ?.

Thank you very much in advance.

  Mapper::map(-22.886449, -43.118474,
              [   'marker'=>false,
                  'zoom' => 10,
                  'draggable' => true,
                  'center' => true,
                  'cluster' => false,
                  'markers' => [
                  'icon' =>'img/ida_22.png',
                  'title' => '166001',
                  'animation' => 'DROP'],

              ]);

              $markers = array(['lat' => -22.886449,'lng' => -43.118474,'label'=> 'Veículo 01'],
                                ['lat' => -22.885632,'lng' => -43.118143,'label'=> 'Veículo 02'],
                                ['lat' => -22.883990,'lng' => -43.119513,'label'=> 'Veículo 03'],
                                ['lat' => -22.885734,'lng' => -43.124988,'label'=> 'Veículo 04']);

              foreach ($markers as $marker) {
        
                   Mapper::marker($marker['lat'], $marker['lng'],['label'=> $marker['label']]);

                   Mapper::informationWindow($marker['lat'], $marker['lng'], $marker['label']);
              }

**Comment by bradcornford** [comment]
Hi there,

You can add a custom label using the following:

```

        Mapper::marker(51.3359154, 3.3129791, [
            'label' => [
                'text' => '$300k',
                'color' => '#4682B4',
                'fontSize' => '30px',
                'fontWeight' => 'bold'
            ],
            'labelClass' => 'labels',
            'title' => 'Hello World!',
        ]);
```

**Comment by xandedj** [comment]
Deu erro em anexo



2017-09-12 11:19 GMT-03:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Make sure you update the dependency with:

`composer update`

**Comment by xandedj** [comment]
I ran the composer update and nothing, not this loading a class nor the
latest styles, does it tell me a problem for conflicts with bootstrapp 3?

2017-09-13 5:04 GMT-03:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
No, the package doesn't conflict with bootstrap 3. 

No, im afraid `labelOrigin` isnt supported currently.
