### ISSUE TITLE
Rendering the map alters my page's fonts?

### ISSUE THREAD

**Issue by gmask** [bradcornford/Googlmapper#144]
Calling `{!! Mapper::render() !!}` messes the way fonts are being displayed: here are some screenshots: http://imgur.com/a/SjsaR

What is causing this? I combed through the views and don't see those styles set anywhere.

**Comment by bradcornford** [comment]
Hi there,

This is a strange one, what browser are you seeing this on? Can you try another browser too. I assume its something to do with how the browser renders canvas objects.

**Comment by gmask** [comment]
Seems to affect Edge, Chrome, and Firefox the same.

**Comment by bradcornford** [comment]
I can't seem to replicate the issue myself. You could try adding important to you font-family classes.

**Comment by bradcornford** [comment]
I've done some searching, and it appears that the following CSS is required on all affected selectors, see: https://stackoverflow.com/questions/5498770/why-is-an-embedded-google-map-altering-safaris-font-rendering

```
-webkit-font-smoothing: antialiased;
```
