### ISSUE TITLE
Google Maps API warning

### ISSUE THREAD

**Issue by shinokada** [bradcornford/Googlmapper#145]
Hi, I get the following warning.
How can I fix the problem?

util.js:220 
Google Maps API warning: SignedInNotSupported https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported

**Comment by bradcornford** [comment]
Hi there,

This is just a warning at the moment. It's on my list of things to remove. It however doesn't affect performance at the moment.

**Comment by kevinp1005** [comment]
Hi, is this still just a warning? I tried the polygon and circle, as well as information windows, and it's not working, does it has anything to do with this?

**Comment by bradcornford** [comment]
I've now removed Signed in Support from the package in current version v2.31.4/v1.25.
