### ISSUE TITLE
Error handing

### ISSUE THREAD

**Issue by shinokada** [bradcornford/Googlmapper#147]
In my app, there might be a situation that there is no address entered  or wrong address entered. And I may get the following

> MapperSearchResultException in Mapper.php line 160:
> No results found for the location search.

What is the best way to handle this error? `try and catch`? 

I tried this but not working.

            try{
            Mapper::location($location)->map( ['zoom' => 14, 'markers' => ['title' => 'My Location', 'animation' => 'DROP']] );
            } catch (Exception $e) {
                $this->data['nomap'] = "No map";
            }

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply!

Yes, a try catch is the best way to handle this. Try:

```php
        try{
        Mapper::location($location)->map( ['zoom' => 14, 'markers' => ['title' => 'My Location', 'animation' => 'DROP']] );
        } catch (\Exception $e) {
            $this->data['nomap'] = "No map";
        }
```

**Comment by shinokada** [comment]
Thanks, it works.
