### ISSUE TITLE
Blank Map 

### ISSUE THREAD

**Issue by mourareaupro** [bradcornford/Googlmapper#148]
I try to display a map , it worked one time now i get the map blank ! Where i'm doing it wrong ? 

Here my controller 

use : 
```
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

 $render = Mapper::location($rencontre->stade->adresse_stade);

dd($render);
```

I get : 

```
Location {#965 ▼
  #search: "AVENUE DE MAZICOU"
  #address: "Avenue de Mazicou, 81000 Albi, France"
  #type: "route"
  #latitude: 43.9420004
  #longitude: 2.1453354
  #placeId: "ChIJx0Af5h_orRIRpEZaAtfCUGM"
}

```

my view : 

 <div style="width: 500px; height: 500px;">
                        {!! Mapper::render() !!}
                    </div>

**Comment by bradcornford** [comment]
Hi there,

Your nearly there, as you can see when you call the location method it returns a location object, you can then call map on this method to create a map for that location, i.e. location()->map ()

**Comment by mourareaupro** [comment]
Thanks for the answer ! it's working on Firefox but in chrome or Safari i get only the red flag on the map . It's a problem by my side ?

**Comment by bradcornford** [comment]
No problem. I'm not sure, you'd have to check your browsers error console and send me the error to check.

**Comment by mourareaupro** [comment]
Ok when i display in a body content all is fine but when i want to display to my modal the map is blank 

here my modal : 

```
<!-- Modal -->
    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Plan d'accès <i class="fa fa-info-circle" data-toggle="popover" data-placement="bottom" title="MAP" data-content="Si la map ne s'affiche pas correctement sur votre navigateur, vous pouvez cliquer en haut à droite sur le carré pour mettre la map en grand"></i></h4>
                </div>
                <div class="modal-body">

                    <div style="width: 500px; height: 500px;">
                        {!! Mapper::render() !!}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- ./modal -->
```

**Comment by hamodi** [comment]
are you trying to do {!! Mapper::render() !!} more than once on the same page?

**Comment by bradcornford** [comment]
Hi there,

This is a known issue with Bootstrap modals, and Google Maps. There is a simple workaround however:

```
$('#myModal1').on('shown.bs.modal', function () {
  google.maps.event.trigger(maps[0].map, 'resize');
});
```
