### ISSUE TITLE
Map Not Rendering in @section('content')

### ISSUE THREAD

**Issue by martin9908** [bradcornford/Googlmapper#149]
Hi Brad, I need help with your googlmapper. When I add it as a @section('content') in my blade.php file the map is not rendering but when I remove the @extends and @section from my file the map is rendering fine.

**Comment by martin9908** [comment]
I found the error and fixed it.. 👍

**Comment by bradcornford** [comment]
Hi there,

How did you manage to fix this? Just for future reference.
