### ISSUE TITLE
Location Method Params 

### ISSUE THREAD

**Issue by mourareaupro** [bradcornford/Googlmapper#151]
Hello , i would like to make the location with adresse & zip code as : 

  Mapper::location($stade->adresse_stade , $stade->zip_code_stade)->map();

This not work at the moment , i need to make the location with this two params if not i get localized any other city and sometimes countries ! hope someone could help

**Comment by bradcornford** [comment]
Hi there,

Can you not just merge the two items into a string, for example:

```php
Mapper::location($stade->adresse_stade . ' '. $stade->zip_code_stade)->map();
```

**Comment by mourareaupro** [comment]
hello :) it's working ! thanks a lot !

**Comment by bradcornford** [comment]
Great!
