### ISSUE TITLE
Error when initializing the map

### ISSUE THREAD

**Issue by isd89** [bradcornford/Googlmapper#152]
hello family!
i have used the installation and the configuration as said. but when i initialize the map in my controller as said in the Example i get thise error:

> Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically, assuming $this from incompatible context

 here is my controller:

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Cornford\Googlmapper\Mapper;
class GestionEtabSanitaireController extends Controller
{
    public function getmap()
	{
      Mapper::map(53.381128999999990000, -1.470085000000040000);
    return view('admin.map');
	}
}`

**notice that am using laravel 5.3**
i need your help...
thank you

**Comment by isd89** [comment]
its ok it works now
I should not use the Mapper class, but rather the MapperFacade when utilising the class as this
use Cornford\Googlmapper\Facades\MapperFacade as Mapper; 
in the place of this one
use Cornford\Googlmapper\Mapper;

**Comment by bradcornford** [comment]
Hi there,

Glad you got to the bottom of this.
