### ISSUE TITLE
How to get data from marker

### ISSUE THREAD

**Issue by Playbert** [bradcornford/Googlmapper#157]
I need to get data with the marker (lat, lon) to save in DB in variable

**Comment by bradcornford** [comment]
Hi there,

Can you explain this a little more. Are you adding markers dynamically etc?

**Comment by Playbert** [comment]
I am adding directions in Database, but need save latitude and longitude, but my real problem is I need to get and save the data "lon and lat" with the marker in real time. 

I place the marker on the map using this method:

`    google.maps.event.addDomListener(window, 'load', new function() 
    {
        setTimeout(function () {
            google.maps.event.addListener(maps[0].map, 'click', function(event) {
                maps[0].markers[0].setPosition(event.latLng);
            });
        }, 500);
    });`
Is it possible to retrieve the latitude and longitude of the marker, then store it in the database?

I'm working with (Laravel-MongoDB)

**Comment by bradcornford** [comment]
You will need to post the position data to your application using ajax. Something like this should work:

```js
<script type="text/javascript">

    google.maps.event.addDomListener(window, 'load', new function() {
        setTimeout(function () {
            google.maps.event.addListener(maps[0].map, 'click', function(event) {
                maps[0].markers[0].setPosition(event.latLng);
                $.ajax({
                    type: "POST",
                    url: '/ajax',
                    data: event.latLng.serialize()
                });
            });
        }, 500);
    });

</script>
```

```php
    public function store(array $request)
    {
        Position::create($request->input('location'));

        return response()->json(['status' => 'success']);
    }
```
