### ISSUE TITLE
How to plot multiple markers in Maps?

### ISSUE THREAD

**Issue by mchalise** [bradcornford/Googlmapper#159]

**Comment by bradcornford** [comment]
Hi there,

You can achieve this as follows:

```php
Mapper::map(53.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000);
```

**Comment by mchalise** [comment]
I just used above data but no luck. Could you please help me on this one. I need to plot different marker's in different coordinate and draw a line between them.

![map](https://user-images.githubusercontent.com/11830928/27028678-3a322d8a-4f85-11e7-9961-874f1527c6b5.jpg)

**Comment by bradcornford** [comment]
The above was only some example code, all the markers are added at the same location. You would need to alter the latitude and longitude to show them in different places. Also you may want to turn off clustering of markers, see below:
 
```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['cluster' => false]);
```

As for adding lines, this is would be achieved as follows:

```php
            Mapper::polygon(
                [
                    ['latitude' => 53.381128999999990000, 'longitude' => -1.470085000000040000], 
                    ['latitude' => 52.381128999999990000, 'longitude' => 0.470085000000040000]
                ]
            );
```

**Comment by keithgulbro** [comment]
@mchalise That's a great question. My solution is as follows:

This is the code I inserted into the controller:
```
    public function index()
    {

      <!-- Fill the following array with maps you'd like create -->
      $maps = [];

      foreach($maps as $map) {

        Mapper::map(Insert_Latitude, Insert_Longitude);

      return view('sample', compact('maps'));
    }
```

This is the code I inserted into a `example.blade.php` file:
``` 
    <ul>
     @foreach ($maps as $key => $map)
        <li>
        {!! Mapper::render($key) !!}
       </li>
     @endforeach
    </ul>
```

Additionally, simply adding a map with a series of maps with a known latitude and longitude can be done as follows:


Controller code would be represented as:
```
    public function index()
    {

       <!-- Index 0 -->
        Mapper::map(Insert_Latitude, Insert_Longitude); 

       <!-- Index 1 -->
        Mapper::map(Insert_Latitude, Insert_Longitude);

       <!-- Index 2 -->
        Mapper::map(Insert_Latitude, Insert_Longitude);

    }
```

`example.blade.php` would be written as follows:
``` 
    <ul>
      <li>
        {!! Mapper::render(0) !!}
      </li>

      <li>
        {!! Mapper::render(1) !!}
      </li>

      <li>
        {!! Mapper::render(2) !!}
      </li>
    </ul>
```
