### ISSUE TITLE
Please add mouse behavior support

### ISSUE THREAD

**Issue by Sennik** [bradcornford/Googlmapper#16]
Hi there, thanks for your good work, I love it!

Please think about adding mousewheel support to Googlmapper. I am using Googlmapper at full width in my webpages and everytime I am scrolling my page with my mousewheel and as soon as the mouse pointer is over the map scrolling stops and instead the map is zooming in or out. I am sure a lot of people experience this behavior. It is not logical.

**Comment by bradcornford** [comment]
This is the functionality of Google Maps by default, if you want to alter this behaviour you would have to add a script along the line of the below to stop mouse wheel.

```javascript
map_0.disableScrollWheelZoom();
```

**Comment by Sennik** [comment]
Yes, I know this is default behavior of Google Maps. But how often will users use this functionality full screen? In most cases it will be a part of the page like for example a map just above (or inside) the footer (with address etc). So a visitors scrolls over it with his mousewheel and suddenly scrolling stops and the map starts zooming in or out, depending on the scroll direction. An extra option in GooglMapper like 'scrollwheelzoom' => false will come in very handy for a lot of users.

**Comment by bradcornford** [comment]
Oh, I understand what you are suggesting ow,

**Comment by Sennik** [comment]
This looks great! I will try it when I am able to work on the project. Should be today. Thanks sofar!

**Comment by Sennik** [comment]
Sorry I had to let you wait but my project is still in development and not ready for the map yet. I pulled in de delopment branch with composer: "cornford/googlmapper": "dev-master"

The map is still zooming when I pass it while scrolling through the page with the scroll wheel.

I added:

    /*
     |--------------------------------------------------------------------------
     | Scroll wheel Zoom
     |--------------------------------------------------------------------------
     |
     | Set if scroll wheel zoom should be used by Googlmapper.
     |
     */
    'scrollWheelZoom' => false,

to the googlmapper.php config file. Also tried putting it in the construction, same result.

Did you remove the function by accident or am I doing something wrong?

**Comment by bradcornford** [comment]
Hi again,

No you'd have to pull in "cornford/googlmapper": "dev-develop" as your dependency to use this functionality.

**Comment by bradcornford** [comment]
Did you have any luck with this?

**Comment by Sennik** [comment]
Yes I have. Used it yesterday with success. Thank you!

**Comment by bradcornford** [comment]
Okay, i'll get this versioned into master sometime today. Thanks for your help!

**Comment by bradcornford** [comment]
This has now been merged to master and version as 2.3.0.
