### ISSUE TITLE
Get map information variables

### ISSUE THREAD

**Issue by smlabonia** [bradcornford/Googlmapper#160]
Hi,

Thanks for this tool! It's awesome!

I have this:

`Mapper::map(-34.620212, -58.446236)->rectangle([['latitude' => -34.6864020, 'longitude' => -58.5284970], ['latitude' => -34.5383410, 'longitude' => -58.3582090]], ['strokeColor' => '#000000', 'strokeOpacity' => 1, 'strokeWeight' => 4, 'fillColor' => '#FFFFFF', 'editable' => true]);`

Now, i need recover the drawn rectangle on the map. It's editable, and have to use the "from" lat-long and the "to" lat-long variables.

Appreciate your collaboration!

Thanks a lot.

**Comment by smlabonia** [comment]
I've got it!

```
$map = Mapper::map(-34.620212, -58.446236)->rectangle([['latitude' => -34.6864020, 'longitude' => -58.5284970], ['latitude' => -34.5383410, 'longitude' => -58.3582090]], ['strokeColor' => '#000000', 'strokeOpacity' => 1, 'strokeWeight' => 4, 'fillColor' => '#FFFFFF', 'editable' => true]);

        $options = $map-> getItems()[0]-> getShapes()[0]-> getOptions();
        
        $from_latitude = $options['coordinates'][0]['latitude'];
        $from_longitude = $options['coordinates'][0]['longitude'];
        $to_latitude = $options['coordinates'][1]['latitude'];
        $to_longitude = $options['coordinates'][1]['longitude'];
```

Someone who knows a better way?

**Comment by bradcornford** [comment]
Hi there,

You can do it like you purposed, or you can add an event listener for changes to submit the shape data via ajax. See this: https://developers.google.com/maps/documentation/javascript/events
