### ISSUE TITLE
How to set popup

### ISSUE THREAD

**Issue by markmuigai** [bradcornford/Googlmapper#162]
How do I set a pop up that displays information in a view when I click a marker? Example, property title, type and price.
Or should I pass this information through my mapController?

**Comment by bradcornford** [comment]
Hi there,

This sounds like you need to use information windows, try the following:

```php
Mapper::map(53.281128999999990000, -1.480085000000040000, ['marker' =>  false]);
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content');
```

**Comment by markmuigai** [comment]
okay...seems I was trying to set my infowindow to show when I click a custom icon. How do I pull this off in this case?
Mapper::marker(-1.196726, 36.754797, ['icon' => '/images/icon.png', 'scale' => 1000, informationWindow( 'content')]);

**Comment by bradcornford** [comment]
Hi there,

Again this can be achieved using information windows, for example:

```
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content', ['icon' => '/images/icon.png', 'scale' => 1000]);
```

**Comment by markmuigai** [comment]
Thanks.
