### ISSUE TITLE
How to show current location  ?

### ISSUE THREAD

**Issue by t3k0o** [bradcornford/Googlmapper#163]
I have an issue I don't know how to set up current location with GooglMapper. I couldn't figure out how to show current user location on the map.

**Comment by bradcornford** [comment]
Hi there,

Yes, this is possible. It can be achieved as follows:

```php
Mapper::map(0, 0, ['locate' => true]);
```

**Comment by t3k0o** [comment]
Hi there
by using this code
`Mapper::map(0, 0, ['locate' => true]);`
mapper send you to long "0" lat "0" but not your current location.
thanks.

**Comment by bradcornford** [comment]
The above will only work if you allow your browser to locate your position.

**Comment by bradcornford** [comment]
Otherwise you may want to locate the users position by using there IP address.
