### ISSUE TITLE
Non-static method Cornford\Googlmapper\Mapper::render() should not be called statically

### ISSUE THREAD

**Issue by davidem27** [bradcornford/Googlmapper#165]
Hi @bradcornford,
I red about this issue in every single page of Issues forum of this repo. Still having the problem.

That's my situation:

config/app.php
#providers
`Cornford\Googlmapper\MapperServiceProvider::class`
#aliases
`'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class`

#my controller
```
use Cornford\Googlmapper\Facades\MapperFacade as Mapper

Mapper::map(53.381128999999990000, -1.470085000000040000); #as your example guide
```

#my view
`{!! \Cornford\Googlmapper\Mapper::render() !!}`

using {!! Mapper::render() !!} it gets another error message:

syntax error, unexpected end of file

I'm still just debugging, but can't find the solution.

Any idea?

Laravel v. 5.3.31

**Comment by davidem27** [comment]
Solved. Thanks.

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply, what was the issue? Do you mind explaining the solution.

**Comment by t-prod** [comment]
Hi,

I agree what's your solution cause I gave the same issue on Laravel 5.4.
Thanks for your help.

Regards

**Comment by t-prod** [comment]
Ok I'm answering myself.
You must use the following Facade with this line
`use Cornford\Googlmapper\Facades\MapperFacade as Mapper;`
