### ISSUE TITLE
How to draw a maps and passing variable on informationwindow

### ISSUE THREAD

**Issue by kembar000** [bradcornford/Googlmapper#167]
Sir . Is this can draw a maps and passing variables on informationwindow ? i mean  part / part of maps

**Comment by bradcornford** [comment]
Hi there, 

Can you please explain what you require in more detail?

Heres how you would add a map, with an information window:

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['marker' => false]);
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content');
```
