### ISSUE TITLE
Alert marker id

### ISSUE THREAD

**Issue by zubinkadva** [bradcornford/Googlmapper#168]
Hi. Excellent library. I am creating dynamic markers as:

    $locations = $model->getLocations();
    foreach ($locations as $location) {
        Mapper::marker($location->lat, $location->lng, 
              ['center' => true, 
               'eventClick' => 'alert("$location->id")']);
    }

I am trying to get the marker click by simply alerting its id. But it does not work. Can you help me? Thanks.

**Comment by mrkalmdn** [comment]
@zubinkadva, can you try this code

```
'eventClick' => 'alert("'.$location->id.'")'
```

**Comment by zubinkadva** [comment]
Thanks. That works.

**Comment by bradcornford** [comment]
Hi there,

Glad you got this sorted, you can also reference the event itself within the fired event, for example:

```
$locations = $model->getLocations();
foreach ($locations as $location) {
    Mapper::marker(
        $location->lat,
        $location->lng, 
        ['center' => true,  'eventClick' => 'alert(alert(event.latLng.toString()))']
    );
}
```
