### ISSUE TITLE
Map not showing #helpwanted

### ISSUE THREAD

**Issue by sbourdette** [bradcornford/Googlmapper#170]
Sorry but I have exactly the same problem of #40 but I have a Mapper::Map in my controller.

I have tried to use 
`
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
`
but the result is the same
AlbumController.php : 

`namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Cornford\Googlmapper\Mapper;
class AlbumController extends Controller
{
   public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);
        
        return view('album');
    }
}`

album.blade.php :

`                                    <tr>
                                        <td class="table-text"><div>Maps</div></td>
                                        <td>{!! Mapper::render() !!}</td>
                                        <td>&nbsp;</td>
                                    </tr>`

Generated html source :

<div class="ui embed"><script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&region=FR&language=fr&key=XXXXXXX&signed_in=false&libraries=places"></script>

        <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script>

</div>

**Comment by sbourdette** [comment]
Sorry for the format of my post ...

**Comment by sbourdette** [comment]
in the src of the generated render the http: is missing

**Comment by sbourdette** [comment]
My fault i used the wrong controller ...

You can close

**Comment by bradcornford** [comment]
Hi there, 

Sorry for the late reply. Yes it is correct that http: is missing, this means that the includes will be protocol agnostic, i.e. they will utilise whatever the page protocol currently is (HTTP/HTTPS).
