### ISSUE TITLE
Cannot get variables from the config file, "Google maps API key is required." ERROR

### ISSUE THREAD

**Issue by kylops** [bradcornford/Googlmapper#171]
Hello, Brad,

I was using your plugin these days trying to implement a googlemap on my site. I followed all installation steps and set a variety of variables. **I am on laravel 5.4.**

I stuck in this error: "Google maps API key is required.". Even I try to hard set the API in your core function, then it throws another error says "region is required". seems like the config file cannot be reached. I also tried to fix the file permissions, but unfortunately that's not the issue. Do you have any ideas about this?
This is part of my **controller file**   
```
use Cornford\Googlmapper\Mapper;
use Cornford\Googlmapper\Facades\MapperFacade;
use Illuminate\Support\Facades\Route;

   public function index(Mapper $mapper)
   {
        ............
        $firstMapItem = reset($mapArrays);
        $mapper->map(
         $firstMapItem->latitude, $firstMapItem->longitude,
         [
            'zoom' => 10,
            'markers' => ['title' => 'My Location', 'animation' => 'DROP'],
            'clusters' => ['size' => 10, 'center' => true, 'zoom' => 20]
         ]
      );
      
      // Add information window for each address
      foreach ($mapArrays as $mapArray) {
         $mapper->marker($mapArray->latitude, $mapArray->longitude);
      }
}
```

**Route**
`Route::get( '/map', 'MapController@index');`

**view**
```
<div style="width: 100%; height: auto;">
	{!! Mapper::render() !!}
</div>
```

Thank you so much!

**Comment by kylops** [comment]
@zubinkadva thanks for the reply. I already changed the API value there, my problem is this API value has not been referenced. But if I move the Mapper function from the controller to the Route file, everything is fine. But if I do what I did as above, the API value from the googlmapper.php file isn't  referenced.

**Comment by zubinkadva** [comment]
Ok. In your controller, change the use statements to:
````
use Mapper;
use Illuminate\Support\Facades\Route;
````

Don't use anything else. See if that works.

**Comment by kylops** [comment]
Wow, amazing! @zubinkadva It works! 
change
`use Cornford\Googlmapper\Mapper;`
to
`use Mapper;`
Very simply Facades things I think. Thank you a lot!

**Comment by kylops** [comment]
I'll close this issue. Thanks again!

**Comment by bradcornford** [comment]
Hi there,

The solution @zubinkadva provided does work, however for reference you can also use the following:

```
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
```
