### ISSUE TITLE
how to plot a marker from database?

### ISSUE THREAD

**Issue by ivandgreat** [bradcornford/Googlmapper#172]
How can i plot a markers on the map using my database?

public function index()
    {
        $mapArrays= Location::all();
        dd($mapArrays);
    }

**Comment by mrkalmdn** [comment]
You can do it this way, assuming that your location table has a column of lat and long.

```php
public function index()
{
    $mapArrays = Location::all();

    foreach($mapArrays as $location)
    {
        Mapper::map($location->lat, $location->long);
    }

    return view('map');
}
```

and in your `map.blade.php`

```html
<div style="width: 500px; height: 500px;">
	{!! Mapper::render() !!}
</div>
```

**Comment by ivandgreat** [comment]
I only have 5 locations in my db, but it shows 6 markers. 

But when dd($mapArrays) it only show 5 collections.

How can i add the infowindow fot each markers?

thanks for your help.

**Comment by mrkalmdn** [comment]
Just add the `Mapper::information()` inside your loop.

```php

foreach($mapArrays as $location)
{
    Mapper::informationWindow($location->lat, $location->long, 'Content', ['open' => true, 'minWidth' => 300]);
    Mapper::marker($location->lat, $location->long);
}

```

**Comment by ivandgreat** [comment]
I just notice, from the above code, it will create duplicate markers, since i enable my cluster, it show 11 markers, instead of 5 only.

i disregard the, 
     Mapper::marker($location->lat, $location->long);

This is my final code, 

```
public function index()
    {
        $mapArrays= Location::all();
        Mapper::map(21.5545, 39.1672, ['marker' => false, 'type' => 'ROAD']);
        foreach ($mapArrays as $mapArray) {
          Mapper::informationWindow($mapArray->lat, $mapArray->lng, $mapArray->site, ['open' => false, minWidth' => 300]);
        }
        return view('map.index',compact('mapArrays'));
    }
```

**Comment by mrkalmdn** [comment]
Glad to help! You should close this if you already solved your issue.

**Comment by bradcornford** [comment]
Hi there,

Glad you got the help you needed =) thanks @mrkalmdn
