### ISSUE TITLE
Help with information window - Can it open on MouseOver?

### ISSUE THREAD

**Issue by mjbain10** [bradcornford/Googlmapper#173]
First, this is an awesome tool, thanks so much. You've saved me hours of work.

Second, I was wondering if I could open the information window for markers on MouseOver instead of the default on click.

Thank you!

**Comment by zubinkadva** [comment]
According to the readme:

````
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventMouseOver' => 'console.log("mouse over");']);
````

**Comment by mjbain10** [comment]
I tried using the mouseOver event for the markers already. Sorry, let me try and explain my question better. 

I'm not sure how to programmatically open the information windows using the marker event function when the info windows are created in the Controller with this tool. If I create them using the plain Google API javascript I can get it to work with .open(), but not when creating them in the Controller using this tool.

**Comment by bradcornford** [comment]
Hi there,

Glad you like it. @zubinkadva is close to the solution, its not ideal, but does work, try this:

```php

Mapper::informationWindow(54.9, -2.9, 'Test', ['eventMouseOver' => 'new google.maps.event.trigger(maps[0].markers[0], "click");', 'eventMouseOut' => 'maps[0].infowindows[0].close();']);

```

**Comment by mjbain10** [comment]
I took a break from this project, and then came back and tried your solution and got it working. Thanks!

**Comment by bradcornford** [comment]
Glad this worked for you!
