### ISSUE TITLE
Distinguish marker click

### ISSUE THREAD

**Issue by zubinkadva** [bradcornford/Googlmapper#174]
Hi. I want to **distinguish between multiple marker clicks**. So, when the user click on a marker for instance, I was thinking of changing its icon. I would also need to restore the default icon.

Any suggestions on how this can be achieved?

Also, is there any method by which I can **redraw all markers**. Currently I am refreshing the page.

Thanks.

**Comment by zubinkadva** [comment]
So, I have 3 ways to approach this. I have posted only relevant code.

**Method 1: Drawing a circle around the marker**

Controller:
````
Mapper::marker(lat, lng, ['eventClick' => 'draw(event.latLng)']);
````

Javascript:
````
    var circles = [];

    function clearArray() {
        for (var i = 0, len = circles.length; i < len; i++) {
            circles[i].setMap(null);
        }
        circles = [];
    }

    function draw(latLng) {
        clearArray();
        var cityCircle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.35,
            map: maps[0].map,
            center: {lat: latLng.lat(), lng: latLng.lng()},
            radius: 1000
        });
        circles.push(cityCircle);
    }
````

**Method 2: Setting an icon dynamically**

Controller:
````
Mapper::marker(lat, lng, ['eventClick' => 'icon($index)']);
````
_Note: $index is index variable in foreach loop_

Javascript:
````
    var previous = 0;
    function icon(index) {
        maps[0].markers[previous].setIcon();
        previous = index;
        maps[0].markers[index].setIcon('{{asset('current.png')}}');
    }
````

**Method 3: Setting animation dynamically**
Controller:
````
Mapper::marker(lat, lng, ['eventClick' => 'bounce($index)']);
````
_Note: $index is index variable in foreach loop_


Javascript:
````
    var previous = 0;
    function bounce(index) {
          maps[0].markers[previous].setAnimation(null);
          previous = index;
          maps[0].markers[index].setAnimation(google.maps.Animation.BOUNCE);
    }
````

**Comment by bradcornford** [comment]
Hi there,

@zubinkadva yeah your solutions are all possible, :

```php

Mapper::informationWindow(54.9, -2.9, 'Test', ['eventMouseOver' => 'maps[0].markers[0].setIcon({
            path: google.maps.SymbolPath.CIRCLE,
            scale: 10,
            fillColor: "#00F",
            fillOpacity: 0.8,
            strokeWeight: 1
        });']);

```

You have access to all maps, markers, and information windows. It would be possible to re-draw when needed, via the following access variables:

```
maps[index]
maps[index].markers
maps[index].infowindows
```

**Comment by zubinkadva** [comment]
So, user clicks on the map and I set a marker and save it to database. Now user selects it, so I need to change it animation. How do I get its index, so that I can set animation?

**Comment by bradcornford** [comment]
I'm not sure how you could look up an index for the item dynamically added to the map. You could just add an event listener when you create your marker itself.
