### ISSUE TITLE
putting all marker positions to show directions

### ISSUE THREAD

**Issue by vivek7890** [bradcornford/Googlmapper#178]
Hi, I am trying to show trip journey on map. I am able to store all marker positions after selecting locations in a array but I am not able to put this array into the map to show all additional places.

**Comment by bradcornford** [comment]
Hi there,

You can just loop over all your locations, adding markers like the following:

```php
Mapper::map(
    0,
    0,
    ['marker' => false]
);

foreach ($markers as $marker) {
Mapper::informationWindow(
    $marker['latitude'],
    $marker['longitude'],
   'content'
);
}
```

**Comment by vivek7890** [comment]
sorry, I think I could not explain correctly. What I want to show is I want to show breakup journey. Suppose I want to go somewhere and if I would like to stay somewhere in between I will and then again I will start my journey to the final destination. There can be many stops in between. In a static way I have done this way. I have defined all positions in the waypoints.

function addRoute(map) {

                var directionsService = new google.maps.DirectionsService();
                var directionsDisplay = new google.maps.DirectionsRenderer();
                directionsDisplay.setPanel(document.getElementById('panel'));
                directionsDisplay.setMap(map);

                var request = {
                    origin: '{{ $origin }}',
                    destination: '{{ $destination }}',
                    waypoints: [
                      {
                        location: 'delhi',
                        stopover: true
                      },{
                        location: 'kolkata',
                        stopover: true
                      },
                      {
                        location: 'mumbai',
                        stopover: true
                      }
                    ],
                    provideRouteAlternatives: true,
                    unitSystem: google.maps.UnitSystem.IMPERIAL,
                    travelMode: 'DRIVING',
                    drivingOptions: {
                      departureTime: new Date("July 26, 2017 21:13:00"),
                      trafficModel: 'pessimistic'
                    }
                };

                {{--var route = {!! $route !!};--}}
                {{--route.request = request;--}}
                {{--directionsDisplay.setDirections(route);--}}

                directionsService.route(
                    request,
                    function(response, status) {
                        if (status == google.maps.DirectionsStatus.OK) {
                            directionsDisplay.setDirections(response);
                        }
                    }
                );
            }

**Comment by vivek7890** [comment]
`function addRoute(map) {

                var directionsService = new google.maps.DirectionsService();
                var directionsDisplay = new google.maps.DirectionsRenderer();
                directionsDisplay.setPanel(document.getElementById('panel'));
                directionsDisplay.setMap(map);

                var request = {
                    origin: '{{ $origin }}',
                    destination: '{{ $destination }}',
                    waypoints: [
                      {
                        location: 'delhi',
                        stopover: true
                      },{
                        location: 'kolkata',
                        stopover: true
                      },
                      {
                        location: 'mumbai',
                        stopover: true
                      }
                    ],
                    provideRouteAlternatives: true,
                    unitSystem: google.maps.UnitSystem.IMPERIAL,
                    travelMode: 'DRIVING',
                    drivingOptions: {
                      departureTime: new Date("July 26, 2017 21:13:00"),
                      trafficModel: 'pessimistic'
                    }
                };

                {{--var route = {!! $route !!};--}}
                {{--route.request = request;--}}
                {{--directionsDisplay.setDirections(route);--}}

                directionsService.route(
                    request,
                    function(response, status) {
                        if (status == google.maps.DirectionsStatus.OK) {
                            directionsDisplay.setDirections(response);
                        }
                    }
                );
            } `

**Comment by vivek7890** [comment]
Thank you for your reply. I manged to do it but now I have one more issue, now I want to show optimised distance between each points. How can I do it.

**Comment by vivek7890** [comment]
Thank you I could solve.
