### ISSUE TITLE
How add many markers at once.

### ISSUE THREAD

**Issue by jzebala** [bradcornford/Googlmapper#180]
I would like to add multiple markers to the map at once.

        Mapper::map(0, 0,
            [
                'zoom' => 15,
                'draggable' => true,
                'marker' => false,
                'center' => false,
                'markers' => ['title' => 'To jest właśnie tutaj!', 'animation' => 'DROP'],
                
            ])
        ->marker(50.061711, 19.937356)
        ->marker(50.063693, 19.911742)
        ->marker(50.057979, 19.920445)
        ->marker(50.054466, 19.936655);

I have created something like that but I need to add any value manually.
Does anyone know how to do this automatically to retrieve data from mysql or array.

**Comment by mrkalmdn** [comment]
Hi! You can try the suggestions in this issue #172.

**Comment by bradcornford** [comment]
Hi there, 

You can create a map individually, then iterate over a foreach to create markers:

```php

Mapper::map(0, 0,
        [
            'zoom' => 15,
            'draggable' => true,
            'marker' => false,
            'center' => false,
            'markers' => ['title' => 'To jest właśnie tutaj!', 'animation' => 'DROP'],
            
        ]);

$markers = [
    ['lat' => 50.061711, 'lng' => 19.937356],
    ['lat' => 50.063693, 'lng' => 19.911742],
    ['lat' => 50.057979, 'lng' => 19.920445],
    ['lat' => 50.054466, 'lng' => 19.936655]
];

foreach ($markers as $marker) {
    Mapper::marker($marker['lat'], $marker['lng'])
}

```

**Comment by jomayan** [comment]
Has anyone tried adding a hundred or thousand markers?
Does it slow down the rendering?

**Comment by bradcornford** [comment]
A hundred seems to be okay, a thousand may be pushing it. Yes it would affect rendering if you had a large numbers of markers. How much so is hard to say though. An option would be to add x amount to the map at load, then add an event listener to add more after page load.
