### ISSUE TITLE
Scale controls

### ISSUE THREAD

**Issue by robbecreates** [bradcornford/Googlmapper#181]
I am trying to enable the scale controls as you can see on maps.google.com in the right hand bottom corner, but keep failing. I tried using 'scaleControl' in the initialisation, but this does not work.

My code for the initialisation: 
`Mapper::map(51.2359154,3.2129791, ['scaleControl' => true, 'fullscreenControl' => true, 'zoom' => 9, 'scrollWheelZoom' => true, 'marker' => false, 'clusters' => ['size' => 2, 'center' => true, 'zoom' => 10, 'icon' => asset('img/map/cluster') ]]);`

Can you point me to where things are going wrong please?

**Comment by bradcornford** [comment]
Hi there, 

Are you referring to the + / - and locations buttons bottom right of the map? If so these should be added automatically.

Here is the map i see with your above code:

<img width="1027" alt="screen shot 2017-08-01 at 09 03 50" src="https://user-images.githubusercontent.com/2913887/28815172-5e8fda44-7698-11e7-97c3-5fce87831ab4.png">

**Comment by bradcornford** [comment]
Actually, i know what you mean now, ill look at introducing this along with the other control options.

**Comment by bradcornford** [comment]
Okay, i've pushed this feature under current versions v2.26.0/v1.21.0. Let me know how you get on.

**Comment by robbecreates** [comment]
Thanks for the quick reply!

I just updated to the latest version, but it does not seem to work. Tried this code now:
`Mapper::map(51.2359154,3.2129791, ['scaleControl' => true, 'zoomControl' => false, 'zoom' => 9, 'scrollWheelZoom' => true, 'marker' => false, 'clusters' => ['size' => 2, 'center' => true, 'zoom' => 10, 'icon' => asset('img/map/cluster') ]]);`

That gets me this map:
<img width="1036" alt="screen shot 2017-08-01 at 11 37 33" src="https://user-images.githubusercontent.com/7987091/28819257-ea5f3faa-76ad-11e7-9998-6c38d963f21d.png">
(icon on the left hand bottom is a custom one from myself)

Zoom control is not disabled and there is no scale visible on the map. Looking at the javascript for the initialisation of the map I see that the code for the controls is not there.. Hope this helps to find the problem.

**Comment by bradcornford** [comment]
Hi there,

I wonder if the assets weren't re-published, try the below:

`php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper`

Heres what i have now, with your above code:

<img width="1026" alt="screen shot 2017-08-01 at 14 22 53" src="https://user-images.githubusercontent.com/2913887/28827277-f4d72a1c-76c4-11e7-9dae-a21f4d077d68.png">

**Comment by robbecreates** [comment]
Hi

The problem was indeed with the assets! The terminal code you provided worked, but just needed `--force` to make it work.

Thanks for all the help and adding the functionality!
