### ISSUE TITLE
Call to undefined method Cornford\Googlmapper\MapperServiceProvide

### ISSUE THREAD

**Issue by MichaelPtacek** [bradcornford/Googlmapper#183]
Hello, I am trying to use  Googlemapper in Laravel 5.4. Everything should be set-up correctly 

however when using this in my view:

`  {!! Mapper::render() !!}`

I receive an error: 

`

(1/1) FatalErrorExceptionCall to undefined method Cornford\Googlmapper\MapperServiceProvider::render()
--
in 72f73276391ec7eea6494d475d7d59b1b78ebe4b.php (line 135)

`
Any idea, why it could be? Thanks :)

**Comment by bradcornford** [comment]
Hi there,

Have you added all the configuration within you app.php configuration? It appears that the provider is being called, rather than the facade. Can you show me your configuration.
