### ISSUE TITLE
build a web application that draw the points on google map api with Laravel

### ISSUE THREAD

**Issue by abdolrhman** [bradcornford/Googlmapper#185]
Hello good people , 
i have a task which is to build a web app service , that can draw the points in google map api ,
 so that admin can build the routes from point a to point b , 
some thing like this : 
[google api direction drag](https://developers.google.com/maps/documentation/javascript/examples/directions-draggable)
now how to do this in laravel , plz help me am so confused about to build some thing like this in laravel .
thk in advance ^^

**Comment by bradcornford** [comment]
Hi there,

This isn't something that is natively available with this library, however it can be achieved by using events and hooks, see both  https://github.com/bradcornford/Googlmapper/issues/178 and https://github.com/bradcornford/Googlmapper/issues/135 for more information.

Also here is Google Maps documentation: https://developers.google.com/maps/documentation/directions/intro
