### ISSUE TITLE
Laravel 5.4 don't catch Exceptions

### ISSUE THREAD

**Issue by majweb** [bradcornford/Googlmapper#186]
Hi!

I use this package in laravel 5.4.
In my controler i have:
`try{
   foreach($user->connected_to_gyms as $key =>$man){
        Mapper::location("$man->city $man->street $man->local")->map(['zoom' => 15, 'center' => true, 
        'marker' => true, 'type' => 'roadmap']);
     }
   }catch(Exception $e){
          return view......
            }

@foreach($user->connected_to_gyms as $key =>$man)
                <div class="col-xs-12 col-md-3 text-center" style="height: 200px;">
                    {!! Mapper::render ($key) !!}
                </div>
            @endforeach`

I'cant catch exceptions what is wrong?

**Comment by bradcornford** [comment]
Hi there,

Try the following:

```php
try {
    foreach($user->connected_to_gyms as $key =>$man){
        Mapper::location("$man->city $man->street $man->local")->map(['zoom' => 15, 'center' => true, 'marker' => true, 'type' => 'roadmap']);
    }
} catch (\Exception $e) {
return view......
}
```

**Comment by majweb** [comment]
Its works!

tell me how pass variables with errors to blade and use if and else element?

**Comment by bradcornford** [comment]
You should be able to return your view, with an error key, for example:

```php
return view(...)->withErrors(['This is an error message']);
``
