### ISSUE TITLE
Help with plotting a location through a search box. 

### ISSUE THREAD

**Issue by abrhambas01** [bradcornford/Googlmapper#189]
Does this library has the capability to plot a location based on the user's query like for example when he search Times Square in the search box. It then goes to that location and plot it to the map.

**Comment by bradcornford** [comment]
Hi there,

Yes this is entirely possible, see the below post for more information around autocomplete / location marking: https://github.com/bradcornford/Googlmapper/issues/114

**Comment by xandedj** [comment]
Bom dia.

Há possibilidade de plotar no mapa o percurso executado de acordo com uma data hora inicial e data e hora final e o mapa exibir o percurso?

**Comment by bradcornford** [comment]
Hi there,

I dont speak Portuguese. However you could create an information window containing the information you require.

```
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'End Time: AAA');
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Start Time: BBB');
```

**Comment by xandedj** [comment]
helo

Funcionou apenas para um marcador e possuo diversos preciso plotar em cada marcador o seu nome,

segue código abaixo:
  Mapper::map(-22.886449, -43.118474,
              [   'marker'=>false,
                  'zoom' => 10,
                  'draggable' => true,
                  'center' => true,
                  'cluster' => false,
                  'informationWindow'=>'Texto'['open'=> true,
                  'markers' => [
                  'icon' =>'img/ida_22.png',
                  'title' => '166001',
                  'animation' => 'DROP']],

              ]);

              $markers = array(['lat' => -22.886449,'lng' => -43.118474],
                                ['lat' => -22.885632,'lng' => -43.118143],
                                ['lat' => -22.883990,'lng' => -43.119513],
                                ['lat' => -22.885734,'lng' => -43.124988]);

              foreach ($markers as $marker) {
       
                  Mapper::marker($marker['lat'], $marker['lng']);

              }

**Comment by xandedj** [comment]
Gostaria de saber também se conseguimos exibir o caminho percorrido por um veículo por exemplo de acordo com as coordenadas captadas por um equipamento de GPS por exemplo?

**Comment by xandedj** [comment]
Mias uma Ajudinha :)

Tenho um array assim:

array:10 [▼
  0 => "-22.886145457836463,-43.118764097835"
  1 => ",-22.88643210096987,-43.118324215556555"
  2 => ",-22.886694032959,-43.117846782351904"
  3 => ",-22.886763222456636,-43.11767512097496"
  4 => ",-22.886782990878046,-43.117605383540564"
  5 => ",-22.886886775043237,-43.11763757004875"
  6 => ",-22.887133879879073,-43.11891966595787"
  7 => ",-22.88630360584699,-43.11942392125267"
  8 => ",-22.886115805063966,-43.118823106433325"
  9 => ",-22.886145457836463,-43.118764097835 "
]

como posso utilizar o polyline, polygon, rectangle e circle?

**Comment by bradcornford** [comment]
Yes, you could plot lines onto the map based on these coordinates. 

You could use something as follows:

```php
$markers = [
	0 => "-22.886145457836463,-43.118764097835"
	1 => "-22.88643210096987,-43.118324215556555"
	2 => "-22.886694032959,-43.117846782351904"
	3 => "-22.886763222456636,-43.11767512097496"
	4 => "-22.886782990878046,-43.117605383540564"
	5 => "-22.886886775043237,-43.11763757004875"
	6 => "-22.887133879879073,-43.11891966595787"
	7 => "-22.88630360584699,-43.11942392125267"
	8 => "-22.886115805063966,-43.118823106433325"
	9 => "-22.886145457836463,-43.118764097835"
];

Mapper::map(0, 0, ['marker' => false]);

foreach ($markers as $key => $marker) {
    if (isset($markers[$key + 1])) {
    	$startLocation = explode(',', $marker);
    	$endLocation = explode(',', $markers[$key + 1]);
    	Mapper::polyline([['latitude' => startLocation[0], 'longitude' => startLocation[0]], ['latitude' => $endLocation[0], 'longitude' => $endLocation[1]]]);
    }
}
```
