### ISSUE TITLE
Problem with informationWindow

### ISSUE THREAD

**Issue by Eronte** [bradcornford/Googlmapper#19]
Hello

 I´m using yourt great library but I´ve a problem with informationWindow.
 All is integrated and the map is drawed with markers and without javascript errors.
 But when i try include an informationWindow, this does not appears.
 If I use a simple example like:
 ```
Mapper::map(52.381128999999990000, 0.470085000000040000)->informationWindow(53.381128999999990000, -1.470085000000040000, 'Content', ['markers' => ['animation' => 'DROP']]);
```
and make a render in view, the marker appear, the maps renders ok but when click over marker I can´t see the informationWindow.

Do you know where could be the problem?

Thanks!

**Comment by bradcornford** [comment]
Hi there,

I've just used the code you provided and it's working as expected. There are two markers, one at where the map is centered around Thetford, and another for the information window, which has the message "Content" located over Sheffield. Only the marker for which you have set as a information window will have a click action to display an information window.

**Comment by bradcornford** [comment]
Did you have any luck with this?
