### ISSUE TITLE
Trait 'App\Http\Controllers\Mapper' not found

### ISSUE THREAD

**Issue by andikawill** [bradcornford/Googlmapper#191]
Can anyone solve this issue?

**Comment by frijj2k** [comment]
Make sure in config/app.php you have under providers:

        Cornford\Googlmapper\MapperServiceProvider::class,

and under aliases:

        'Mapper'      => Cornford\Googlmapper\Facades\MapperFacade::class,

Then inside your controller, add the following at the top of the file:

        use Mapper;

or the full namespace is:

        use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

Hope that helps... :)

**Comment by bradcornford** [comment]
Hi there,

@frijj2k is correct with his comment, hope that works for you!
