### ISSUE TITLE
SignedInNotSupported

### ISSUE THREAD

**Issue by andikawill** [bradcornford/Googlmapper#193]
i use laravel infyom please help

the page still blank and this the error when i inspect elements:

Google Maps API warning: SignedInNotSupported https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported

**Comment by bradcornford** [comment]
Hi there,

That is just a warning, it can be ignored. Make sure you set a CSS height to the containing div that you are using for `{!! Mapper::render() !!}`

**Comment by jagbon** [comment]
Since signed_in feature is deprecated in Google map versions 3.27 and above, i advise to just simply remove the parameter "signed_in=true" in the file javascript.blade.php inside the cornford/googlmapper package. 

Or simply paste this code in the cornford/googlmapper/javascript.blade.php starting on line 5:

> @if ($options['async'])

        <script async defer type="text/javascript" src="//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&libraries=places&callback=initialize_method"></script>

    @else

        <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&libraries=places"></script>

    @endif

Google Developers mentioned it here : 
https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported
https://developers.google.com/maps/documentation/javascript/signedin

**Comment by bradcornford** [comment]
I've now removed Signed in Support from the package in current version v2.31.4/v1.25.

**Comment by syyou** [comment]
Error loading map after recent changes ... 
Undefined index: user ... ?signed_in=<?php echo $options['user']

Error on Laravel 5.5 
<?php echo $__env->make('googlmapper::javascript', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

Undefined index: user (View: /views/cornford/googlmapper/javascript.blade.php) (View: /resources/views/cornford/googlmapper/javascript.blade.php) (View: t/resources/views/cornford/googlmapper/javascript.blade.php)
/storage/framework/views/3928a500ce4f4f18b9b31f95298c9393aefa3600.php#11

**Comment by MarKco** [comment]
I'm experiencing the same issue trying to load the page:

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined index: user (View: /var/www/project/resources/views/cornford/googlmapper/javascript.blade.php) (View: /var/www/project/resources/views/cornford/googlmapper/javascript.blade.php) (View: /var/www/project/resources/views/cornford/googlmapper/javascript.blade.php)

**Comment by MarKco** [comment]
Ok, I managed to fix it: https://github.com/bradcornford/Googlmapper/issues/249
