### ISSUE TITLE
Geocode

### ISSUE THREAD

**Issue by Magnificent-Big-J** [bradcornford/Googlmapper#194]
Does the package Geocode?

**Comment by bradcornford** [comment]
Hi there,

Yes, this can be achieved by using the `location` method.

```php
Mapper::location('Sheffield');
---
object(Cornford\Googlmapper\Models\Location)[171]
  protected 'search' => string 'Sheffield' (length=9)
  protected 'address' => string 'Sheffield, UK' (length=13)
  protected 'type' => string 'locality' (length=8)
  protected 'latitude' => float 53.381129
  protected 'longitude' => float -1.470085
  protected 'placeId' => string 'ChIJFb7o-qkKeUgReLAGr_UnKD4' (length=27)
```

**Comment by Magnificent-Big-J** [comment]
Sweet,  I only have latitude and longitude, give me an example of getting address using the two without me having to type the name on Mapper::location('Sheffield');

**Comment by bradcornford** [comment]
Hi there,

You can pass the latitude and longitude to the location method too.

```php
Mapper::location('53.381129, -1.470085')
```

**Comment by Magnificent-Big-J** [comment]
Thank you very much, your package have made my dev life more easy

**Comment by Mohsing511** [comment]
how can i use this for searching a place with autocomplete

**Comment by bradcornford** [comment]
You can simply have a search box, that posts the data, then call `Mapper::location($search)` to get an Location object back. This then allows for calls to `map` or `streetview` to create a map for the location.
