### ISSUE TITLE
Error: MapperSearchException in Mapper.php line 128

### ISSUE THREAD

**Issue by jozeflambrecht** [bradcornford/Googlmapper#195]
Today I am having this error on al my pages using the location function: 

```
MapperSearchException in Mapper.php line 128:
Unable to perform location search, the error was: "file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1******6:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed".
```

Any idea what might have gone wrong? Something Google changed?

**Comment by jozeflambrecht** [comment]
Found it: it had to change the following setting:

run PHP as: FastCGI application served by Apache

and wit works again!

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply, glad you got to the bottom of this!
