### ISSUE TITLE
Not sure how to use javascript on this

### ISSUE THREAD

**Issue by joveice** [bradcornford/Googlmapper#196]
Hello, I just want when a user clicks the map a marker gets placed, now this can be sendt along with all other datas in the form. If the map is clicked again after first time the marker moves (max 1 marker)

How do you do this? I don't understand how you use javascript for this.

**Comment by bradcornford** [comment]
Hi there,

You should find some helpful information around dynamic markers here: https://github.com/bradcornford/Googlmapper/issues/175
