### ISSUE TITLE
rendering the map in @include()

### ISSUE THREAD

**Issue by wabsa** [bradcornford/Googlmapper#197]
Hi,
Map is not rendering when the view is inside @include()

eg:
View (index.blade.php)
```
<html>
@include('maincontent)
@include('map')
</html>
```
View (map.blade.php)
`{{Mapper::render()}}`

Controller
```
public function index()
{
$this->resultMap = Mapper::map(0, 0, ['zoom' => ZOOM_SIZE, 'clusters' => ['size' => 10, 'center' => true, 'zoom' => ZOOM_SIZE], 'eventDomReady' => 'alert("test");']);

return view('index)
}

Please advise, thanks
```

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply! How did you fix this issue for future reference?

**Comment by wabsa** [comment]
My mistake I forgot to add width and height to the div container. Thanks.
