### ISSUE TITLE
call the map controller using ajax

### ISSUE THREAD

**Issue by wabsa** [bradcornford/Googlmapper#198]
I want to render the map using ajax call in index.blade.php
index.blade.php
```
<div id="maphandler" style="width:100%;height:500px;"></div>

<script>
$(document).ready(function() {
        getMap();
})
function getMap(){
 $.ajax( {
             url: "{{url('/')}}/getmap/",
                type: 'GET',
                data: data,
                success: function (response) {
                   $('#maphandler').html(response);
                }
            });
}
</script>
```
on map controller: 
```
public function getmap(){
    Mapper::map(0, 0);
    return view('map')->render();
}
```

map.blade.php
`{!!Mapper::render()!!}`

So basically my goal here is to have a search button that can search specific location upon click using ajax so that it will not reload the whole page I just want to replace the current map with the new result map coming from the backend. Thanks

**Comment by bradcornford** [comment]
Hi there,

I don't think this is a supported way of loading google maps. See: https://developers.google.com/maps/documentation/javascript/tutorial?csw=1#Loading_the_Maps_API for more information.

Your also likely to run into the following error too:

`Warning: you have included the Google Maps API multiple times on this page. This may cause unexpected errors.`

**Comment by bradcornford** [comment]
The other option you have, is to load the map in a hidden state, then when a location is searched / entered, move the map using a callback.

**Comment by wabsa** [comment]
Thank you for the  info, can you give me a quick example using a callback?

**Comment by bradcornford** [comment]
See https://github.com/bradcornford/Googlmapper/issues/91 for more info.

**Comment by wabsa** [comment]
How to include markers with infowindow?

**Comment by bradcornford** [comment]
Hi there,

Information windows come with a marker attached by default:

```php
Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, 'Content');
```
