### ISSUE TITLE
Error [Array to string conversion] of using marker labels as an array.

### ISSUE THREAD

**Issue by kristina-kachan** [bradcornford/Googlmapper#199]
Hi
i have the latest version of framework. But the marker labels as an array doesn't work. How can i solve this problem?

**Comment by bradcornford** [comment]
Hi there,

Can you explain the problem / provide some sample code please.

**Comment by kristina-kachan** [comment]
Hi
in the issue #143 You wrote this :
Hi there,You can add a custom label using the following:  
       Mapper::marker(51.3359154, 3.3129791, [           
  'label' => [   
              'text' => '$300k', 
                'color' => '#4682B4',     
            'fontSize' => '30px',         
        'fontWeight' => 'bold'          
   ],            
 'labelClass' => 'labels',      
       'title' => 'Hello World!',       
  ]);
--
But 'label' as the array doesn't work. Only as a string
like this 

  Mapper::marker(51.3359154, 3.3129791, [           
  'label' => 'hi',            
       'title' => 'Hello World!',       
  ]);

**Comment by bradcornford** [comment]
Can you confirm the version of the package you are using? 

The code I have tested is:

```php
Mapper::marker(51.3359154, 3.3129791, [
            'label' => [
                'text' => '$300k',
                'color' => '#4682B4',
                'fontSize' => '30px',
                'fontWeight' => 'bold'
            ],
            'labelClass' => 'labels',
            'title' => 'Hello World!',
        ]);
```

Which outputs:
<img width="1044" alt="screen shot 2017-09-19 at 15 14 34" src="https://user-images.githubusercontent.com/2913887/30596924-70122e94-9d4d-11e7-8e68-284618e30615.png">

**Comment by kristina-kachan** [comment]
Hi again)
the version is 2.28.0

**Comment by kristina-kachan** [comment]
Hi again)
thanks for answers i found the solution
i have my own views/marker.blade.php, where forgot to change this
-	label: {!! json_encode((string) $options['label']) !!},
 +	label: {!! json_encode($options['label']) !!},

**Comment by bradcornford** [comment]
Ah yes, you would need to re-publish to assets of the package when updating. Sorry, forgot about that!
