### ISSUE TITLE
Add marker clusterer

### ISSUE THREAD

**Issue by michellaurent** [bradcornford/Googlmapper#2]
It would be nice to have the ability to use [marker clusterer](https://googlemaps.github.io/js-marker-clusterer/docs/reference.html) when having many markers.

[Some examples](https://googlemaps.github.io/js-marker-clusterer/docs/examples.html)

**Comment by bradcornford** [comment]
Yes, that would be useful for maps using many markers to increase performance. I'll take a look at integration options for this.

**Comment by bradcornford** [comment]
Okay, I have now integrated marker clusters as a configuration option. This has been pushed to the develop branch if you would like to check it out.

**Comment by michellaurent** [comment]
Hi Bradley,

It works fine. You can push to the master branch.

Thanks !

**Comment by bradcornford** [comment]
Thanks for checking this out. All merged and version in 2.1.0.
