### ISSUE TITLE
Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically, assuming $this from incompatible context

### ISSUE THREAD

**Issue by m7vm7v** [bradcornford/Googlmapper#20]
I am using Laravel 5.1 and I have eddited the composer.json and updated it. Then eddited app.php with 
Cornford\Googlmapper\MapperServiceProvider::class, and 
'Mapper'    => Cornford\Googlmapper\Facades\MapperFacade::class, .
Then runned 
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" 
and e had 'Nothing to publish for tag []'
in routes.php
Route::get('/map', 'Test@map' );
in the model Test.php
Mapper::map(53.381128999999990000, -1.470085000000040000);

And I have this error:

Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically, assuming $this from incompatible context

Any suggestion will be nice. Thank you

**Comment by m7vm7v** [comment]
If I try directly form the routes.php like
Route::get('/map', function(){
    Mapper::map(53.381128999999990000, -1.470085000000040000);
});

I have a blank page with nothing.

**Comment by bradcornford** [comment]
Hi,

Also can you confirm that you are not using the Mapper class, but rather the MapperFacade when utilising the class?

```php
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
```

Some IDE's will automatically require the class utilising a use statement at the top of the class without prompting.

**Comment by m7vm7v** [comment]
Now is working. Thank you

**Comment by kumarsunnyil** [comment]
The Solution Works
