### ISSUE TITLE
publish works on fresh 5.5 install - gives non-static method error

### ISSUE THREAD

**Issue by jhoskins98** [bradcornford/Googlmapper#200]
Getting - Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically - on a 5.5 instance that I wanted to add maps to.  

To try and isolate I even did a fresh install and got the same thing.  Documentation says 'use Mapper;' but will only run if 'use Cornford\Googlmapper\Mapper;' is put in.   

Problem #2 
Followed instructions ... but noticed that publish did not copy files on existing install but fresh install showed the files get copied.  

Did a fresh install of 5.5 and then ran install of googlmapper and got 
```
$php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper
Copied File [/vendor/cornford/googlmapper/src/config/config.php] To [/config/googlmapper.php]
Copied Directory [/vendor/cornford/googlmapper/src/views] To [/resources/views/cornford/googlmapper]
Publishing complete.
```

So I know what was not copied and fixed that.

**Comment by Lirux** [comment]
Try with this line:
`use Cornford\Googlmapper\Facades\MapperFacade as Mapper;`

**Comment by bradcornford** [comment]
Did @Lirux comment fix your issue?

**Comment by sarperkaya** [comment]
Same issue.

```
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
//
Mapper::map(53.381128999999990000, -1.470085000000040000);
```

Gives:
Class mapper does not exist

```
use Cornford\Googlmapper\Mapper;
//
Mapper::map(53.381128999999990000, -1.470085000000040000);
```
Gives:
Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically

My config/app.php
```
// providers
Cornford\Googlmapper\MapperServiceProvider::class,
// aliases
'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class,
```

**Comment by jhoskins98** [comment]
Note that 5.5 requires PHP 7 so it might be a PHP 7 issue at its heart.  Also, you can close this whenever you want.  I am no longer tracking this issue.

**Comment by bradcornford** [comment]
I've just tested this with a clean install of Laravel 5.5, using the installation instructions, with the following code and all seems to be working: 

Laravel-5.5/composer.json
```php
...
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "cornford/googlmapper": "2.*"
    },
...
```

Laravel-5.5/config/app.php:
```php
...
    Cornford\Googlmapper\MapperServiceProvider::class,
...
    'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class,
...
```

Laravel-5.5/routes/web.php:
```php
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

Route::get('/', function () {
    Mapper::map(53.381128999999990000, -1.470085000000040000);

    return view('welcome');
});

```

Laravel-5.5/resources/views/welcome.blade.php:
```html
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style></style>
    </head>
    <body>
        <div style="height: 500px; width: 500px;">
            {!! Mapper::render() !!}
        </div>
    </body>
</html>

```

<img width="494" alt="screen shot 2017-10-24 at 14 28 08" src="https://user-images.githubusercontent.com/2913887/31945623-9bde8f28-b8c7-11e7-84e5-2ce5231e2c87.png">

Can you try running `composer update` and `composer dump-autoload -o`?

**Comment by sarperkaya** [comment]
It updated to v2.29.0. And then it worked.

Thanks.
