### ISSUE TITLE
Refresh map after getting geolocation

### ISSUE THREAD

**Issue by t-prod** [bradcornford/Googlmapper#201]
Hi,

When page loads, geolocation must be approved by user (accept or decline). When he clicks Accept I made a call in Ajax with params in get with longitude and latitude. When he declines the same page is showeb without geolocation (same view with map).

In my Controller I use this : 

`
if ($request->ajax() && $request->lat && $request->long) {
      $networks = Network::all();

      Mapper::map($request->lat, $request->long, ['zoom' => 10, 'markers' => ['title' => trans('dashboard.networks.youarehere'), 'animation' => 'DROP']]);

      foreach ($networks as $network) {
        Mapper::informationWindow(
            $network->latitude,
            $network->longitude,
            $network->title
           /* [
             'open' => true, 'maxWidth'=> 300,
             'markers' => ['title' => $network->title.' chla']
            ]*/
        );
      }
      return view('dashboard.networks.networks', ['user' => Auth::user(), 'networks' => $networks]);
}
`
How can I refresh also the map ? How can I do ?
I use the view with but of course the map is not refreshed even with my ajax call

`<div class="map" id="map" style="width: 100%; height: 400px;">
		{!! Mapper::render() !!}
	</div>`

**Comment by Messhias** [comment]
I have the same problem, I'm trying make reload with javascript and jquery, but it would better if we can do it with the library

**Comment by t-prod** [comment]
I think I give up this library. If you find a way tell me ;)

**Comment by Messhias** [comment]
hi, I find a way to do it, I just call the initialize_{{id}} method again after the ajax call

**Comment by t-prod** [comment]
Hi Messhias,

Can you provide an example to do so ?

Thanks

**Comment by Messhias** [comment]
`<script type="text/javascript">

var maps = [];
var propierties;
var nearBottom = 9000;
var loading = false;
var c = 0;
var url = document.URL;
url = url.split("/");
url = url[3];
url = url.split("?");
url = url[0];
var markers = [];
var infowindows = [];
var shapes = [];
$(document).ready(function() {
	function initialize_{!! $id !!}() {
		var bounds = new google.maps.LatLngBounds();
		var infowindow = new google.maps.InfoWindow();
		var position = new google.maps.LatLng({!! $options['latitude'] !!}, {!! $options['longitude'] !!});

		var mapOptions_{!! $id !!} = {
			@if ($options['center'])
				center: position,
			@endif
			mapTypeId: google.maps.MapTypeId.{!! $options['type'] !!},
			disableDefaultUI: @if (!$options['ui']) true @else false @endif,
			scrollwheel: @if ($options['scrollWheelZoom']) true @else false @endif,
            zoomControl: @if ($options['zoomControl']) true @else false @endif,
            mapTypeControl: @if ($options['mapTypeControl']) true @else false @endif,
            scaleControl: @if ($options['scaleControl']) true @else false @endif,
            streetViewControl: @if ($options['streetViewControl']) true @else false @endif,
            rotateControl: @if ($options['rotateControl']) true @else false @endif,
            fullscreenControl: @if ($options['fullscreenControl']) true @else false @endif
		};

		var map_{!! $id !!} = new google.maps.Map(document.getElementById('map-canvas-{!! $id !!}'), mapOptions_{!! $id !!});
		map_{!! $id !!}.setTilt({!! $options['tilt'] !!});


		@foreach ($options['markers'] as $key => $marker)
			{!! $marker->render($key, $view) !!}
		@endforeach

		@foreach ($options['shapes'] as $key => $shape)
			{!! $shape->render($key, $view) !!}
		@endforeach

		@if ($options['overlay'] == 'BIKE')
			var bikeLayer = new google.maps.BicyclingLayer();
			bikeLayer.setMap(map_{!! $id !!});
		@endif

		@if ($options['overlay'] == 'TRANSIT')
			var transitLayer = new google.maps.TransitLayer();
			transitLayer.setMap(map_{!! $id !!});
		@endif

		@if ($options['overlay'] == 'TRAFFIC')
			var trafficLayer = new google.maps.TrafficLayer();
			trafficLayer.setMap(map_{!! $id !!});
		@endif

		var idleListener = google.maps.event.addListenerOnce(map_{!! $id !!}, "idle", function () {
			map_{!! $id !!}.setZoom({!! $options['zoom'] !!});

			@if (!$options['center'])
				map_{!! $id !!}.fitBounds(bounds);
			@endif

			@if ($options['locate'])
				if (typeof navigator !== 'undefined' && navigator.geolocation) {
					navigator.geolocation.getCurrentPosition(function (position) {
						map_{!! $id !!}.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
					});
				}
			@endif
		});

        var map = map_{!! $id !!};

		@if (isset($options['eventBeforeLoad']))
			{!! $options['eventBeforeLoad'] !!}
		@endif

		@if (isset($options['eventAfterLoad']))
			google.maps.event.addListenerOnce(map_{!! $id !!}, "tilesloaded", function() {
				{!! $options['eventAfterLoad'] !!}
			});
		@endif

		@if ($options['cluster'])
			var markerClusterOptions = {
				imagePath: '{!! $options['clusters']['icon'] !!}',
				gridSize: {!! $options['clusters']['grid'] !!},
				maxZoom: @if ($options['clusters']['zoom'] === null) null @else {!! $options['clusters']['zoom'] !!} @endif,
				averageCenter: @if ($options['clusters']['center'] === true) true @else false @endif,
				minimumClusterSize: {!! $options['clusters']['size'] !!}
			};
			var markerCluster = new MarkerClusterer(map_{!! $id !!}, markers, markerClusterOptions);
		@endif

		maps.push({
			key: {!! $id !!},
			markers: markers,
			infowindows: infowindows,
			map: map_{!! $id !!},
			shapes: shapes
		});
	}

    @if (!$options['async'])

	    google.maps.event.addDomListener(window, 'load', initialize_{!! $id !!});

    @endif

    if (url == "comprar") {
        $(".search-results-container").bind('scroll', function() {
            if(!loading && $(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight - nearBottom){

                loading = true;

                $(this).toggleClass("loaded");

                $.ajax({
                    url: 'my-url',
                    type: "GET",
                    data: { 
                        //here your parameters data
                    },
                    beforeSend:function(){
                    },
                    error:function(error){
                        console.log(error);
                    },
                    success:function(success){
                                             
                        for( i = 0; i < success.markers.length; i++) {
                            var myLatlng = new google.maps.LatLng(success.markers[i].lat,success.markers[i].lng);
						    var marker = new google.maps.Marker({
						        position: myLatlng,
						        map: maps,
						        title: 'Hello World!'
						    });

						    markers.push(marker);

                        }
						initialize_0();
                    },
                    complete:function(){
                        $(".search-results-container").append(propierties);

                        $(this).toggleClass("loaded");

                        loading = false;
                    }
                });
                
            }
        });
    }
</script>`

**Comment by bradcornford** [comment]
Hi there,

I've pushed an update to the library that should do what you are seeking. The map renders at 0,0 until the users current location is found, after which the map and maker move to the current location. It should now be as simple as doing the following:

```php
Mapper::map(0, 0, ['marker' => true, 'locate' => true, 'zoom' => 10, 'markers' => ['title' => trans('dashboard.networks.youarehere'), 'animation' => 'DROP']);
```

**Comment by t-prod** [comment]
Hi, thanks for this update. it put the map in the sea. I have deleted all javascript to get geolocation and put only your script above.

Have I missed something ?

**Comment by bradcornford** [comment]
Did you run `composer update`? Also have you allowed the page to take your current location?

**Comment by t-prod** [comment]
Yes of course. I try with different browsers (even Edge ;)). This is my code :

`
Mapper::map(0, 0, ['marker' => true, 'locate' => true, 'zoom' => 10, 'markers' => ['title' => trans('dashboard.networks.youarehere'), 'animation' => 'DROP']]);
`

And in the view 

`
<div class="map" id="map" style="width: 100%; height: 400px;">
		{!! Mapper::render() !!}
	</div>
`

**Comment by bradcornford** [comment]
Any chance you can drop the HTML source from the browser here, its working for me as expected. See (Notice the location icon in the browsers URL bar):

<img width="1127" alt="screen shot 2017-10-24 at 14 33 31" src="https://user-images.githubusercontent.com/2913887/31945888-56ff374e-b8c8-11e7-9fe4-8babcb8ef30c.png">

**Comment by t-prod** [comment]
You're right i've deactivated the geolocation, that's why I has this problem.
I noticed that I config a image marker which displays well but when I authorize the geolocation it disappears and I've not the marker anymore.

Could you reproduce this problem  ?
Here is the link for testing : http://app.sesami.fr/images/marker-black.svg

Thanks again

**Comment by bradcornford** [comment]
No, thats not something i can reproduce. I used the following:

```php
Mapper::map(0, 0, ['marker' => true, 'locate' => true, 'zoom' => 10, 'markers' => ['title' => 'You are here', 'animation' => 'DROP', 'icon' => 'http://app.sesami.fr/images/marker-black.svg']]);
```

And get:

<img width="456" alt="screen shot 2017-10-24 at 15 02 45" src="https://user-images.githubusercontent.com/2913887/31947573-85e2baf0-b8cc-11e7-9265-9e9c0becb1e0.png">

**Comment by Messhias** [comment]
In my case, I did a new laravel project instalation and reinstall the
library, i think it could be something in your library could be in conflict
with another libs and plugins that we using, maybe this is a  possibility,
i am trying to simulate the same error again to debug carefuly what happens


*Atenciosamente,*

*Fabio William Conceição*

*Contato*: *messhias@gmail.com <messhias@gmail.com>*

2017-10-24 12:03 GMT-02:00 Bradley Cornford <notifications@github.com>:

**Comment by danilosantosdev** [comment]
I'm trying to refresh the map after change the icons. I'm doing like above:

```
maps[0].markers.forEach((marker) => {							
    var iconColor = this._getIndicadorByUE(marker.title)[0].indicadores[ind-1].icon;
    var icon = 'unidadeensino-' + iconColor + '.png';
    marker.icon = {!! json_encode(url(asset('imagens/_icone_'))) !!}.replace('_icone_', icon);
});
initialize_0();
```
But doesn't work. I see that the map is refreshedm but the icons don't change.

**Comment by Messhias** [comment]
In your ajax call just call your initialize again.

Em 10/11/2017 16:29, "Danilo Santos" <notifications@github.com> escreveu:
