### ISSUE TITLE
Load map using js

### ISSUE THREAD

**Issue by shaliniseb** [bradcornford/Googlmapper#202]
Hello, I want implement map page using js.

I have a page with some search result and a link for loading map, when i click on map link i should load map with searched locations as marked in the same view using the js.
how to implement that in larvel .

**Comment by bradcornford** [comment]
Hi, 

This package is for Laravel and as such you would need to make a request to a controller containing the map initialisation, and in turn receive a response with a rendered map.

```php

    public function index()
    {
        Mapper::map(0, 0, ['marker' => true, 'locate' => true, 'async' => true]);

        print Mapper::render();
    }
``
