### ISSUE TITLE
Help with infowindow with same Lat and Long

### ISSUE THREAD

**Issue by georgecpacheco** [bradcornford/Googlmapper#208]
Hi!
I have many locations with the same lat and long and then Google puts them all together, but I want an infowindow with the titles of the marks separated by a line.
And let them be loaded along with the map, not clicking.
Thank you for your help. [proposed Label] help wanted

**Comment by bradcornford** [comment]
Hi there, 

If you mean you want to turn off clustering this can be achieved as follows: 

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 10, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 'maker' => false, 'cluster' => false]);
```

For multiple markers in the same location, would something like this suffice?

```php
$locations = '';
$items = [
    [
        'title' => 'Location 1',
        'latitude' => 1,
        'longitude' => 1
    ] ,
    [
        'title' => 'Location 2',
        'latitude' => 1,
        'longitude' => 1
    ]
];

foreach ($items as $key => $item) {
   $locations .= $item['title'] . ($key < count($items) - 1 ? '<hr>' : '');
}

Mapper::informationWindow(53.381128999999990000, -1.470085000000040000, $locations, ['open' => true, 'markers' => ['title' => 'Title']]);
```

**Comment by georgecpacheco** [comment]
Thank you!!
You show me the way, and works!!
