### ISSUE TITLE
Compatibility wit L5.4

### ISSUE THREAD

**Issue by issacMontes28** [bradcornford/Googlmapper#209]
Hi, one question, is your package compatible with laravel 5.4? because I have followed the instructions and I get this error "Class 'Mapper' not found". Thanks a lot

**Comment by tijdmachine** [comment]
The package should properly work with L5.4.

Make sure you have added the package to the alias/providers array within `config/app.php`

```
// providers
Cornford\Googlmapper\MapperServiceProvider::class,
```

```
// aliases
'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class,
```

And `use` the package within your controller

`use Cornford\Googlmapper\Facades\MapperFacade as Mapper;`

**Comment by bradcornford** [comment]
Hi there,

Yes, I can confirm the package is compatible with Laravel 5.4. As @tijdmachine has mentioned ensure you have set the configuration for providers and aliases.

**Comment by jomayan** [comment]
I can also confirm that the package is fully compatible with Laravel 5.4 .
I'm currently using it in my web App.

![screen shot 2017-11-12 at 1 41 54 am](https://user-images.githubusercontent.com/25026077/32697672-b3624bf8-c74a-11e7-9ff2-7e203a311d50.png)
