### ISSUE TITLE
MarkerClusterer

### ISSUE THREAD

**Issue by m7vm7v** [bradcornford/Googlmapper#21]
Is there any chanse that you can add MarkerClusterer. Or any information where do I need to impliment them. Thanks mate.
https://developers.google.com/maps/articles/toomanymarkers

**Comment by bradcornford** [comment]
Hi there,

Marker clusters are enabled by default, check your config.php for this section:

```php
    /*
    |--------------------------------------------------------------------------
    | Map Marker Cluster
    |--------------------------------------------------------------------------
    |
    | Enable default Googlmapper map marker cluster.
    |
    */
    'cluster' => true,
```

It uses https://github.com/googlemaps/js-marker-clusterer

**Comment by bradcornford** [comment]
Did you have any luck with this?

**Comment by m7vm7v** [comment]
Yep. You can close the issue now. Everything works fine. The only think is that with huge data is making a problems but it is a normal. I need to load 30 000 points at the same time and for that it took me a 30 seconds. If there is a better way to do that will be perfect but....

**Comment by bradcornford** [comment]
I think with that amount of data, you'll see slowdowns, as the amount to render to the browser is large, along with JS having to process those items into the map. I would suggest you look at loading a smaller set at load, and then loading sets via ajax when needed.
