### ISSUE TITLE
map polyline not follow street ??

### ISSUE THREAD

**Issue by Bougueddima** [bradcornford/Googlmapper#210]
![capture d ecran 2017-11-09 a 9 20 38 am](https://user-images.githubusercontent.com/33159264/32595241-66c5a4a6-c52f-11e7-8bca-6c75ce2075d2.png)

how can i draw a PolyLine who follow street.

thanks

...
for($i=0; $i< $j; $i++ ){
             Mapper::polyline([['latitude' => $tab[$i], 'longitude' => $tab[$i+1]],
                ['latitude' => $tab[$i+2], 'longitude' => $tab[$i+3]]]);
        }        
        return view('position');

**Comment by bradcornford** [comment]
Hi there,

This isn't achieved naturally with polylines, you would have to get an array of road latitude and longitudes, and for each add them to the map yourself. 

Other than that you could look into: https://developers.google.com/maps/documentation/roads/snap
