### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by jomayan** [bradcornford/Googlmapper#211]
Hi!

Is there any way that we can style the custom image icon ?
It's currently displaying the custom image icon as square, is it possible that we can make it into circular or add style='border-radius: 50%;' to make it circular.

Thanks.

**Comment by tijdmachine** [comment]
You can pass a custom icon image (such as SVG) which you can adjust to your personal needs.

```
Mapper::informationWindow('lat', 'lat', 'title', [
    'icon' => '/images/markers/default.svg';
]);
```

**Comment by jomayan** [comment]
Thanks @tijdmachine, I have already done it.. What I'm asking is, can we possible add CSS style to the icon. Example, i want to add a CSS style of `border-radius:50%` to make the icon circular and not square.

Like the one on the attached photo.. I want to make them circular..

![screen shot 2017-11-10 at 8 18 43 pm](https://user-images.githubusercontent.com/25026077/32686127-6b9fca44-c654-11e7-92a2-27d8109b5e5c.png)

**Comment by bradcornford** [comment]
Hi there,

I'm not sure that this is possible to be honest. I cant seem to find anything in Google's documentation.

**Comment by jomayan** [comment]
@bradcornford GooglMapper has been a huge help in my web app already. 
If I can find a way, I will post here.

Thank you so much for GooglMapper.

**Comment by tijdmachine** [comment]
https://humaan.com/blog/custom-html-markers-google-maps/

This might be useful. Looked this up quickly, but if I have some time I'll read myself a bit more into it

**Comment by jomayan** [comment]
Thanks @tijdmachine. I'll check it out :)

**Comment by bradcornford** [comment]
@jomayan I'm glad its helping you out!

Yeah, i was trying to find a native way to achieve this @tijdmachine. 

I've put together something which should suffice:

```php
Mapper::map(0, 0, ['marker' => false, 'locate' => true, 'eventAfterLoad' => 'loadMarkerOverlay(map);']);
```

```html
<style type="text/css">

    #markerLayer img {
        border-radius: 20px !important;
    }

</style>
```

```html
<script type="text/javascript">

    function loadMarkerOverlay(map) {
        var overlay = new google.maps.OverlayView();

        overlay.draw = function () {
            this.getPanes().markerLayer.id='markerLayer';
        };

        overlay.setMap(map);
    }
    
</script>
```

**Comment by jomayan** [comment]
Thanks @bradcornford, greatly appreciate it! :)
