### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by jomayan** [bradcornford/Googlmapper#213]
I'm kinda new here and would like to know if someone already achieved geofencing.
Lets say for example:
I want to put a marker for those users 25 miles radius from my location.

P.s. : I have all the Longitude and Latitude of all my users in DB.

**Comment by bradcornford** [comment]
I don't think this is something that has been done before with the package. But you could create a circle of that size, and have an after load callback in which you check each maker is within the bounds of the circle, and remove them if they are not (Setting there map to null would work).

**Comment by jomayan** [comment]
I'm not sure how to implement this.
What I'm doing now is just geofence it by state since I have the state data of all my user.
