### ISSUE TITLE
Show infowindow on mouseover

### ISSUE THREAD

**Issue by ootim** [bradcornford/Googlmapper#214]
Hi, Please how can I use this library to show the infowindow on mouseover and not on mouseclick?

Also, how can I include links in the content of the infowindow.

Thanks.

**Comment by tijdmachine** [comment]
You can render multiple information windows, simply by calling the `informationWindow` method on the Mapper facade. (param 1 = latitude, param 2 = longitude, param 3 = name, param 4 = options)

Example:
```php
$hotspots->each(function (Hotspot $hotspot) {
            Mapper::informationWindow(hotspot->latitude', $hotspot->longitude, 'any_name, [
                'eventMouseOver' => 'infowindow.setContent("'.$hotspot->data.'"); infowindow.open(map, this);',
                'eventMouseOut'  => 'infowindow.close()'
            ]);
        });
```

**Comment by ootim** [comment]
That worked perfectly! Thanks a lot!
