### ISSUE TITLE
How to change content of a "informationWindow" in my JS

### ISSUE THREAD

**Issue by danilosantosdev** [bradcornford/Googlmapper#215]
Hi guys, i need to change the content of a "informationWindow" after some event, a change in a html select for example.

initially i have only the title of a marker, after change the html select, i need something like the attachment, add the "resultado" string and the "detalhe" string.

How can i do that?
Thanks!

![image](https://user-images.githubusercontent.com/2335679/32804349-86adcc00-c965-11e7-9fa1-d20b09d6ea7e.png)

**Comment by bradcornford** [comment]
Hi there,

This is very possible, and fairly simple too. This can be achieved as follows:

```js
console.log(maps[0].infowindows);
maps[0].infowindows[0].setContent('hello');
```
