### ISSUE TITLE
Cannot run in view with vue

### ISSUE THREAD

**Issue by k-kentang** [bradcornford/Googlmapper#216]
Hai, maps do not appear when open my page, but if I inspect the element map it appears but I get an error in vue js.
How to fix that?
I've tried several ways but it did not work.
Thanks

**Comment by bradcornford** [comment]
Hi there,

What error are you receiving? What does you view look like?

**Comment by k-kentang** [comment]
Thanks for your response, i get an error like this
![screenshot from 2017-11-20 16 54 46](https://user-images.githubusercontent.com/21195587/33012764-7a45cd38-ce14-11e7-82d5-451e24416919.png)

when i inspect elements and refresh this page, maps is showing but error in vue.js
![screenshot from 2017-11-20 17 03 08](https://user-images.githubusercontent.com/21195587/33012922-de3f8554-ce14-11e7-8383-ff7dae698af5.png)

**Comment by bradcornford** [comment]
Have you got multiple maps in your template, or are you calling the render method multiple times?

**Comment by k-kentang** [comment]
no, I just called the method render once like this
<div style="width: 1070px; height: 500px;" id="map-canvas">
	@if($maps != '')
	       <h5>{{$maps}}</h5>`
	@else
               <?php Mapper::map($model['latitude'], $model['longitude'], ['zoom' => 16]); ?>
		{!! Mapper::render () !!}
	@endif
</div>
