### ISSUE TITLE
Mouseover on external link outside map to show infoWindow base on lat/long render from database

### ISSUE THREAD

**Issue by vanndy** [bradcornford/Googlmapper#220]
Hello,

With google mapper, currently, it can render multi marker on a map. I'm looking the way to add event mouseover on external link outside map view, and display infoWindow on Maker inside the map. Can you show me?

Thanks.

**Comment by bradcornford** [comment]
Hi, 

Yes this should be possible. You could use something like this:

```html
<a href="#" onclick="google.maps.event.trigger(maps[0].markers[1], 'click');">Click here</a>
```
