### ISSUE TITLE
Cannot drag marker

### ISSUE THREAD

**Issue by dianavillegas** [bradcornford/Googlmapper#222]
Hi
For some reason, I cannot drag my marker anymore. It was working a while ago

MapController
`	Mapper::map(52.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventDragEnd' => 'console.log(event.latLng.lat()); console.log(event.latLng.lng());']);
   		return view('map');`

Does the error Google Maps Api Warning: SignedInNotSupported affects this?

**Comment by bradcornford** [comment]
Hi,

Did you get to the bottom of this issue? 

No the warning for 'SignedInNotSupported' wouldn't affect this.
