### ISSUE TITLE
Click and Double Click

### ISSUE THREAD

**Issue by jomayan** [bradcornford/Googlmapper#224]
for single click... it's eventClick,  what is for double click?
i tried eventdblClick but it does't work.

I want to run the same JS function for click and double click events...

Please help.. Thanks,

**Comment by bradcornford** [comment]
Hi there,

The event wasn't implemented, but has been in current versions v1.24.0/v2.30.0.

The event is called `eventDblClick`

**Comment by jomayan** [comment]
Thanks @bradcornford .. Will try it out.

**Comment by jomayan** [comment]
it works. Thanks :)
