### ISSUE TITLE
Postal Code

### ISSUE THREAD

**Issue by poxxac** [bradcornford/Googlmapper#225]
Hi, I'm using a Mapper::location to get the location object but I need the short version of the address formatted and the postal code as attributes to be saved in the database, how can I do it?

Thanks so much for Googlmapper, it's just awesome!

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply! Glad you like the package, can you explain what you mean?

The location object return from the location method itself has both the address, and latitude and longitude and more. These can all be accessed via appropriate get methods, i.e. `->getAddress()`
```php
dd(Mapper::location('s1 1aa'));
```
```php
object(Cornford\Googlmapper\Models\Location)[184]
  protected 'search' => string 's1 1aa' (length=6)
  protected 'address' => string 'Sheffield S1 1AA, UK' (length=20)
  protected 'type' => string 'postal_code' (length=11)
  protected 'latitude' => float 53.3815505
  protected 'longitude' => float -1.4635271
  protected 'placeId' => string 'ChIJWY7PqoKCeUgRdB8iQAEX5U0' (length=27)
```

**Comment by poxxac** [comment]
I mean, I can get lat and lng with: 

```
$location = Mapper::location($request->address . ' ' . $request->session()->get('citySelected')->name);
$post->address = $location->address;
$post->lat = $location->latitude;
$post->lng = $location->longitude;
```

But the postal code, there is no getter for it....

**Comment by bradcornford** [comment]
Hi there,

This isn't present within the response from Google Maps location service i'm afraid.

**Comment by poxxac** [comment]
I can see it here: https://developers.google.com/maps/documentation/geocoding/start

**Comment by bradcornford** [comment]
I mean its not always within the response, so it's not reliable.

**Comment by bradcornford** [comment]
I've updated the latest current version v2.31.0 to add Postal Code to the location object.

```
$location = Mapper::location($request->address . ' ' . $request->session()->get('citySelected')->name);
$post->postalCode = $location->getPostalCode();
```

**Comment by poxxac** [comment]
After updating:

$location      = Mapper::location($request->address . ' ' . $request->session()->get('citySelected')->name);
		dd($location);

Im getting: Cannot use object of type stdClass as array

        foreach ($resultObject->results[0]->address_components as $addressComponent) {
            if ($addressComponent->types[0] == 'postal_code') {
IN THIS LINE->                $postalCode = $addressComponent['long_name'];
            }
        }

**Comment by Lirux** [comment]
Look at my reply at #234 .

**Comment by bradcornford** [comment]
Hi,

Sorry about this, this issue has now been resolved. See: https://github.com/bradcornford/Googlmapper/issues/234
