### ISSUE TITLE
Get map object

### ISSUE THREAD

**Issue by Anismumtaz126** [bradcornford/Googlmapper#228]
Is there any possibility I can get map  object and process that object onclick event processing means change zoom level or use map.pan etc

**Comment by bradcornford** [comment]
Hi there,

Yes, the map itself is accessible, you could create an on load event to handle creating the listeners, something like this:

```php
Mapper::map(0, 0, ['eventAfterLoad' => 'attachMapListeners(map);']);
```

```html
    <script>

        function attachMapListeners()
        {
            map.addListener('center_changed', function() {
                console.log('center_changed');
            });

            map.addListener('zoom_changed', function() {
                console.log('zoom_changed');
            });
        }

    </script>
```

See https://developers.google.com/maps/documentation/javascript/events for more event information.
