### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by connectjames** [bradcornford/Googlmapper#23]
Hi, 

I checked the issue 18 but nothing to do nothing is rendered and no error message. I am just testing it on my web app in the user controller and show view. Can you spot the problem?

**Comment by bradcornford** [comment]
Hi,

I checked over your work, and couldn't spot anything wrong. Glad you figured it out! Out of interest, what was the issue?

**Comment by connectjames** [comment]
Hi,

It was me being stupid, forgot to put the map in a div to make visible...

Thanks for the extension, reallll good.

**Comment by connectjames** [comment]
Actually, is it an easy add or not to add GEOCODING as it is quite a good feature to have?

Thanks

**Comment by bradcornford** [comment]
I've looked into this, and its on a feature branch. Check it out here:
https://github.com/bradcornford/Googlmapper/issues/12

**Comment by connectjames** [comment]
Thanks I added in my controller the following to get the latitude:

Mapper::location("Bawtry")->getLongitude;

But I think I need to add something to Googlmapper before as it throw an error:

Call to undefined method Cornford\Googlmapper\Mapper::location()

Thanks again for your help

**Comment by bradcornford** [comment]
No worries. If you let me know how your getting on with it, i can get it merged to a version soon.

**Comment by connectjames** [comment]
Cool, if you can add in it the same thing than location but with directions, so for example if a user with location x says I want all the service available around me, ei: 10 miles, it can be done by looping through all the services to check how far they are and display them or not on the map and under the map.

**Comment by erwinjnefer** [comment]
hi @bradcornford  ... i have problem when i publish 
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"

i got this error : 
PHP Fatal error:  Call to undefined method Cornford\Googlmapper\MapperServiceProvider::mergeConfigFrom() in /home/jneferboy/web/pln/vendor/cornford/googlmapper/src/Cornford/Googlmapper/MapperServiceProvider.php on line 37
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Cornford\\Googlmapper\\MapperServiceProvider::mergeConfigFrom()","file":"\/home\/jneferboy\/web\/pln\/vendor\/cornford\/googlmapper\/src\/Cornford\/Googlmapper\/MapperServiceProvider.php","line":37}}

**Comment by connectjames** [comment]
Did you try to simply put:

php artisan vendor:publish

**Comment by erwinjnefer** [comment]
@connectjames : no.. i just follow the tutorial,,, i'll try your suggestion now.. thank's .. :)

**Comment by bradcornford** [comment]
Hi @erwinjnefer what version of Laravel are you using?

**Comment by erwinjnefer** [comment]
Hi @bradcornford i'm using Laravel 4.2,,,

**Comment by bradcornford** [comment]
@erwinjnefer You will need to use the setup steps in version 1.1.3, as version 2 is for Laravel 5.

See: https://github.com/bradcornford/Googlmapper/tree/v1.1.3

**Comment by bradcornford** [comment]
@erwinjnefer Did this fix the issue you were facing?
