### ISSUE TITLE
Script loads and fires initialize_method too soon

### ISSUE THREAD

**Issue by jsiebach** [bradcornford/Googlmapper#232]
I have a page with up to 6 maps on it.  Calling `Map::render()` on the first one prints out the javascript for Google Maps, and before the rest of the maps have loaded the callback function runs.  This can cause some maps to not be initialized.

I am not sure exactly that this was the issue, but I finally solved all my woes by running it again manually:

```
$(function(){
    initialize_method();
});
```

Is there another way I should be doing this? thanks

**Comment by bradcornford** [comment]
Hi there,

You could utilise the async options within your maps to ensure they load correctly. For example:

```php
Mapper::map(40, -100, ['zoom' => 4, 'marker' => false, 'async' => true]);

```
