### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by TurtoiVlad** [bradcornford/Googlmapper#234]
Updated composer and this package now:

<img width="410" alt="screen shot 2018-02-05 at 15 02 00" src="https://user-images.githubusercontent.com/7279482/35805709-95c8837c-0a85-11e8-80e6-48c3f4791aa8.png">

Using with Facade. Laravel 5.4.

**Comment by bradcornford** [comment]
Hi there,

I've re-pushed the current version with a fix for this issue.

**Comment by jozeflambrecht** [comment]
Just ran composer update and same problem here with version 2.31.0..

**Comment by Lirux** [comment]
As a quick fix change at line 178 in the Mapper.php file:

From
`$postalCode = $addressComponent['long_name'];`

To
`$postalCode = $addressComponent->long_name;`

**Comment by bradcornford** [comment]
Hi,

This issue has now been resolved in current version v2.31.1/v1.25.1.
