### ISSUE TITLE
jquery and JS error 

### ISSUE THREAD

**Issue by pooransingh** [bradcornford/Googlmapper#237]
Laravel : 5.3 

Google Maps API warning: SignedInNotSupported https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported

after edit resources/views/cornford/googlmapper/javascript.blade.php  like this : 
<pre>
@if (!$view->shared('javascript', false))

    @if ($view->share('javascript', true)) @endif

    @if ($options['async'])

        <script async defer type="text/javascript" src="//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&signed_in={!! $options['user'] ? 'true' : 'false' !!}&libraries=places&callback=initialize_method"></script>

    @else

        <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&signed_in={!! $options['user'] ? 'true' : 'false' !!}&libraries=places"></script>

    @endif

    @if ($options['cluster'])

        <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script>

    @endif

    @if ($options['async'])

        <script type="text/javascript">

            var initialize_items = [];

            function initialize_method() {
                initialize_items.forEach(function(item) {
                    item.method();
                });
            }

        </script>

    @endif

@endif
</pre>

it still gives Google Maps API warning: SignedInNotSupported https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported  and 'google' is undefined variable.

**Comment by bradcornford** [comment]
Hi, 

The warning `Google Maps API warning: SignedInNotSupported ` isn't an issue. It will however be rectified in future version, but it doesn't cause any issues.

**Comment by bradcornford** [comment]
I've now removed Signed in Support from the package in current version v2.31.4/v1.25.
