### ISSUE TITLE
How to render circle on map after an AJAX Request? 

### ISSUE THREAD

**Issue by IonutRusen** [bradcornford/Googlmapper#238]
I'm refreshing map after ajax request, and i can't set circle on refreshed map! 
this is what i'm doing, can you please help me ? 

thank you !

$.get("/usl/"+$(this).val(), function(data) {

                maps[0].map.setCenter({lat: data.latitude, lng: data.longitude});
                maps[0].markers[0].setPosition(new google.maps.LatLng(data.latitude, data.longitude));
               

            })

**Comment by bradcornford** [comment]
Hi there,

Did you find a solution to this issue?
