### ISSUE TITLE
informationWindow content parameter 

### ISSUE THREAD

**Issue by starba3** [bradcornford/Googlmapper#239]
is there a way to make the content parameter in informationWindow accepts and prints array elemets, each in separate line?

**Comment by bradcornford** [comment]
Hi there,

This isn't something native to information windows, however you can do this within you calling code itself. For example:

``
$items = [1, 2, 3, 4];

Mapper::informationWindow(0,0, '<ul><li>' . implode( '</li><li>', $items) . '</li></ul>');

``
