### ISSUE TITLE
Polygon data out of the database

### ISSUE THREAD

**Issue by m7vm7v** [bradcornford/Googlmapper#24]
I am trying to make a polygon from the database.
I the DB i have a columb called polygon with (for example)

        ['longitude' => 1, 'latitude' => 6 ],['longitude' => 2, 'latitude' => 6 ]

in the controller:

        $points = DB::table('polygons_data')->select('polygon')->get();
        $map = Mapper::map(5, -2);
        $map->polygon([$points[0]->polygon]);        
        return view('test');

but when I am trying this in the output I am having something like 
$map->polygon(['['longitude' => 1, 'latitude' => 6 ],['longitude' => 2, 'latitude' => 6 ]']);    

So the problem is these ' ' but they are comming automaticly, 
Any ideas how to make it working

**Comment by bradcornford** [comment]
The problem your having is that your passing a string, when an array is expected. Your best best would be to store an encoded string, and decode when you want to use it.

Consider the following:

$data = [['longitude' => 1, 'latitude => 1], ['longitude' => 2, 'latitude' => 2]];

So you would store the output of this in the db:

$polygon = json_encode($data);

The on retrieval you would decode this, passing it to Mappers polygon function:

$map->polygon(json_decode($polygon));

**Comment by m7vm7v** [comment]
I have got this now
Argument 1 passed to Cornford\Googlmapper\Mapper::polygon() must be of the type array, string given, called in C:\xampp\htdocs\Geo5.1\app\Http\Controllers\Test.php on line 150 and defined

150    $map->polygon(json_decode($polygon));

**Comment by m7vm7v** [comment]
Considering to this method I thing now the output looks like
$map->polygon('[['longitude' => 1, 'latitude' => 6 ],['longitude' => 2, 'latitude' => 6 ]]');

So the ' ' have moved a bit atleast ...

**Comment by bradcornford** [comment]
Store the decode into a variable, then pass the variable to the polygon method.

**Comment by m7vm7v** [comment]
I have already tryed but without succes.

**Comment by bradcornford** [comment]
Okay, have your tried passing in the data variable as well?

**Comment by m7vm7v** [comment]
Give me example with the code what do you exacly mean

**Comment by bradcornford** [comment]
Okay, so i believe json_encode / decode are causing the array to be type casted to an object, to avoid this, try using serialization.

Firstly i would insert a row into the db as follows:

```php

$data = [['longitude' => 1, 'latitude' => 1], ['longitude' => 2, 'latitude' => 2]];
DB::insert('insert into polygons_data(polygon) values (?)', [serialize($data)]);

```
Then upon retrieval i would do as follows:

```php

$points = DB::table('polygons_data')->select('polygon')->get();
$map = Mapper::map(1, 1);
$polygon = unserialize($points);
$map->polygon($polygon);     
   
return view('test');

```

**Comment by m7vm7v** [comment]
Now works mate. Tank you
