### ISSUE TITLE
how to save polygon array to database

### ISSUE THREAD

**Issue by rendyif** [bradcornford/Googlmapper#240]
i'm new to this stuff, could you give me example to make and store polygon, to database, i can use it to save point marker, 
controller
Mapper::map(-6.9809279,107.486755, [
        'draggable' => true,
        'eventDragEnd' => 
        'document.getElementById("Lat").value=event.latLng.lat();
         document.getElementById("Long").value=event.latLng.lng();'
      ]);
this my view
 <div class="form-group">
                  <label class="control-label" for="avatar">Map</label><br />(Drag marker)
                  <div style="width: 300px; height: 300px; border:1px solid #ccc;">
                    {!! Mapper::render() !!}
                  </div>
                </div>
this how, i save marker, how can i save polygon in single field? example  polygon not latitude and longitude

**Comment by rendyif** [comment]
found this solution in here https://stackoverflow.com/questions/15454919/extract-drawingmanager-polygon-path-google-maps-on-click

**Comment by bradcornford** [comment]
Hi there,

You would look to assigning events to the map, and use Javascript itself to post to an end point to store the data within your database. See the following for more information: https://github.com/bradcornford/Googlmapper/issues/175
