### ISSUE TITLE
Google Map Gray Blank

### ISSUE THREAD

**Issue by muaramasad** [bradcornford/Googlmapper#243]
Hi,
Thanks for this awesome package, it's really help me a lot when working with google maps. 
but i have a problem, the map only show gray box no map and there is no error message on console, could please help me ?
Thanks,
Laravel : 5.5
controller 
```
Mapper::map(-1.7922201, 116.9502052, ['zoom' => '5','center' => true, 'marker' => false, 'cluster' => false]);
        $provinceId = [];
    	$division = Division::find($id);
    	$sites = Site::where('division_id',$id)->get();
    	$areas = Area::where('division_id',$id)->with('province')->get();
        foreach ($areas as $area) {
            if ($area->has('sites')) {
                $provinceId[] = $area->province->id;
            }
        }
        $ProvinceCollection = Province::find($provinceId);
        $ProvinceCollection->each(function($province)
        {
            $content = $province->province_name;
            Mapper::marker($province->province_cor_x, $province->province_cor_y,['eventClick' => 'window.location.href = "/map/province/'.$province->province_code.'";']);
        });
    	return view('maps.div',[
    		'areas' => $areas,
    		'division' => $division,
    		'sites' => $sites
    	]);
```

view
```
@extends('layouts.app')
@section('content')
{{ Breadcrumbs::render('division', $division) }}
<div class="columns">
	<div class="column">
		<div class="card">
			<header class="card-header">
				<p class="card-header-title">
					{{ $division->division_name }}
				</p>
			</header>
			<div class="card-content">
					<div id="mapdiv" style="width: 100%; height: 600px;">
						{!! Mapper::render() !!}
					</div>
			</div>
		</div>
	</div>
</div>
@endsection
```

**Comment by RadoszSzymon** [comment]
Google map on my website also stop working...

**Comment by bradcornford** [comment]
Hi there,

I am also seeing the same issue myself. I've even backed up versions to see the same error. As such, it would seem that something may have changed with Google Maps API itself. I will investigate this issue and try to resolve.

**Comment by bradcornford** [comment]
Okay, seems like there is issues with the experimental version of GoogleMaps, as such i've pinned the version to 3.31. This has been resolved in current version v2.31.2/v1.25.2.

**Comment by cdoouteiro** [comment]
Work with v2.31.2, thanks for your work @bradcornford 👍

**Comment by janikaja** [comment]
looks like `var idleListener = google.maps.event.addListenerOnce(map_0, "idle", function () { ...` is not working - the event is not firing

**Comment by janikaja** [comment]
... which means that map's zoom is not set

**Comment by ifirestone** [comment]
with v2.31.2, not working for me @bradcornford, using Mapper::map(latitud, longitud) nothing else, still same problem.

**Comment by ifirestone** [comment]
@janikaja if you go full screen can come back then it renders the maps.

**Comment by janikaja** [comment]
@ifirestone yes, also if you set the zoom twice - I put it into `eventBeforeLoad`

**Comment by ifirestone** [comment]
Hi @janikaja can you point me how to? im not really fluent on JavaScript.... thanks in advance

**Comment by janikaja** [comment]
Hi, @ifirestone,
in my case I just had to make another call of `map.setZoom(zoom);` function and to do that, first of all I made changes in my Laravel controller:
`Mapper::map($lat, $lng, [
            'zoom' => $zoom,
            'eventBeforeLoad' => 'styleGoogleMap(map, ' . $zoom . ');'
        ]);`

and then in my Blade template I updated that `styleGoogleMap` Javascript function with `map.setZoom(zoom);`. I said "updated" because up to now I used it only for custom styling.

**Comment by bradcornford** [comment]
@janikaja @ifirestone  Okay, i've now set the zoom option at construction. This should alleviate the issue you are seeing. This is in current version v2.31.3/v1.25.3. Make sure once you update that you publish the packages resources.

**Comment by HusamAamer** [comment]
FYI, Now `3.exp` back to work normally

**Comment by kevin-kp** [comment]
in src/views/javascript.blade.php, you should remove the signed_in parameters,
it's deprecated: https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported
After i removed this parameter, the maps worked again

**Comment by bradcornford** [comment]
I've now removed Signed in Support from the package in current version v2.31.4/v1.25.
