### ISSUE TITLE
Mapper::render() error in version v2.31.4

### ISSUE THREAD

**Issue by ajzuse** [bradcornford/Googlmapper#244]
At call Mapper::render() in my view, the error in image is generated.

![captura de tela 2018-03-07 as 10 35 56](https://user-images.githubusercontent.com/3410356/37094969-5d2385dc-21f3-11e8-8d74-c31aa3c42d1e.png)

My installed packages is:
alexpechkarev/geometry-library        1.0.0  
alexpechkarev/google-maps             1.0.9     
cornford/googlmapper                  v2.31.4  
dnoegel/php-xdg-base-dir              0.1       
doctrine/annotations                  v1.6.0 
doctrine/cache                        v1.7.1      
doctrine/collections                  v1.5.0  
doctrine/common                       v2.8.1     
doctrine/dbal                         v2.6.3 
doctrine/inflector                    v1.3.0     
doctrine/instantiator                 1.1.0      
doctrine/lexer                        v1.0.1     
egulias/email-validator               2.1.3   
eighty8/laravel-seeder                5.5.1       
erusev/parsedown                      1.7.0   
fideloper/proxy                       3.3.4    
filp/whoops                           2.1.14    
firephp/firephp-core                  dev-master ea6a06a
fzaninotto/faker                      v1.7.1        
hamcrest/hamcrest-php                 v2.0.0 
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jbroadway/urlify                      1.1.0-stable 
laravel/framework                     v5.5.36 
laravel/homestead                     v7.2.0  
laravel/tinker                        v1.0.4  
lavary/laravel-menu                   v1.7.2 
league/flysystem                      1.0.43
mockery/mockery                       1.0    
monolog/monolog                       1.23.0
mtdowling/cron-expression             v1.2.1   
myclabs/deep-copy                     1.7.0 
nesbot/carbon                         1.23.0   
nikic/php-parser                      v3.1.5 
orangehill/iseed                      dev-master c99a9f7 
paragonie/random_compat               v2.0.11 
phar-io/manifest                      1.0.1       
phar-io/version                       1.0.1 
phpdocumentor/reflection-common       1.0.1
phpdocumentor/reflection-docblock     4.3.0
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      1.7.5
phpunit/php-code-coverage             5.3.0
phpunit/php-file-iterator             1.4.5
phpunit/php-text-template             1.2.1
phpunit/php-timer                     1.0.9
phpunit/php-token-stream              2.0.2    
phpunit/phpunit                       6.5.7   
phpunit/phpunit-mock-objects          5.0.6    
predis/predis                         v1.1.1  
psr/container                         1.0.0 
psr/log                               1.0.2  
psr/simple-cache                      1.0.1
psy/psysh                             v0.8.17 
ramsey/uuid                                 3.7.3 
sebastian/code-unit-reverse-lookup    1.0.1
sebastian/comparator                  2.1.3
sebastian/diff                        2.0.1 
sebastian/environment                 3.1.0
sebastian/exporter                    3.1.0
sebastian/global-state                2.0.0
sebastian/object-enumerator           3.0.3 
sebastian/object-reflector            1.1.1
sebastian/recursion-context           3.0.0
sebastian/resource-operations         1.0.0
sebastian/version                     2.0.1
squizlabs/php_codesniffer             3.2.3
swiftmailer/swiftmailer               v6.0.2
symfony/console                       v3.4.6
symfony/css-selector                  v4.0.6
symfony/debug                         v3.4.6
symfony/event-dispatcher              v4.0.6
symfony/finder                        v3.4.6
symfony/http-foundation               v3.4.6
symfony/http-kernel                   v3.4.6
symfony/polyfill-mbstring             v1.7.0
symfony/polyfill-php70                v1.7.0
symfony/process                       v3.4.6
symfony/routing                       v3.4.6
symfony/translation                   v4.0.6
symfony/var-dumper                    v3.4.6
symfony/yaml                          v4.0.6
theseer/tokenizer                     1.1.0 
tijsverkoyen/css-to-inline-styles     2.2.1
vlucas/phpdotenv                      v2.4.0
webmozart/assert                      1.3.0

I need help to solve this issue.

**Comment by ifirestone** [comment]
delete and re-publish the packages

**Comment by bradcornford** [comment]
Hi there,

Yes, just re-publish the packages assets and you should be fine.

**Comment by ajzuse** [comment]
Thank's for help! Now all is working!

**Comment by rodericktech** [comment]
Could someone please provide a bit more detail on exactly what they deleted and republished to get this working?  I am getting the same error (using Laravel) and am having no success removing and reinstalling the package, clearing caches, re-running vendor:publish, etc.

Thank you!
