### ISSUE TITLE
Displaying new markers via AJAX

### ISSUE THREAD

**Issue by reymark-torres** [bradcornford/Googlmapper#245]
Basically I have a search function to re-render the Google Map to display new markers based in the input of the user.

Are there any implementation to this?
I'm having trouble rending the Google Map again as it reports the error:

**"You have included the Google Maps API multiple times on this page. This may cause unexpected errors."**

Then when I include: View::share('javascript', true); in my search method the error was gone but my Google Map does not show anymore as I call Mapper::render() again in my controller.

I will really appreciate your response.
Thank you very much

**Comment by bradcornford** [comment]
Hi there,

You could just add markers to the map via Javascript, and move the map to that location, something like this would suffice:

```php
Mapper::map(40, -100, ['zoom' => 4, 'marker' => false, 'type' => MapperBase::TYPE_ROADMAP, 'eventBeforeLoad' => 'addEventListener(map);']);
```

```html
<script type="text/javascript">

            dynamicallyCreatedMarkers = [];

            function addEventListener(map)
            {
                google.maps.event.addListener(map, 'click', function (e) {
                    var marker = new google.maps.Marker({
                        position: e.latLng,
                        map: map
                    });

                    map.panTo(e.latLng);
                    dynamicallyCreatedMarkers.push({
                        position: e.latLng
                    });
                });
            }

            $('#submit').click(function() {
                $.ajax({
                    type: "POST",
                    url: '/',
                    data: dynamicallyCreatedMarkers.serialize(),
                    success: function(response)
                    {
                        console.log('success')
                    }
                });
            });

        </script>
```
