### ISSUE TITLE
Unable to perform location search: SSL operation failed with code 1

### ISSUE THREAD

**Issue by alexvilcu** [bradcornford/Googlmapper#246]
Hello there! I have an issue with the Mapper::location() method. It worked until today and I am stuck in finding out the cause of it. It seems like when I am using the following method:
`public function map()
   {	
   Mapper::map(50.381128999999990000, -1.470085000000040000);
   
return view('cornford.map');	
    }`

the map is rendered correctly, but when I try:

`public function map()
 
{
    Mapper::location('Sheffield')->map();
    render view('cornford.map');
}`

I get the following error:
Unable to perform location search, the error was: "file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed".

I am really stuck because the location() method worked until today. I got a new API Key also but still the problem persisted. Have any idea where should I start?
I am running the project on a local apache server using laragon. Thanx a lot :D

**Comment by alexvilcu** [comment]
Ok, after hours of searching I think I found the problem. Seems like the CA certification has been updated in the last days, so in order to make php work, you have to download the latest CA certificate bundle (you can download it as a cacert.pem file) and store it on your machine. Then, point to that location where you saved the cacert.pem file in your php.ini by writing this line: openssl.cafile=/"path-to-your-location"/cacert.pem. I will leave this comm here if someone struggles with this too. tnx :D

**Comment by bradcornford** [comment]
Hi there,

I'm glad you resolved this issue! It may also be work updating your Open SSL packages too if the problem persists.
