### ISSUE TITLE
mapTypeControl 

### ISSUE THREAD

**Issue by giuseppeauteri** [bradcornford/Googlmapper#248]
Hi, 
i can't setting mapTypeControl. 

Mapper::map(lat, lng,
                    [
                        'fullscreenControl'=>false,
                       'mapTypeControl'=>false,
                    ])

mapTypeControl is ignored

thnx for your help

**Comment by giuseppeauteri** [comment]
Fixed 

added

mapTypeControl: @if ($options['mapTypeControl']) true @else false @endif,
in map.blade.php line 20

**Comment by bradcornford** [comment]
Hi there,

This should already be in the package. Perhaps you need to re-publish the packages assets.
