### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by mateevd** [bradcornford/Googlmapper#249]
Hi, 

the mapper was working fine until yesterday when I did composer update. Now I have this error:

<img width="701" alt="croquis 2" src="https://user-images.githubusercontent.com/29518478/37350563-6474417e-26d9-11e8-8b44-a5e81da023e5.png">

I'm probably missing something but just can't figure it out.......

**Comment by mateevd** [comment]
Never mind fix it. Just had to delete the cornford viex folder and then re-publish :)

**Comment by MarKco** [comment]
Hello mateevd. Thank you for this!

For those who don't know how to clean the view folder and re-publish:
1. delete /resources/views/cornford/googlmapper folder
2. from root folder, perform `php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper`
