### ISSUE TITLE
How to reposition map after infowindow content dynamically loaded

### ISSUE THREAD

**Issue by ghost** [bradcornford/Googlmapper#253]
Hi, I had insert into the infowindow two buttons that on click call a controller function (by ajax) and return html that is appended to infowindow content.
On call success the result is that infowindow is not completely visible. 
Is there a way to reposistion the map to view entirely the infowindow?
When map is loaded the situation is:
![37658941-fc6c53ac-2c4e-11e8-85db-b7ab8d86e326](https://user-images.githubusercontent.com/33837603/38617490-7ab95d0a-3d97-11e8-89f0-713cdf6eb84b.png)
After click on "Altri dati" button the situation is:
![37658908-e4dc6f10-2c4e-11e8-828e-f85783e60524](https://user-images.githubusercontent.com/33837603/38617474-723afdaa-3d97-11e8-8b24-c946bbdc8ef4.png)

Thanks a lot.

**Comment by bradcornford** [comment]
Hi there,

The only real thing i can think of is to set the location of the map when you click the button to the marker position. Something like this:

```js
maps[0].setCenter(marker.getPosition());
```
