### ISSUE TITLE
Laravel 5.6 Undefined index: user

### ISSUE THREAD

**Issue by 06chaynes** [bradcornford/Googlmapper#254]
I have a strange issue after upgrading Laravel from 5.5 to 5.6. 

When I try to load a map I get an error thrown from the javascript.blade.php and marker.blade.php files that $config['user'] is not defined. I have double checked my config file for errors but the syntax is valid and user is defined (false). For now I have manually set the value to false in the blade templates and that is working.

**Comment by jozeflambrecht** [comment]
you need to delete the googlmapper view-files and republish

**Comment by 06chaynes** [comment]
Ah, I had tried running the publish command again but didn't delete the existing files first. All is working again, thank you
