### ISSUE TITLE
not able to get long, lat and address on  Draggable Markers

### ISSUE THREAD

**Issue by devParry** [bradcornford/Googlmapper#256]
Hi,

I am new in laravel. I am using googlemapper i have successfully display map on my view page.
now ihave to get long and lat and display into the text box. while user drag the marker on google map but i am not able to get it please help me to fix this.  Please have a look on my code 

`Mapper::map(0, 0)->marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP'] , 'draggable' => true, 'eventDrag' => 'getMapData(maps)' ]);`

and my callback function is : 

`function getMapData(mapsData){
	console.log(mapsData);
	
}`

Please have a look on my console screen-short : 
![console2](https://user-images.githubusercontent.com/30040278/37902536-583a2e80-3112-11e8-9d2c-0477dabf74e4.png)

**Comment by farhanamandaa** [comment]
Try to use 'eventDragEnd' instead of 'eventDrag'. Reference : #97

**Comment by bradcornford** [comment]
Hi there,

You nearly have it right, your just not accessing the markers object of the map:

Try the following:

```function getMapData(mapsData){
console.log(mapsData[0].markers);

}```

**Comment by Mohsing511** [comment]
Helper for Google map lat long use in marker[**Here**]
'eventDragEnd' =>"(document.getElementById('lat').value=(event.latLng.lat())); (document.getElementById('long').value=(event.latLng.lng()))"
