### ISSUE TITLE
Mapper::render not working in section('content')

### ISSUE THREAD

**Issue by s5510886103** [bradcornford/Googlmapper#261]
if run 
`    <section class="content">
        <div class="container">
            <div style="width: 100%; height: auto;">
                {!! Mapper::render() !!}
            </div>
        </div>
    </section>`
it working
but pass section not working
`@extends('frontend.layouts.app')
@section('content')
    <section class="content">
        <div class="container">
            <div style="width: 100%; height: auto;">
                {!! Mapper::render() !!}
            </div>
        </div>
    </section>
@endsection
`

**Comment by bradcornford** [comment]
Hi there,

I'm not sure what the issue that you are seeing as i can't seem to replicate it myself!

**Comment by AhSem** [comment]
I think what happen is that "width: 100%; height: auto" is not showing the map. Any workaround? @bradcornford

**Comment by bradcornford** [comment]
@AhSem Yes, you would need to set a height as theres a know issue with Google Maps and auto height.

Try something like;

```
html, body, .content {
            height: 100%;
            width: 100%;
        }
```
