### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by MuhammadHamza14-SE-58** [bradcornford/Googlmapper#263]
Undefined index: user (View: C:\xampp\htdocs\StayAndPark\resources\views\cornford\googlmapper\javascript.blade.php) (View: C:\xampp\htdocs\StayAndPark\resources\views\cornford\googlmapper\javascript.blade.php) (View: C:\xampp\htdocs\StayAndPark\resources\views\cornford\googlmapper\javascript.blade.php)

The map is not working. Please help me.

**Comment by jaejamesuk** [comment]
Hi,
Can you show a bit more of your code? Undefined index is normally when your trying to instance an array/object without the variable you are looking for existing.

**Comment by MuhammadHamza14-SE-58** [comment]
Thanks I got it fixed. There was problem in javascript  file.

**Comment by bradcornford** [comment]
Hi, 

Sorry for the late reply, glad you got this fixed! I think you just needed to re-publish the packages assets.

**Comment by danilosantosdev** [comment]
I'm still facing the same problem.

My Laravel is the version 5.1

I re-publish, but the problem persist.

What can i do? Thanks!
