### ISSUE TITLE
A not needed marker is displaying 

### ISSUE THREAD

**Issue by MuhammadHamza14-SE-58** [bradcornford/Googlmapper#265]
When using the map a not needed marker is always shown due to Mapper::map(33.7669097,72.8232996);  as i know this is necessary. But Is there any way to remove that because i dont need it. 

![not needed](https://user-images.githubusercontent.com/34311257/39124593-63229c88-4715-11e8-94fd-aa8179dd4e53.JPG)

**Comment by MuhammadHamza14-SE-58** [comment]
Sorry. I got it fixed using marker=>false

**Comment by bradcornford** [comment]
Hi there,

Yeah, thats possible. For reference: 

```php
Mapper::map(33.7669097, 72.8232996, ['marker' => false]);
```
