### ISSUE TITLE
marker.autoclose option does not seem to work

### ISSUE THREAD

**Issue by nileshd** [bradcornford/Googlmapper#266]
Has the marker.autoclose option been deprecated? 

It seems to be in the documentation, but not in the code or config anymore.

Without this option, multiple markers stay open on click. How can markers be automatically close without that option?

**Comment by bradcornford** [comment]
Hi there,

This can be accomplished as follows:

```php
Mapper::map(0, 0, ['markers' => ['autoclose' =>true]])
Mapper::infoWindow(1, 1, 'Test', ['autoclose' =>true])
```
