### ISSUE TITLE
Getting lat and long from user when it drag the pin

### ISSUE THREAD

**Issue by MuhammadHamza14-SE-58** [bradcornford/Googlmapper#267]
Hi,
I am developing a laravel application in which i want user to input the location of a particular place. The user will drag the pin to desired location and in backend the lat and long of that location will be extracted and inserted into database. 

Could you please help me. 

Thanks

**Comment by bradcornford** [comment]
Hi there,

This isn't something that is natively available with this library, however it can be achieved by using events and hooks, see both #178 and #135 for more information.

Also here is Google Maps documentation: https://developers.google.com/maps/documentation/directions/intro
