### ISSUE TITLE
Autoclosing marker infowindows

### ISSUE THREAD

**Issue by gtree6** [bradcornford/Googlmapper#268]
Hello there,
I'm having problems using the 'autoclose' option on markers' information windows. It doesn't seem to work whatsoever. It is also not present in the config file (googlmapper.php). Has it been deprecated and if so, how can I go about achieving such a functionality?

Thanks in advance and keep up the good work!

**Comment by gtree6** [comment]
I found the solution in another thread...this is how it works.
Mapper::map(0, 0, ['markers' => ['autoclose' =>true]])
Mapper::infoWindow(1, 1, 'Test', ['autoclose' =>true])

However, the ['autoclose'=>true] should actually be ['autoClose' => true, with capital 'C'.

**Comment by bradcornford** [comment]
Hi there,

Glad you got to the bottom of this! I've now updated the documentation to reflect this in current version v2.31.5/1.25.6.
