### ISSUE TITLE
Support different API keys for server side and client side requests

### ISSUE THREAD

**Issue by bluec** [bradcornford/Googlmapper#269]
It seems that currently this component supports only a single google API key and this is used for both server side requests (e.g. Geocoding API via file_get_contents()) and also for client side requests (e.g. Maps API via Javascript).

It is common to need access to both the server side and client side APIs, for example to show the map of an address you need access to both the Geocoding API and Maps API.

As this currently uses a single API key for both types of requests we cannot adequately restrict the API key usage within the Google Developer Console. For server requests we need to restrict by IP address, but for client requests we need to restrict by referrer. The console only allows one of the other, so if you're currently using both server side and client side requests then you have no choice but to have no restrictions on the key usage. I therefore suggest this component should use a different key for server and client side requests.

**Comment by bradcornford** [comment]
Hi there,

This functionality should be possible using the method `Mapper::setKey('xxx');` for server side requests. Then switch back to the default API key. I know this isn't ideal but is certainly possible.

Feel free to raise a PR to address this if you like.

**Comment by bluec** [comment]
That would work for some methods but, for example, `Mapper::location('xxxxx');` method uses both a server-side and client-side API call so would still use the same key for both.

I will have a look and see whether I can figure out a clean way to implement two API keys. Do you have any suggestions? I don't want to make it messy.

**Comment by bluec** [comment]
Actually, maybe I'm mistaken, could you call it like this in the controller:

```
Mapper::setKey('server-side-key'); 
Mapper::location('xxxxx'); 
```

And then like this in the view:

```
{!! Mapper::setKey('client-side-key') !!} 
{!! Mapper::render() !!}
```

**Comment by bradcornford** [comment]
Yeah that would work. I know its not the best experience however.
