### ISSUE TITLE
Info Window Events

### ISSUE THREAD

**Issue by gtree6** [bradcornford/Googlmapper#270]
Hi, good job on the package, it's only getting better :)
I don't see an option to add events to an information window, such as 'closeclick', 'domready', etc...
Is this something that you would consider adding to the package?
Until then, any suggestions on how I would go about achieving such a functionality?

**Comment by bradcornford** [comment]
Hi there,

All the current events for makers should also work for information windows. There are however, a number of events that haven't yet been implemented. I'll look at getting these implemented soon, or feel free to raise a PR with it.

Here are the supported events so far:

- 'eventClick'
- 'eventDblClick'
- 'eventRightClick'
- 'eventMouseOver
- 'eventMouseDown'
- 'eventMouseUp'
- 'eventMouseOut'
- 'eventDrag'
- 'eventDragStart'
- 'eventDragEnd'
- 'eventDomReady'

You could however attach an event to the map after load, and then loop through all info windows adding your desired event listener.

```php
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'addEventListener(map);']);
```

```html
        <script type="text/javascript">

            function addEventListener(map)
            {
                maps[0].infowindows.forEach(function(marker) {
                     google.maps.event.addListener(marker, 'EVENTNAME', function (event) {
			// EVENT ACTION
		     });
                 });
            }

        </script>
```

**Comment by gtree6** [comment]
Hey, 
thanks for the snippet, it did the job perfectly. I'll see if I can get around to contributing before you decide to implement this.
