### ISSUE TITLE
Multiple Markers

### ISSUE THREAD

**Issue by jamalnasir** [bradcornford/Googlmapper#271]
How to display multiple markers with different LAT and LON with information window each  - on a single map?

**Comment by umair321** [comment]
@gidaban link not found

**Comment by bradcornford** [comment]
Hi there,

This is as simple as the following:

```php
Mapper::map(40, -100, ['zoom' => 4, 'marker' => false, 'type' => MapperBase::TYPE_ROADMAP]);
Mapper::informationWindow(40, -99, 'hello']);
Mapper::informationWindow(41, -98, 'hello']);
Mapper::informationWindow(42, -97, 'hello']);
```

**Comment by bradcornford** [comment]
Here is the link that @gidaban supplied https://github.com/bradcornford/Googlmapper/issues/250
