### ISSUE TITLE
how i can change icon marker?

### ISSUE THREAD

**Issue by rplkabir** [bradcornford/Googlmapper#272]

**Comment by cloudwales** [comment]
Hope this helps... 

```
Mapper::informationWindow(-1.11111, 11.11111,[

    				'marker' => true,
    				'markers' => [
    					'symbol' => 'circle',
    					'icon' => /path/to/your/icon.png'',
    					'autoclose' => true,
    					'animation' => 'DROP'
    				],
    
]);
```

**Comment by bradcornford** [comment]
Hi there,

Further to @cloudwales answer, the following also works:

```
Mapper::map(-1.11111, 11.11111,[
        'markers' => [
            'symbol' => 'circle',
            'icon' => /path/to/your/icon.png'',
            'animation' => 'DROP'
    ],   
]);
```

**Comment by sparkcures** [comment]
We are experiencing a similar issue. No matter what we do, we can't get custom icons to show up on the map. Any help would be greatly appreciated.

`Mapper::map($mapLat, $mapLon, [
               'zoom' => $mapZoom,
               'scrollWheelZoom' => false,
               'cluster' => false,
               'async' => false,
               'marker' => false,
               'fullscreenControl' => false,
               'streetViewControl' => false,
               'mapTypeControl' => false,
               'center' => $centerMap
          ]);

foreach ($this->centers as $trialCenter)
          {
               $content = view('centers.shared.map.information_window')
                    ->with('center', $trialCenter->center)
                    ->render();

               Mapper::informationWindow($trialCenter->center->lat, $trialCenter->center->lon, $content, [
                    'open' => false,
                    'marker' => true,
                    'markers' => [
                         'symbol' => 'circle',
                         'icon' => asset('img/maps/blue-pin.png'),
                         'autoClose' => true
                    ],
               ]);
          }`

And the icon is always blank.

<img width="388" alt="Screen Shot 2019-06-26 at 3 40 14 PM" src="https://user-images.githubusercontent.com/51457263/60209459-bc7e0500-9828-11e9-9945-39e68cf432fc.png">

Thanks!

**Comment by bradcornford** [comment]
Hi @sparkcures, move the items from within the "markers" array to base array. Alternatively move the markers array into the map array.

```Mapper::informationWindow($trialCenter->center->lat, $trialCenter->center->lon, $content, [
                'open' => false,
                'marker' => true,
                
                     'symbol' => 'circle',
                     'icon' => asset('img/maps/blue-pin.png'),
                     'autoClose' => true
                
           ]);
      }

```

**Comment by sparkcures** [comment]
Perfect! Thank you.

**Comment by Hmerman6006** [comment]
I am using version 3.* with Laravel 8 and also could not render with `icon` as  `string`.  The reason it did this is because the code base changed and it expects the `icon` key to be an `array` with two keys nl. `string` `url` and `array` `size` i.e.<br />
```
Mapper::informationWindow($trialCenter->center->lat, $trialCenter->center->lon, $content, [
                'open' => false,
                'marker' => true,
                'icon' => [
                                 'url' => asset('img/maps/blue-pin.png'),
                                 'size' => [58,88], // width,height
                                ],
                'autoClose' => true
                
           ]);
      }

```
BUT, do not set the `symbol` key.  This is very important, the code excludes the `icon` key if `symbol` is set.  If `symbol` is set the `scale` key should be set. No `symbol` it looks for `icon`.  Here is a snippet of the `marker.blade` that renders the map.<br />
```
@if ($options['symbol'])
    icon: {
              path: google.maps.SymbolPath.{!! $options['symbol'] !!},
	      scale: {!! $options['scale'] !!}
		}

	@else
@else
		icon:

		@if (is_array($options['icon']) && isset($options['icon']['url']))

			{
                                url: {!! json_encode((string) $options['icon']['url']) !!},
				@if (isset($options['icon']['size']))

					@if (is_array($options['icon']['size']))

						scaledSize: new google.maps.Size({!! $options['icon']['size'][0] !!}, {!! $options['icon']['size'][1] !!})

					@else

						scaledSize: new google.maps.Size({!! $options['icon']['size'] !!}, {!! $options['icon']['size'] !!})

					@endif

				@endif

			}
```
