### ISSUE TITLE
Change the marker animation on mouse eventMouseOver

### ISSUE THREAD

**Issue by rddewan** [bradcornford/Googlmapper#274]
Hi
How can i change the marker animation on mouse eventMouseOver

public function index()
    {
        Mapper::map(0, 0,
            [
                'zoom' => 15,
                'draggable' => true,
                'marker' => false,
                'center' => false,
                'markers' => ['title' => 'To jest właśnie tutaj!', 'animation' => 'DROP'],

            ]);

        $markers = [
            ['lat' => 50.061711, 'lng' => 19.937356,'content'=>'D01'.' 10.15AM'],
            ['lat' => 50.063693, 'lng' => 19.911742,'content'=>'D01'.' 10.15AM'],
            ['lat' => 50.057979, 'lng' => 19.920445,'content'=>'D02'.' 10.15AM'],
            ['lat' => 50.054466, 'lng' => 19.936655,'content'=>'D02'.' 10.15AM']
        ];

        foreach ($markers as $marker) {
            Mapper::informationWindow($marker['lat'], $marker['lng'],$marker['content'],['open' => true,
                'eventMouseOver' => 'BOUNCE']);
        }

        return view('gps_log/map');
    }

**Comment by bradcornford** [comment]
Hi there,

Something like the following would work:

```php
Mapper::informationWindow($marker['lat'], $marker['lng'],$marker['content'],['open' => true, 'eventMouseOver' => 'this.setAnimation("BOUNCE");']);

```
