### ISSUE TITLE
No works in Mailable build function

### ISSUE THREAD

**Issue by cubiczx** [bradcornford/Googlmapper#275]
`class TicketUpdated extends Mailable
{
...
/**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);
        return $this->from('test@test.com')
                    ->view('emails.update')
                    ->with([
                        'title' => $this->title
                    ]);
    }
}
...
`

**Comment by cubiczx** [comment]
In mail HTML create:
`<div style="width: 500px; height: 500px;">
<div id="map-canvas-0" style="width: 100%; height: 100%; margin: 0; padding: 0; position: relative; overflow: hidden;"></div>
</div>`

**Comment by cubiczx** [comment]
My template contains
`<div style="width: 500px; height: 500px;">
			{!! Mapper::render() !!}
		</div>`

**Comment by bradcornford** [comment]
Hi there,

Could you call the render within your build method, then pass it through to the template as HTML. For example:

```php
public function build() { Mapper::map(53.381128999999990000, -1.470085000000040000); $map = Mapper::render(); return $this->from('test@test.com') ->view('emails.update') ->with([ 'title' => $this->title, 'map' => $map ]); } 

```

```
<div style="width: 500px; height: 500px;"> {!! $map !!} </div>
```
