### ISSUE TITLE
Exceptions could each extend the MapperException class?

### ISSUE THREAD

**Issue by bluec** [bradcornford/Googlmapper#276]
Would it be better if each of the various exceptions extended the MapperException (or some other Mapper-specific exception) class?

This would be useful when catching exceptions as we could then catch MapperException as a catch-all. Currently (< PHP 7.1 at least) we have to catch /Exception and then test whether it is an instanceof the various exceptions, or use different catch blocks for each exception type.

**Comment by bradcornford** [comment]
Hi there,

Yes, this seems like a great idea, usually i like to handle Exceptions individually. But a catch all abstract could be useful. I'll look into implementing this.

**Comment by bradcornford** [comment]
This has now been implemented in current versions v2.32.0/v1.26.0.
