### ISSUE TITLE
Location geodecoding and creating map

### ISSUE THREAD

**Issue by anantaramdas** [bradcornford/Googlmapper#277]
Hi could you please advise me:
I'm running following code `Mapper::location('Kiev')->map(['zoom' => 15, 'center' => true, 'marker' => true]);` and for some reason getting following https://www.google.com/maps/@50,-179,15z?hl=en-GB (while `Mapper::location('Kiev')` gives me correct coordinates for Kiev).

Thanks!

**Comment by bradcornford** [comment]
Hi there,

This sounds like some kind of localisation issues, have you tried updating the configuration for language to your locale?

```    /*
    |--------------------------------------------------------------------------
    | Language
    |--------------------------------------------------------------------------
    |
    | The Language Google API should use required in ISO 639-1 code format.
    |
    */
    'language' => 'en-gb',```
