### ISSUE TITLE
Map in grey and non-centered

### ISSUE THREAD

**Issue by poxxac** [bradcornford/Googlmapper#279]
So, everything was working good until a week ago or so when for some reason (composer update or something I don't know) some maps started to show in grey and non-centered, all markers are outside the view and I have to move the map to the right/down to see them, however the map still in grey.

All the code to generate the map is the same for all of them, however, homepage map works good, every entity view map also, but the other maps don't.

Thanks in advance for the help.

![ss 1](https://user-images.githubusercontent.com/5736422/42491283-79e7fb68-83d1-11e8-94bf-7a4c8286266d.png)
![ss 2](https://user-images.githubusercontent.com/5736422/42491284-7a01ae32-83d1-11e8-87f0-f8e305111553.png)
![ss 3](https://user-images.githubusercontent.com/5736422/42491285-7a18c630-83d1-11e8-88cf-752e37f19ef3.png)

**Comment by poxxac** [comment]
As an extra information I just notice. Maybe has something to do with the issue (or not), the views where the map is not showing is where I have the map in a JQuery tab.

![ss 4](https://user-images.githubusercontent.com/5736422/42491788-86a5d24c-83d3-11e8-9dbd-8e5afadde972.png)

**Comment by bradcornford** [comment]
Hi there, 

This is a known issue with jQuery and Google Maps. However, something like the below should work for you:

```
$('#tabname').on('click, function () {
    var map = maps[0].map;
    var currentCenter = map.getCenter();
    google.maps.event.trigger(map, "resize");
    map.setCenter(currentCenter);
});
```
