### ISSUE TITLE
publishable views

### ISSUE THREAD

**Issue by eskrano** [bradcornford/Googlmapper#28]
Hello, can you make views publishable ? For example i need add some options , but i can't...

**Comment by bradcornford** [comment]
Hi there,

Can you explain what you mean?

**Comment by eskrano** [comment]
Thanks :+1:

**Comment by eskrano** [comment]
Hmm i see publishable views, but in this time render views from vendor. I think you can add config option like 'render_from' => 'vendor|views' :+1:  
What do you think about this idea?

**Comment by bradcornford** [comment]
Ah yes, the method 'loadViewsFrom' in the service provider was pointing to the package views rather than the published views.
