### ISSUE TITLE
Search Location Autocomplete without Map 

### ISSUE THREAD

**Issue by komalkantGupta** [bradcornford/Googlmapper#280]
HI,
I am looking for autoComplete Search Location in your Package but can not find,
Just want to search location box without Map.
Follow this URL I need same functionality without showing map Url- http://demos.codexworld.com/autocomplete-places-search-box-google-maps-javascript-api/

**Comment by bradcornford** [comment]
Hi there,

The package doesn't support this natively, however this has been done before. See: https://github.com/bradcornford/Googlmapper/issues/114
