### ISSUE TITLE
Will new Google API affect this?

### ISSUE THREAD

**Issue by rickjm540** [bradcornford/Googlmapper#281]
So July 16th google is restricting the API somewhat - will this affect googlemapper in any way?

**Comment by carlluo** [comment]
I'm seeing some restriction on my search results as well now. Do you have any more info as to what fields in the API is restricted now?

**Comment by bradcornford** [comment]
Hi there, 

I haven't had enough time to delve into the details of the change Google is making to the API. However, a brief look shows that most of the functionality of the package should still work.

**Comment by bradcornford** [comment]
After looking into this a little more, it appears that location searching, directions, and mapping are both covered by the API changes. These features should still work, as long as the API key is setup to allow these functions. See: https://developers.google.com/maps/documentation/javascript/get-api-key#restrict_key
