### ISSUE TITLE
Add Mapper::marker to array of markers

### ISSUE THREAD

**Issue by DigitalDotEU** [bradcornford/Googlmapper#282]
Hi, I can't solve some problem. When I created markers in my controller I want to create javascript array called markers[] and add every marker to that array. I need that to change selected marker icon later. Maybe you have better idea how to change selected marker icon(other markers should have default icon)?

```
 Mapper::marker(
                $results[$i]['lat'],
                $results[$i]['lng'],
                [
                    'draggable' => false,
                    'eventAfterLoad' => 'console.log("before load");',
                    'eventClick' => 'this.setIcon(\'img/map2.png\');
                ]);
```

**Comment by bradcornford** [comment]
Hi there,

The package already does this for you. The following can be used to access each marker:

```
console.log(maps[0].markers);
```
