### ISSUE TITLE
Multiple markers in same location

### ISSUE THREAD

**Issue by cloudwales** [bradcornford/Googlmapper#283]
Hi. Is there a tidy way of displaying multiple markers at the same location? As it stands it just clusters but i have an app that sometimes theres a marker in the same location.

Many thanks

**Comment by bradcornford** [comment]
Hi there,

I don't think this would be possible in the package itself. If you're loading the markers from a DB then you could put some logic in place to achieve this however.

**Comment by cloudwales** [comment]
Brilliant no problem. Will have a look into it.

Cheers
