### ISSUE TITLE
Callback raising initialize_method is not a function

### ISSUE THREAD

**Issue by DLO33** [bradcornford/Googlmapper#285]
I have a page with a single map and sometimes I get a 'initialize_method is not a function' error and the map doesn't load.
Using cornford/googlmapper v 2.32.
I have async set to true but still encountering this error.

Controller:
```
Mapper::map($lat, $lng, ['zoom' => 14, 'marker' => true, 'center' => true,
                  'draggable' => true, 'streetViewControl' => false,
                  'mapTypeControl' => false, 'fullscreenControl' => false, 'async' => true,
                  'eventAfterLoad' => 'mapLoaded()']);
```
Blade:
```
<div id="listing-map">
    {!! Mapper::render () !!}
  </div>
```

Error:
![image](https://user-images.githubusercontent.com/35256407/43998692-f3d6dbba-9e3e-11e8-8667-8fda8ee81106.png)

**Comment by bradcornford** [comment]
Hi there,

I'm sorry your facing an issue, however can you please provide more information to allow me to debug this further.
