### ISSUE TITLE
2 Mapper::render() in 1 page view 

### ISSUE THREAD

**Issue by FadliFathulMubarok** [bradcornford/Googlmapper#289]
hello, 
can I use 2 mapper :: render () methods in 1 page view ? if I can do it, can you show me how to use it to me ?

**Comment by mohamedsabil83** [comment]
I try it too but it seems to render two blocks for each map. one filled with the map and leave another one empty.

**Comment by mohamedsabil83** [comment]
Gotcha. after many test I found how to render many map in same page.
let's say in controller `$maps = Maps::all()` and parse **$maps** to view. So, in blade view:
```
@foreach($maps as $map)
    <div style="width: 500px; height: 300px">
        {!! Mapper($map->column_name_for_latitude, $map->column_name_for_longitude)->render($loop->index) !!}
    </div>
@endforeach
```

**Comment by bradcornford** [comment]
Hi there,

You can create you map anywhere, then just ensure you call the render method with an index:

For example:

```
{!! Mapper::map(0, 0) !!}
```

```
{!! Mapper::render(0) !!}
```
