### ISSUE TITLE
View [mapper] not found.

### ISSUE THREAD

**Issue by m7vm7v** [bradcornford/Googlmapper#29]
Hi mate, 
What have you changed after v2.3.0 till v2.7.0 cus I have not changed any of the code and now I have 
View [mapper] not found. (View: C:\xampp\htdocs\resources\views\vendor\country.blade.php)
When I try the backup before the update everything is fine but..

**Comment by bradcornford** [comment]
Hi there,

Yes, a change where views are now publishable means that you will need to run a publish again to ensure your project gets the views. All other changes are backwards compatible:

```

php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"

```

**Comment by m7vm7v** [comment]
C:\xampp\htdocs\laravel>php artisan vendor:publish --provider="Cornford\\Googlmap
per\\MapperServiceProvider"
Nothing to publish for tag [].

**Comment by m7vm7v** [comment]
This solved the problem. Meaby it is good to add it in the Installation guide. 

php artisan vendor:publish --tag=googlmapper

**Comment by bradcornford** [comment]
How strange, both commands seem to work for me! Glad you got it working!

**Comment by tedmasterweb** [comment]
I had to use
`php artisan vendor:publish --provider='Cornford\Googlmapper\MapperServiceProvider'`
but I'm logged in to Homestead…

**Comment by korneliuskristianr** [comment]
Hi, if anyone still have problem. Do ```php artisan cache:clear``` and ```php artisan config:clear```.
Then run again ```php artisan vendor:publish --tag=googlmapper``` or ```php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"```
