### ISSUE TITLE
(maybe) Bugs about Google Maps JavaScript API warning: RetiredVersion

### ISSUE THREAD

**Issue by aufche** [bradcornford/Googlmapper#290]
Hi @bradcornford 

Your package is awesome!, thank you, but I was found bug (maybe)

Its about Google Maps JavaScript API warning: RetiredVersion

Google map appears perfect when the website is opened using a desktop / PC, but the map does not appear when the web is opened with a smartphone / mobile version

as example (open it on chrome desktop)
http://kontrakan123.com/properti/kos-harmonice-terima-kos-putri-muslim-kamar-mandi-dalam.html

then switch to mobile version by pressing F12 on your keyboard. As simple, open it on your smartphone. 

thank you

**Comment by olipiskandar** [comment]
harus diganti manual mas..
ada di :
"vendor/cornford/googlmapper/src/Cornford/Googlmapper/MapperBase.php"
cari : protected $version = '3.31';.
ganti aja jadi : protected $version = '3.33';
jalanin composer dumpautoload

**Comment by aufche** [comment]
Ok gan. Siap makasih ya

**Comment by bradcornford** [comment]
Hi there,

Yeah i had to drop the version back some time ago to get around a bug in the latest version. I've not bumped this to the current version and this should now be resolved.
