### ISSUE TITLE
Draw polygons, circles, rectangles 

### ISSUE THREAD

**Issue by Travel81** [bradcornford/Googlmapper#292]
I've just started to explore Googlmapper and I was wondering if there is a possibility to draw polygons/circles/rectangles and retrieve the coordinates of the shape draw on the map. 

Thanks in advance

**Comment by bradcornford** [comment]
Hi there,

Yes this is indeed possible, you will however need to add some hooks onto map events to achieve this.

You can use any of the shape commands within GooglMapper, with an option for them to be editable:

Polyline
Polygon
Rectangle
Circle
Here is a sample for a polygon:


Mapper::map(52.381128999999990000, 0.470085000000040000)->polygon([['latitude' => 53.381128999999990000, 'longitude' => -1.470085000000040000], ['latitude' => 52.381128999999990000, 'longitude' => 0.470085000000040000]], ['editable' => true]);

Also the following resource may be useful: https://developers.google.com/maps/documentation/javascript/shapes
