### ISSUE TITLE
Mapper not defined

### ISSUE THREAD

**Issue by arelidev** [bradcornford/Googlmapper#293]
Hey, I followed the steps in your readme but my IDE (PHPStorm) isn't recognizing the facade. Laravel is also telling me this:

`View [mapper] not found.  `

I'm sure it's just me, but any suggestions?

![screen shot 2018-08-22 at 1 39 53 pm](https://user-images.githubusercontent.com/13908167/44480428-2af2a500-a611-11e8-9584-5fe375c5a9a1.png)

**Comment by cloudwales** [comment]
Have you added it to the config/app.php Aliases and Provider
` Cornford\Googlmapper\MapperServiceProvider::class,`
`'Mapper' => Cornford\Googlmapper\Facades\MapperFacade::class,`

**Comment by arelidev** [comment]
Yes, I followed the instructions.

**Comment by bradcornford** [comment]
Hi there,

You can do the following:

```
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
```

**Comment by arelidev** [comment]
I found the solution to my problem here: https://github.com/bradcornford/Googlmapper/issues/29
I ran the following commands only:
1. `php artisan cache:clear`
2.` php artisan vendor:publish --tag=googlmapper`
