### ISSUE TITLE
use symbol circle for marker (example from readme does not seem to work)?

### ISSUE THREAD

**Issue by wivaku** [bradcornford/Googlmapper#296]
I would like to use a circle symbol as marker.
Similar to [Google's predefined symbols](https://developers.google.com/maps/documentation/javascript/symbols#predefined).

Second [Marker example](https://github.com/bradcornford/Googlmapper#marker)  in the Googlmapper readme shows exactly that:
```
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['symbol' => 'circle', 'scale' => 1000]);
```
When I try that:
```
        Mapper::map(53.3799491,-1.4706869, [
            'zoom' => 16,
            'center' => true, // true so the zoom will be used
            'marker' => false, // don't show marker for this location
        ]);

        Mapper::marker(
            53.381128999999990000, -1.470085000000040000, 
            ['symbol' => 'circle', 'scale' => 1000] // #1: incorrect, show default drop pin
            // ['icon' => 'https://storage.googleapis.com/support-kms-prod/SNP_2752125_en_v0'] // #2: correct
            // ['path' => 'M 0, 0 m -75, 0 a 75,75 0 1,0 150,0 a 75,75 0 1,0 -150,0', 'fillColor' => 'red', 'fillOpacity' => 0.7, 'scale' => 0.1, 'strokeColor' => 'red', 'strokeWeight' => 0.5 ] // #3: correct
        );

        return view('map');    
```

The code shows a couple of variations:
1. the example from the readme gives standard drop pin
2. icon as PNG url works
3. icon as SVG path works

How to use predefined symbols? And: how to customize color?

**Comment by bradcornford** [comment]
Hi there,

Try dropping the scale of the symbol, for example:

```
Mapper::marker(
            53.381128999999990000, -1.470085000000040000, 
            ['symbol' => 'circle', 'scale' => 10] 
        );
```
Some of the properties of symbol are currently not supported by the package though.

**Comment by wivaku** [comment]
This still gives the default drop pin.
The console shows: InvalidValueError: setIcon: not a string; and no url property; and no path property

**Comment by intrepidws** [comment]
@wivaku You need to capitalize the word CIRCLE for this to work.
