### ISSUE TITLE
Invalid API Key / Retired Version

### ISSUE THREAD

**Issue by jjesuscastro** [bradcornford/Googlmapper#297]
Been trying to add this to a Laravel project but been getting javascript errors saying I have an invalid key. Have tried to generate two different keys but no luck.

I also get retired version errors

**Comment by bradcornford** [comment]
I've bumped the version of the Google Maps to the latest, this should hopefully fix this issue.

**Comment by felixed** [comment]
I'm also getting this error:

Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
