### ISSUE TITLE
Limit Zoom In

### ISSUE THREAD

**Issue by jomayan** [bradcornford/Googlmapper#298]
Is there a way to limit the maximum Zoom In?

**Comment by bradcornford** [comment]
Yes, this would be possible, something like the below should work:

```
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'limitZoom(map);']);
```

```
function limitZoom(map) {
map.event.addListener(map, 'zoom_changed', function() {
     minZoomLevel = 1
     if (map.getZoom() < minZoomLevel) map.setZoom(minZoomLevel);
   });
}
```

**Comment by jomayan** [comment]
Thanks Brad. Will try this out.

**Comment by Johnny1210** [comment]
hello there,

I'm having a different issue with zoom in and out key.... 

Sometimes the key does exists sometimes not, I don't even know why this is happing...

![image](https://user-images.githubusercontent.com/36806969/47279945-bda1c700-d5f5-11e8-8c34-48c274433af8.png)

![image](https://user-images.githubusercontent.com/36806969/47279905-99de8100-d5f5-11e8-83d9-722b8e09c6ab.png)

Can you help me to show the switch

Thanks
