### ISSUE TITLE
Individual marker options are being overwritten by global options

### ISSUE THREAD

**Issue by akurtz** [bradcornford/Googlmapper#303]
I was having an issue where I had a default icon defined in global options -- but if I set a different icon on an individual marker, that wasn't picked up.

I believe `$this->options` (global options) should be the first parameter of `array_replace_recursive()`, to be overwritten by the individual marker parameters.  Swapping the two lines fixed my issue.

https://github.com/bradcornford/Googlmapper/blob/06428532c50d86cc3807c4c6e9fa042f2cd278b8/src/Cornford/Googlmapper/Models/Marker.php#L25-L29

**Comment by sparkcures** [comment]
Are there any updates on this? We are having similar issues and are hoping to use custom icons...

**Comment by bradcornford** [comment]
@akurtz I believe there was a reason for it being this way around. I believe the inheritance from global caused issues with the set parameters on construction of the marker. 

Out of interest, what is the code you are using?

**Comment by akurtz** [comment]
@bradcornford It's been a while, and this isn't a project I maintain regularly, but here's a quick snippet I found.  In `googlmapper.php` options file:

```
    'markers' => [

        /*
        |--------------------------------------------------------------------------
        | Marker Icon
        |--------------------------------------------------------------------------
        |
        | Display a custom icon for markers. (Link to an image)
        |
        */
        'icon' => '/img/PeachMapIcon.png',
```

Elsewhere...

```
        \Mapper::map($listing->latitude, $listing->longitude, [
            'markers' => [
                'icon' => [
                    'url' => $listing->is_banana_listing ? '/img/BananaMapIcon@2x.png' : '/img/PeachMapIcon@2x.png',
                    'size' => [29, 49],
                ],
            ],
            // Other options...
        ]);
```

As mentioned, works fine when I swap those two lines discussed above.

Thanks for your work on this package!

**Comment by bradcornford** [comment]
I've tested this a little more, and this seems to work exactly as intended.

The blow code will is overwritten by the map configuration. So the below, now becomes the default configuration for any new marker.

```\Mapper::map(1, 1, [
            'markers' => [
                'icon' => [
                    'url' => '/img/PeachMapIcon@2x.png',
                    'size' => [29, 49],
                ],
            ]
        ]);
```
The below code then overrides this default marker configuration for this singular marker:

```\Mapper::marker($listing->latitude, $listing->longitude, [
                'icon' => [
                    'url' => '/img/BananaMapIcon@2x.png',
                    'size' => [29, 49],
                ],
        ]);
```
