### ISSUE TITLE
Sometimes Zoom in switch not showing 

### ISSUE THREAD

**Issue by Johnny1210** [bradcornford/Googlmapper#306]
hello there,

I'm having a different issue with zoom in and out key....

Sometimes the key does exists sometimes not, I don't even know why this is happing...

![image](https://user-images.githubusercontent.com/36806969/47280105-94ce0180-d5f6-11e8-9eab-fc5e72d94516.png)

![image](https://user-images.githubusercontent.com/36806969/47280116-9ef00000-d5f6-11e8-8890-5bcbd130b981.png)

Can you help me to show the switch for all time

Thanks

**Comment by bradcornford** [comment]
Hi there,

You can control this from settings on the map itself:

```php

Mapper::map(1, 1, ['zoomControl' => true]);

```
