### ISSUE TITLE
How can I retrieve address from database?

### ISSUE THREAD

**Issue by thekubilay** [bradcornford/Googlmapper#309]
I m trying to retrieve addresses from DB and pass it to google map api. But I couldn't figure it out very well.

In the DB table I have, lots of address and I want to display all in google map with a marker. For this: I tried the code below. But having an error this:

My table column name is 'address'

> No results found for the location search.

     public function index()
    {
        $address = \DB::table('allestates')
            ->get();

        $notFound = [];

        foreach($address as $addr) {
            try {
                $location = Mapper::location($addr->address)->map();
                Mapper::marker($location->getLatitude(), $location->getLongitude());
            } catch (MapperSearchResultException $e) {
                $notFound[] = $addr->address;
            }
        }

        return view('welcome');
    }

and my view: 

    <div style="width: 500px; height: 500px">

        {!! Mapper::render() !!}

    </div>

**Comment by bradcornford** [comment]
Hi,

The above seems correct, check to make sure that you've allowed the location services on you API key.
