### ISSUE TITLE
Cannot find app/config/packages/cornford/googlmapper/config.php

### ISSUE THREAD

**Issue by CarlasHub** [bradcornford/Googlmapper#310]
Hi, I'm using Laravel homestead 5.4  and i'm following the steps mentioned here but i can't find the  "app/config/packages/cornford/googlmapper/config.php" file.  I looked up  on my project and there is no record of that. I guess i need someone to point me in the right direction, pls. 

![image](https://user-images.githubusercontent.com/34892979/48307121-531de000-e53e-11e8-80bc-c4dc853c316a.png)

**Comment by Lirux** [comment]
Did you run `php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper` to publish the config file?

**Comment by bradcornford** [comment]
Hi,

Did you manage to find your config file? After running the `vendor:publish` command?

**Comment by Mohsing511** [comment]
after vender published write **use mapper;** it will gona work
