### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ladis** [bradcornford/Googlmapper#317]
Hello,
I am using Laravel 5.7. I have 
I followed step by step the installation guide https://github.com/bradcornford/Googlmapper .
I am getting a blank page.
Thanks in advance for the help!

[doc2.docx](https://github.com/bradcornford/Googlmapper/files/2910930/doc2.docx)

**Comment by brassoy** [comment]
Hi!
I had the same problem, and solved it doing this

Once this operation completes, the next step is to add the service provider. Open app/config/app.php, and add a new item to the providers array.

**Cornford\Googlmapper\MapperServiceProvider::class,**
The next step is to introduce the facade. Open app/config/app.php, and add a new item to the aliases array.

**'Mapper'         => Cornford\Googlmapper\Facades\MapperFacade::class,**

**Comment by bradcornford** [comment]
Hi,

Has this solved your issue?
