### ISSUE TITLE
Google Maps JavaScript API error: InvalidKeyMapError

### ISSUE THREAD

**Issue by pratik617** [bradcornford/Googlmapper#318]
![dashboard template for bootstrap](https://user-images.githubusercontent.com/48198208/53714287-c774ea00-3e73-11e9-8a30-8263430aafaf.png)

Getting error in console:
Uncaught SyntaxError: Unexpected identifier
Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error

**Comment by bradcornford** [comment]
Hi,

The package does ship with an API key, for demo purposes only. If you need to use the map yourself, your best creating your own API key and using that instead.
