### ISSUE TITLE
Error, getting markers

### ISSUE THREAD

**Issue by gabrielius159** [bradcornford/Googlmapper#319]
When I am trying to get markers I get this error

`Uncaught TypeError: Cannot read property 'markers' of undefined` 
Line:
`var markers = maps[0].markers;`

**Comment by gabrielius159** [comment]
Ok, I fixed it. The problem was that maps wasn't loaded when I tried to put in an array. What worked for me was to add a delay:
`    setTimeout(function(){

            var markers = maps[0].markers;
  
        }, 100);`

**Comment by bradcornford** [comment]
Ah yes, the map is loaded on load, so isn't available right away. You can use the available event hooks such as `After Load` to ensure the map is loaded before running any custom script.
