### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by eskrano** [bradcornford/Googlmapper#32]
Hello! How i can choose dir for load my views? :+1:

**Comment by bradcornford** [comment]
Hi,

It will load the views once published from views/packages/cornford/goolmapper

Or is it something else you mean? Can you provide an example?

**Comment by dotfusion-min** [comment]
Hi Brad,
My {{ Mapper::render() }} simply returns a bunch of code like below. any idea why it's doing it?
Thanks!

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&region=GB&language=en-gb&key=*******&signed_in=false&libraries=places"></script> <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script> <div id="map-canvas-0" style="height: 100%; margin: 0; padding: 0;"></div> <script type="text/javascript"> var maps = []; function initialize_0() { var bounds = new google.maps.LatLngBounds(); var infowindow = new google.maps.InfoWindow(); var position = new google.maps.LatLng(53.381129, -1.470085); var mapOptions_0 = { center: position, mapTypeId: google.maps.MapTypeId.ROADMAP, disableDefaultUI: false , scrollwheel: true }; var map_0 = new google.maps.Map(document.getElementById('map-canvas-0'), mapOptions_0); map_0.setTilt(90); var markers = []; var markerPosition_0 = new google.maps.LatLng(53.381129, -1.470085); var marker_0 = new google.maps.Marker({ position: markerPosition_0, title: '', animation: '' , icon: '' }); bounds.extend(marker_0.position); marker_0.setMap(map_0); markers.push(marker_0); var markerCluster = new MarkerClusterer(map_0, markers); var listener = google.maps.event.addListener(map_0, "idle", function () { map_0.setZoom(8); google.maps.event.removeListener(listener); }); maps.push({ key: 0, markers: markers, map: map_0 }); } google.maps.event.addDomListener(window, 'load', initialize_0); </script>
