### ISSUE TITLE
Update cluster

### ISSUE THREAD

**Issue by gabrielius159** [bradcornford/Googlmapper#320]
Hi, I came with an issue using Googlmapper. I couldn't find a feature that would update cluster. I mean, if I hide a marker, cluster still shows that there is a marker. Am I missing something or there is no feature to do that?

**Comment by bradcornford** [comment]
Hi,

This isn't something offered by this package natively. However may be achieved using something like the following:

https://github.com/googlemaps/v3-utility-library/blob/master/markerclusterer/examples/advanced_example.html
