### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by cethak89** [bradcornford/Googlmapper#322]
Hello,

I have fresh API Key I tested it with JS. It works properly. But with Mapper i am always taking this error:

> 
file_get_contents(http://maps.googleapis.com/maps/api/geocode/json?address=Sheffield&amp;sensor=false): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden 
> 

I wrote my API key in right places. 

Do you have any idea about what I should do?

Thanks alot,

Hakan CETIN

**Comment by bradcornford** [comment]
Hi,

Have you made sure that you've allowed the API key to be used locally? This usually is one of the few issues. The other is that the API key has run into a limit placed.
