### ISSUE TITLE
No hint path defined for [googlmapper]. 

### ISSUE THREAD

**Issue by BriceHache** [bradcornford/Googlmapper#323]
Hi
I am using Laravel 5.6

I followed all the steps of the installations until the end. But when i use 
{!! Mapper::render() !!} in my view i have this error message.

No hint path defined for [googlmapper]. 

Please what can i do solve this issue ?

**Comment by bradcornford** [comment]
Hi, have you published the package provider?

`php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper`
