### ISSUE TITLE
v3.34 is retired

### ISSUE THREAD

**Issue by sparkcures** [bradcornford/Googlmapper#324]
Our maps using this package no longer load due to the following Google Maps error:

Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

There is no way to override 3.34 to 3.38. Any help/updates/thoughts on this would be awesome. Thanks!

**Comment by bradcornford** [comment]
I've published v2.34.0 to bump the version to latest Google maps js, 3.37.

**Comment by sparkcures** [comment]
This is great. Thanks for the quick response, Brad. We have flushed our composer cache and have even tried to explicitly use 2.34 but when we run composer update it says that version doesn't exist. Does it just take some time for that to update?

**Comment by bradcornford** [comment]
Yeah, its take around an hour for packagist to re-index. I've manually done this now and it should update as expected.

**Comment by sparkcures** [comment]
Perfect. Thanks for the quick help on this!
