### ISSUE TITLE
Blank page after following the instructions

### ISSUE THREAD

**Issue by aesdotjs** [bradcornford/Googlmapper#326]
Hello, i followed the instructions, config/app.php, config/googlmapper.php, and after battling with the new API quotas errors, I have the javascript inside the container I set in the blade template but the page is blank and the map isn't showing.
If you can help me thanks by advance

**Comment by aesdotjs** [comment]
Ok, so If use map::(xxx,xxx) it shows but not if i'm using Mapper::location('town name'); If I input a wrong town name i get an exception though maybe I'm not using location properly.

**Comment by bradcornford** [comment]
Hi there,

Can you try the following for location:

```
Mapper::location('Sheffield')->map(['zoom' => 15, 'center' => true]);
```

**Comment by aesdotjs** [comment]
Yeah I figured out and forgot to close the issue, i was missing the ->map after -> location, but since I needed to use the lat and long to draw a circle i've just stored it in a variable then used map on a second line.
Thanks for the help!
