### ISSUE TITLE
Map not working in mobile browsers

### ISSUE THREAD

**Issue by aesdotjs** [bradcornford/Googlmapper#328]
Hey,
The map is working more than fine on desktop browsers (local and prod) but I'm having an issue on Mobile browsers, the map is rendering at the right location but after 1-2 seconds it turns grey with an error message like "check the console".
Do you have any clue what that can be?

Controller : 
`Mapper::map($location->getLatitude(), $location->getLongitude())
            ->circle([['latitude' => $location->getLatitude(), 'longitude' => $location->getLongitude()]], 
            ['strokeColor' => '#3490dc', 'strokeOpacity' => 0.8, 'strokeWeight' => 2, 'fillColor' => '#3490dc', 'radius' => $plumber->zone_intervention*1000]);`

View : 
`<div class="col-md-10" style="height:90vh">
                        {!! Mapper::render() !!}
                    </div>`

**Comment by bradcornford** [comment]
Hey @aesdotjs, Could you use a chrome mobile browser and use the inbuilt console to view the issue? 

All of the code you provided looks correct. The only thing I could think of being an issue would be that the API key doesn't allow mobile clients.

**Comment by bradcornford** [comment]
Here's a link to the Android remote debugging function: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
