### ISSUE TITLE
How to use multiple marker on google

### ISSUE THREAD

**Issue by kashifmit** [bradcornford/Googlmapper#329]
@bradcornford Hello,
I want to use multiple location marker on the map, how can i do this?
currently 
i am using ```$mapper = Mapper::map(33.73079, -79.80004);``` how can i use multiple lat, long in this function, so that it can show multiple location marker on map, also please let me know if i want to show any tooltip on the marker how i can show on it?

**Comment by bradcornford** [comment]
@kashifmit Please see the ReadMe.

The following should work:

```php
$mapper = Mapper::map(33.73079, -79.80004);
Mapper::informationWindow(33.73069, -79.81004, 'Content');
Mapper::informationWindow(33.73089, -79.82004, 'Content');
Mapper::informationWindow(33.73099, -79.83004, 'Content');
```

**Comment by kashifmit** [comment]
@bradcornford Thanks for your help.
