### ISSUE TITLE
Call to undefined method MapperServiceP rovider::mergeConfigFrom() during publish

### ISSUE THREAD

**Issue by alfredmocon100** [bradcornford/Googlmapper#33]
Hi, 

Would like to try it out but I'm getting this error:

Laravel 4.1.2
Wamp Server 2.5
Windows 8 (64 Bit)

Error:
C:\wamp\www\ninestars>php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Cornford\\Googlmapper\\MapperServiceP
rovider::mergeConfigFrom()","file":"C:\\wamp\\www\\ninestars\\vendor\\cornford\\googlmapper\\src\\Cornford\\Googlmapper\\MapperServiceProvider.php","l
ine":41}}

Thanks.

**Comment by bradcornford** [comment]
Hi,

Version 1.* supports Laravel 4.*, see this: https://github.com/bradcornford/Googlmapper/tree/v1.5.0

**Comment by bradcornford** [comment]
Has the above fixed your issue?
