### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by rikiless** [bradcornford/Googlmapper#331]
> cornford/googlmapper v2.34.0 requires illuminate/view 5.*
> cornford/googlmapper v2.33.0 requires illuminate/support 5.*

**Comment by felipesmendes** [comment]
@rikiless did you solve the problem?
 its seems the package is not maintained.

**Comment by rikiless** [comment]
I just edited composer.json to require illuminate/view 6.* & illuminate/support 6.* in my fork. It seems it's working for now.

**Comment by felipesmendes** [comment]
@rikiless Could you send me step by step how to do this? 

> I just edited composer.json to require illuminate/view 6.* & illuminate/support 6.* in my fork

**Comment by dircm** [comment]
I can cofirm by forking and changing the composer.json "require" to 

```
"require": {
        "illuminate/view": "6.*",
        "illuminate/support": "6.*"
    },
```
Is working in my Laravel v6.0.3 projects.

**Comment by UXandre** [comment]
@dircm can you please elaborate on how I can install the package I forked and edited? Tried to fork the repo, edit the versions, and uploaded to Packgist. But it said the package is owned and maintained by the author. Would appreciate a quick pointer! Thank you!

**Comment by bradcornford** [comment]
I've been away with a family bereavement so haven't had time to merge this until now.

I've merged a PR for this now, and versioned it as current version v2.35.0. I haven't had time to try version Laravel 6 yet however.

**Comment by dircm** [comment]
> @dircm can you please elaborate on how I can install the package I forked and edited? Tried to fork the repo, edit the versions, and uploaded to Packgist. But it said the package is owned and maintained by the author. Would appreciate a quick pointer! Thank you!

Hi @UXandre have a look at https://getcomposer.org/doc/05-repositories.md#vcs

The basics of what I did were: 
1. Fork this repo.
2. Make the changes (bug fixes etc) to the code on your own fork.
3. Add the require to your project composer.json require (here is mine)
`"dircm/googlmapper": "master",`
4. Add the VCS repository to your project composer.json (here is mine).  Note the VCS repository will always be searched first over other repos.
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dircm/Googlmapper.git"
        }
    ]
```
5. If your forked repo is private (like mine is) you will need to generate a personal token to allow your project to download the package.  See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

6. run composer update

**Comment by UXandre** [comment]
> > @dircm can you please elaborate on how I can install the package I forked and edited? Tried to fork the repo, edit the versions, and uploaded to Packgist. But it said the package is owned and maintained by the author. Would appreciate a quick pointer! Thank you!
> 
> Hi @UXandre have a look at https://getcomposer.org/doc/05-repositories.md#vcs
> 
> The basics of what I did were:
> 
> 1. Fork this repo.
> 2. Make the changes (bug fixes etc) to the code on your own fork.
> 3. Add the require to your project composer.json require (here is mine)
>    `"dircm/googlmapper": "master",`
> 4. Add the VCS repository to your project composer.json (here is mine).  Note the VCS repository will always be searched first over other repos.
> 
> ```
> "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/dircm/Googlmapper.git"
>         }
>     ]
> ```
> 
> 1. If your forked repo is private (like mine is) you will need to generate a personal token to allow your project to download the package.  See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
> 2. run composer update

@dircm thanks so much for this, Tom. I am away pitching around our startup but will give a go on Friday. Really appreciate the detailed explanation!

**Comment by dircm** [comment]
> > > @dircm can you please elaborate on how I can install the package I forked and edited? Tried to fork the repo, edit the versions, and uploaded to Packgist. But it said the package is owned and maintained by the author. Would appreciate a quick pointer! Thank you!
> > 
> > 
> > Hi @UXandre have a look at https://getcomposer.org/doc/05-repositories.md#vcs
> > The basics of what I did were:
> > 
> > 1. Fork this repo.
> > 2. Make the changes (bug fixes etc) to the code on your own fork.
> > 3. Add the require to your project composer.json require (here is mine)
> >    `"dircm/googlmapper": "master",`
> > 4. Add the VCS repository to your project composer.json (here is mine).  Note the VCS repository will always be searched first over other repos.
> > 
> > ```
> > "repositories": [
> >         {
> >             "type": "vcs",
> >             "url": "https://github.com/dircm/Googlmapper.git"
> >         }
> >     ]
> > ```
> > 
> > 
> > 
> > 1. If your forked repo is private (like mine is) you will need to generate a personal token to allow your project to download the package.  See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
> > 2. run composer update
> 
> @dircm thanks so much for this, Tom. I am away pitching around our startup but will give a go on Friday. Really appreciate the detailed explanation!

@UXandre I dont think you are forking this repo correctly.  Have a look at 
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

**Comment by dircm** [comment]
Hi @rikiless this issue should be closed now.  All working with new release.

**Comment by rikiless** [comment]
@dircm @felipesmendes I did it the same way 🙂 Simple, fast and temporary. Fork and update package by yourself. Then in composer.json required package changed to dev-master:

```
"cornford/googlmapper": "dev-master",
```

and added mine VCS repo:

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rikiless/Googlmapper"
        }
    ],
```

But now it's not needed anymore. Thanks for updating library.
