### ISSUE TITLE
multiple marker not getting load on ajax call

### ISSUE THREAD

**Issue by kashifmit** [bradcornford/Googlmapper#332]
@bradcornford I am having an issue with ajax. When ever i get multiple lat long map is not getting update.
I am using the following code

```
$.each(data, function (index, value) {
   maps[0].map.setCenter({lat: parseFloat(value.Latitude), lng: parseFloat(value.Longitude)});
});

```
In response i am sending following array
```
[
{Latitude: "34.72217", Longitude: "81.13068" },
{Latitude: "35.13399", Longitude: "-80.964" },
{Latitude: "35.13399", Longitude: "-80.964" },
{Latitude: "34.73423", Longitude: "-82.37597" }
]
```
I am using version ```2.*```
Thanks for your help in advance.... :)

**Comment by bradcornford** [comment]
My suggestion would be to check the dataset in value is what you expect. Also that maps[0] is defined. As far as i can tell it looks correct.

**Comment by kashifmit** [comment]
@bradcornford when i send an ajax call after getting result i check the console it gives me the following error
```Uncaught TypeError: Cannot read property 'map' of undefined```
maps[0] is undefined, can you please help me how can i use it?

**Comment by kashifmit** [comment]
@bradcornford when i did ```console.log(maps)``` it return me empty array i.e ```[]```
