### ISSUE TITLE
how can i use function using Mapper::map() in laravel

### ISSUE THREAD

**Issue by Mohsing511** [bradcornford/Googlmapper#334]
i wants to get lat long values as well as i need  to use autocomplete section using javascript function or any other way my code is 
Mapper::map(0, 0)->marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP'] , 'draggable' => true, '**Function**' => Name or whatever ]);
i just wants to integrate searchbox with map to add marker and get values to save in database please reply as fast as possible 
Thanks in advance

**Comment by bradcornford** [comment]
See: https://github.com/bradcornford/Googlmapper/issues/273 https://github.com/bradcornford/Googlmapper/issues/225 
https://github.com/bradcornford/Googlmapper/issues/175
