### ISSUE TITLE
zoom-event

### ISSUE THREAD

**Issue by andersespedalen** [bradcornford/Googlmapper#336]
Isn't there an event for zoom changed?
I'm trying to update a form using lat,lng and zoom level by having the user drag a marker and zooming to the preferred level. Im only able to fetch the z by dragging the marker, so if the last action of the user is to zoom, then this won't be captured.

**Comment by andersespedalen** [comment]
Also, how do I canpture the event data?

`'eventDragEnd' => 'dragCallback(eventData)'`

**Comment by bradcornford** [comment]
Hi there,

Yes a zoom event is possible see: https://developers.google.com/maps/documentation/javascript/events, this could be achieved using something like the following using the eventAfterLoad:

```
google.maps.event.addListenerOnce(map_0, "zoom_changed", function() {
    alert('ZOOM');
});
```

As for the marker events:

```
'eventDragEnd' => 'dragCallback(event)'
```

**Comment by andersespedalen** [comment]
Ended up using the native google.maps impementation instead of googlemapper.
Saving this for refactor later. Thanks!
