### ISSUE TITLE
markerclusterer.js not found

### ISSUE THREAD

**Issue by cornerstonesoftware** [bradcornford/Googlmapper#337]
Thanks for this great package! I have integrated googlmapper successfully. But i noticed today that the mapsclusterer is not working anymore.
The console shows:
GET http://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js net::ERR_ABORTED 404 (Not Found)

How can this be solved?

**Comment by celcius-jochen** [comment]
See https://github.com/bradcornford/Googlmapper/pull/335

**Comment by cornerstonesoftware** [comment]
Thank you celcius-jochen for your help!
After updating to the latest version this did the trick:
php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper --force
