### ISSUE TITLE
Argument 2 passed to Cornford\Googlmapper\MapperBase::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by dextersiah** [bradcornford/Googlmapper#339]
Hello, 
I am using Laravel 6.5.2.
I have followed all the instructions in the guide but I'm getting an error as stated in the title.

Here are the snippets inside my controller method and view.

```
<!--Controller method-->
public function show($id)
{
        $lat = Report::where('id',$id)->value('latitude');
        $lng = Report::where('id',$id)->value('longitude');


        Mapper::map($lng,$lat);
        

        $report = Report::find($id);

        return view('report',compact('report'));
}

<!--Blade View-->
<div class="column" style="height:500px;width:100vw;">
    {!! Mapper::render() !!}
</div>
```

**Comment by bradcornford** [comment]
That's a strange one, it map method does take an array of options as its third argument, however by default its a blank array.

I'll take a look at this, to see if i can replicate it. What version of PHP are you running?

This should fix your issue in the meantime:

```php

Mapper::map($lng,$lat, ['center' => true]);

```

**Comment by dextersiah** [comment]
I'm using PHP 7.2.9 and thanks that line of code worked

**Comment by bradcornford** [comment]
I've trued this locally on 7.2.24 and it works fine, and cant get version 7.2.9 easily without building from source, so I'm going to close this for now.

**Comment by Dictator1999** [comment]
@bradcornford 
I got the same error and did same thing that you are followed. But still got the error.

php version: 7.3.12-1

Laravel version:  6.13.1

**Comment by Dictator1999** [comment]
I got the solution because of cache.

just run
`php artisan config:clear`

or

`php artisan config:cache`
