### ISSUE TITLE
Recent issues - markers and clustering

### ISSUE THREAD

**Issue by kristianharmer** [bradcornford/Googlmapper#34]
Hey, I've been having issues recently with this Mapper pacakage.

Firstly, clustering stopped working with my initial implementation, although it had worked fine for weeks until I ran a composer update.

Having updated (cannot remember last version but only 2 months ago) I was gettings errors so tried your examples with info windows and markers. I seem to always get the following JS error no matter what!

    ReferenceError: markers_ is not defined
    if (markers_.length < this.minClusterSize_) {

Any ideas?

Great package by the way, I was initally up and running in 30 minutes.

**Comment by bradcornford** [comment]
Hi,

Have you run a publish, as the templates have been made accessible for modifications?

```
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
```

**Comment by bradcornford** [comment]
I believe you will have to access the makers via the maps array:

```js

maps[0].makers;

```

**Comment by kristianharmer** [comment]
Hey, thanks for the response :) I did run that publishing command.

Here is what I have in my controller
```
            $courseMarkers = $region->courses()->get();

            Mapper::map($region->latitude,$region->longitude, ['zoom' => $region->map_zoom, 'center' => true, 'scrollWheelZoom' => false, 'type' => 'ROADMAP']);

            $courseMarkers->each(function($courseMarker)
            {
                if( $courseMarker->latitude != '' && $courseMarker->longitude != '' ) {
                    $content = '<a href="/golf-course/'.$courseMarker->slug.'">'.addslashes($courseMarker->name).'</a>';
                    Mapper::informationWindow($courseMarker->latitude, $courseMarker->longitude, $content);
                }
            });


        return view('region', compact('region', 'courses', 'courseFilter'));
```
...and this in my view
```
						<div id="map">
							{!! Mapper::render() !!}
						</div>
```
Also, I have now tested every release of version 2 and still the same problem so must be my end!

**Comment by bradcornford** [comment]
What you have done appears to be correct. What error are you getting? Is it from Google Maps? Or custom JS?

**Comment by bradcornford** [comment]
Actually looking at it, the library used for marker clusters is broken currently, see: https://github.com/googlemaps/js-marker-clusterer/issues/37

There is currently a pull request to fix it:
https://github.com/googlemaps/js-marker-clusterer/pull/39

**Comment by kristianharmer** [comment]
Ah that would explain it! Thanks for confirming that. Will hold tight on a fix from that repo :)

Thanks for your help all the same...

**Comment by bradcornford** [comment]
For now, you could change "mapper.blade.php" line 5 to:

```html
<script type="text/javascript" src="https://raw.githubusercontent.com/bradcornford/js-marker-clusterer/gh-pages/src/markerclusterer.js"></script>

```
