### ISSUE TITLE
example of cluster?

### ISSUE THREAD

**Issue by wivaku** [bradcornford/Googlmapper#343]
Having trouble to get cluster working. Do you have a complete example?

Tried (based on the example on homepage):
[btw documentation mentions both `cluster` and `clusters.`, should I use both?]
```
        Mapper::map(53.381128999999990000, -1.470085000000040000, 
        [
            'zoom' => 10, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 
            'clusters' => ['size' => 3, 'center' => true, 'zoom' => 20]
        ]);

        Mapper::marker(53.381128999999990000, -1.470085000000040000);
        Mapper::marker(53.181128999999990000, -1.570085000000040000);
        Mapper::marker(53.481128999999990000, -1.370085000000040000);
        Mapper::marker(53.281128999999990000, -1.670085000000040000);
```

The above does not cluster the 4 markers.

**Comment by bradcornford** [comment]
Hi there,

Cluster defines if clusters should be used. Clusters defines configuration for the cluster.

This should work:

```
Mapper::map(53.381128999999990000, -1.470085000000040000, 
        [
            'zoom' => 10,
            'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 
            'cluster' => true,
            'clusters' => ['size' => 3, 'center' => true, 'zoom' => 20]
        ]);

        Mapper::marker(53.381128999999990000, -1.470085000000040000);
        Mapper::marker(53.181128999999990000, -1.570085000000040000);
        Mapper::marker(53.481128999999990000, -1.370085000000040000);
        Mapper::marker(53.281128999999990000, -1.670085000000040000);
```

**Comment by wivaku** [comment]
Thanks for the clarification. I did try with `'cluster' => true` (i.e. your complete example) and same result: no clustering. Suggestions?

**Comment by bradcornford** [comment]
The following should work:

```

Mapper::map(53.0, -1.0, 
        [
           'zoom' => 20,
            'cluster' => true
        ]);

        Mapper::marker(53.1, -1.4);
        Mapper::marker(53.2, -1.5);
        Mapper::marker(53.3, -1.7);
        Mapper::marker(53.4, -1.1);
        Mapper::marker(53.5, -1.5);
        Mapper::marker(53.6, -1.2);
        Mapper::marker(53.7, -1.6);
        Mapper::marker(53.8, -1.9);
        Mapper::marker(53.9, -1.3);

```

Can you check your console, are there any errors?

**Comment by wivaku** [comment]
Ah, I do get an error message. Not sure why I did not check before.
```
GET http://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js net::ERR_ABORTED 404 (Not Found)
Uncaught ReferenceError: MarkerClusterer is not defined
    at initialize_0 (places:327)
```
Which indeed does not exist at that location.
Maybe use this one instead?
```
https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer.js
```

**Comment by bradcornford** [comment]
Ah, looks like they are migrating the project to another repo. Yeah, moving to a CDN version would suffice. Or: https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclusterer/src/markerclusterer.js

If you wouldn't mind creating a PR for this that would be great!

**Comment by wivaku** [comment]
Never done that. More than happy to give it a shot.

**Comment by wivaku** [comment]
BTW. The original Google github page redirects to this one:
https://github.com/googlearchive/js-marker-clusterer
Which mentions: "_Please note: This repository is kept for historical purpose only - the current version of marker clusterer is available as part of the v3-utility-library repository._"

https://github.com/googlemaps/v3-utility-library

which leads to the latest markerclusterer.js:
https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/packages/markerclusterer/src/markerclusterer.js

**Comment by wivaku** [comment]
When looking into this some more I noticed there was a previous PR merged already (https://github.com/bradcornford/Googlmapper/commit/3d180bfed327e5d218fc09ca3da5d561e6fbf30a), which uses the valid archive location (it is not the latest version, but it a valid archive of the one that was used previously).

Turns out I had the [same issue as the other person](https://github.com/bradcornford/Googlmapper/pull/335), which was indeed solved by:
```
php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper --force
```
Here is a fully working example:
```
        Mapper::map(53.381128999999990000, -1.470085000000040000, 
        [
            'zoom' => 8,
            'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 
            'cluster' => true,
            'clusters' => ['size' => 2, 'center' => true, 'zoom' => 20]
        ]);

        Mapper::marker(53.581128999999990000, -1.270085000000040000);
        Mapper::marker(53.181128999999990000, -1.570085000000040000);
        Mapper::marker(53.481128999999990000, -1.370085000000040000);
        Mapper::marker(53.281128999999990000, -1.670085000000040000);

        return view('map');
```

**Note**: the latest version of `markerclusterer.js` is not compatible (e.g. using githack so it is served as JavaScript: https://raw.githack.com/googlemaps/v3-utility-library/master/packages/markerclusterer/src/markerclusterer.js)

I get:
```
Uncaught SyntaxError: Unexpected token 'export'        markerclusterer.js:1271
Uncaught ReferenceError: MarkerClusterer is not defined       cluster:287
    at initialize_0 (cluster:287)
```
