### ISSUE TITLE
interact with map using Javascript after initialization?

### ISSUE THREAD

**Issue by wivaku** [bradcornford/Googlmapper#344]
How can I interact with the map after it has been initialized?
E.g. to change the bounds.
I can add JavaScript, but need to wait for / check that the map is initialized.

**Comment by bradcornford** [comment]
Hi there,

You can do something like the following:

```
Mapper::map(42.5,41.8, ['center' => true, 'eventAfterLoad' => 'mapEvent(maps[0].map);', 'markers' => ['title' => 'My Location', 'animation' => 'DROP']]);

function mapEvent(map)
{
    alert(1);
}
```

**Comment by wivaku** [comment]
Excellent, exactly what I was looking for.
