### ISSUE TITLE
Argument 2 passed to Cornford\Googlmapper\MapperBase::__construct() must be of the type array, null given, called in D:\Laravel\ZooManager\vendor\cornford\googlmapper\src\Cornford\Googlmapper\MapperServiceProvider.php on line 47 

### ISSUE THREAD

**Issue by JanosFalke** [bradcornford/Googlmapper#345]
I don't understand how to fix this error. 
"Argument 2 passed to Cornford\Googlmapper\MapperBase::__construct() must be of the type array, null given, called in D:\Laravel\ZooManager\vendor\cornford\googlmapper\src\Cornford\Googlmapper\MapperServiceProvider.php on line 47"
![Unbenannt](https://user-images.githubusercontent.com/33756729/72449066-5a7ef000-37b8-11ea-86eb-18140a3833dd.PNG)

**---Controller---**
use Mapper; 

public function index()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);
        return view('home');
    }

**---View---**
<div style="width: 500px; height: 500px;">
           {!! Mapper::render() !!}
 </div>

Already tried to set _Mapper::map($lng,$lat, ['center' => true]);
Also checked config/app.php 

Thanks a lot for your help guys ! 

___________________
Laravel version is 6.11.0

**Comment by Dictator1999** [comment]
Have you fixed this problem?

**Comment by bradcornford** [comment]
Hi there,

This appears to be a caching issue, try running:

```
php artisan config:clear
```
