### ISSUE TITLE
How to have user current latitude and longitude before the page even load

### ISSUE THREAD

**Issue by rickyexe** [bradcornford/Googlmapper#347]
So i'm trying to use haversine formula to show marker based on distance. But it needs current user's latitude and longitude. That's why i need it in the controller before the page even load. Is there any way to do that ? Thank You

**Comment by bradcornford** [comment]
Hi there,

No, there would be no way to achieve this in a controller as the users location is only accessible by the browser. Another option would be to load the map with the locate option enabled, with an after event set in which you could get the users location, and callback to a controller via an Ajax request.

**Comment by rickyexe** [comment]
Hi, thank you for the answesr
So i already get the array of latitude and longitude in my ajax response
how can enter that value to the maps? or even better to replace the already existing marker with a new lat and lng value?
i already try this and it didn't work
for (i = 0; i < data.length; i++) {
                        let marker = new google.maps.Marker({
                            position: new google.maps.LatLng(data[i].latitude, data[i].longitude),
                        });
                        marker.setMap(map_0);
                        markers.push(marker);
                    }
                    initialize_0()

Thank you

**Comment by bradcornford** [comment]
You should be able to piece together parts from the following:

https://github.com/bradcornford/Googlmapper/issues/245
https://github.com/bradcornford/Googlmapper/issues/201
https://github.com/bradcornford/Googlmapper/issues/91

**Comment by rickyexe** [comment]
I already read it and it still doesn't show up
 ```
$.ajax({
                url:'/updatemarker/' + lat + '/' + lng,
                type:'GET',
                success:function(data)
                {
                    for (i = 0; i < 5; i++) {

                        var myLatLng = {lat:data[i].latitude, lng: data[i].longitude};

                        var marker = new google.maps.Marker({
                            position: myLatLng,
                            setMap: map,
                            title: 'Staff'
                        });
                    }
                    initialize_0()
                }
            });

```
Am i missing something?

**Comment by bradcornford** [comment]
I think you want to be point at setMap to `maps[0].map`.

**Comment by rickyexe** [comment]
It still doesn't work. what i do now is i make a new map variable and put the marker one by one by using map-canvas-0 . i don't know whether my for loop is wrong or the maps[0].maps is not global.
Anyway thank you for your help! Great tool for years :)

**Comment by bradcornford** [comment]
Could you provide me with the controller code and the map code? You shouldn't need to call `initialize_0()` again
