### ISSUE TITLE
Retired Version of Maps API

### ISSUE THREAD

**Issue by rickyexe** [bradcornford/Googlmapper#348]
How to manually change the version of the link api?
it's 3.37 now
`<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.37&region=ID&language=id&key=key&libraries=places"></script>`

but i need to change it to weekly because i got this error and the document suggest to change the 3.37 to weekly or the maps won't even load
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

Thank You

**Comment by AlexFullComms** [comment]
I've got this very same issue...

**Comment by bradcornford** [comment]
Hi there,

I've now bumped the project to use the latest version of the API, sorry for the long wait, I've been on holiday. This should now be fixed in current version 3.1.0, 2.36.0, 1.28.0.

**Comment by AlexFullComms** [comment]
Ah thanks !!!

Everyone deserves a holiday !

**Comment by rickyexe** [comment]
Great!
Just curious, i tried to resolve this issue by modifying the javascript.blade.php to weekly
is it an okay approach?

**Comment by bradcornford** [comment]
@rickyexe Yeah that's a valid approach, although i did move away from the weekly to a set version due to breaking changes being introduced. A better approach would probably be to use the `quarterly` version.

**Comment by rickyexe** [comment]
Okay great! The issue is resolve then
Thank You
