### ISSUE TITLE
How to correctly set the anchor/origin of a custom SVG marker?

### ISSUE THREAD

**Issue by jochensengier** [bradcornford/Googlmapper#349]
I'm using a custom SVG marker icon, but the icon starts at the bottom of the default marker.
I've already tried setting the size, anchor and origin property of the icon with no luck.

Example (with dummy data):

```
Mapper::informationWindow('latitude', 'longitude', 'content', [
	'title' 	=> 'title',
	'icon'      => [
		'path'         => 'M10.5,0C4.7,0,0,4.7,0,10.5c0,10.2,9.8,19,10.2,19.4c0.1,0.1,0.2,0.1,0.3,0.1s0.2,0,0.3-0.1C11.2,29.5,21,20.7,21,10.5 C21,4.7,16.3,0,10.5,0z M10.5,5c3,0,5.5,2.5,5.5,5.5S13.5,16,10.5,16S5,13.5,5,10.5S7.5,5,10.5,5z',
		'fillColor'    => '#dd716c',
		'fillOpacity'  => 1,
		'strokeWeight' => 0,
		// 'anchor' => [0, 0],
		// 'origin' => [0, 0],
		// 'size'   => [21, 30],
	],
	// 'anchor' => [0, 0],
	// 'origin' => [0, 0],
	// 'size'   => [21, 30],
	'autoClose' => true,
]);
```

![correct](https://user-images.githubusercontent.com/10118729/75458048-84adfb00-597d-11ea-9bb8-69d24013cf44.png)
![wrong](https://user-images.githubusercontent.com/10118729/75458052-85df2800-597d-11ea-993b-84061bc7facc.png)

**Comment by bradcornford** [comment]
Hi there, 

The `anchor` and `origin` variables haven't been added to the library as of yet, however the size option should work with a url image, such as the following:

```
Mapper::informationWindow('latitude', 'longitude', 'content', [
	'title' 	=> 'title',
	'icon'      => [
		'url'         => 'example.jpg',
		'size'    => [1, 1]
	],
	'autoClose' => true,
]);
```

Feel free to raise a PR to add them!

**Comment by bradcornford** [comment]
I've now merged the develop branch and versioned it into master.

**Comment by jochensengier** [comment]
Thanks! Works like a charm!
