### ISSUE TITLE
Laravel 7.0

### ISSUE THREAD

**Issue by jochensengier** [bradcornford/Googlmapper#351]
Would it be possible to update this package to support the newly released Laravel 7?

Thanks!

**Comment by bradcornford** [comment]
Sure, i'd have to check over the docs for any changes, and test it locally, so give me a little time.

**Comment by bradcornford** [comment]
Okay, Laravel 7 support should now integrated into version 3.2.0.

**Comment by jochensengier** [comment]
Thank you 🥳
