### ISSUE TITLE
labelClass on marker

### ISSUE THREAD

**Issue by jesseqli** [bradcornford/Googlmapper#356]
I'm trying to add a custom CSS class to my marker labels but it's not showing up. Any advice on what I'm doing wrong? Thanks in advance!

`Mapper::marker($latitude, $longitude, ['title' => 'Some Title', 'label' => 'Some Label', 'labelClass' => 'my-custom-label-class']);`

**Comment by bradcornford** [comment]
Hi there,

You can't add a css class to the label easily, but you can do the following:

```php
Mapper::marker($latitude, $longitude, ['title' => 'Some Title', 'label' => ['text' => 'Some Label', 'color' => 'blue', 'fontFamily' => 'Ariel', 'fontSize' => '12px', fontWeight => 'bold']]);
```

See here for more infoL https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerLabel

**Comment by jesseqli** [comment]
Got it! Thank you so much for the quick reply.
