### ISSUE TITLE
Can't drag / move map around

### ISSUE THREAD

**Issue by CloseToDie** [bradcornford/Googlmapper#359]
Hello.

First of all, I would like to say that I really like your package so far. 

This is the first time I am using your package, so I am not sure if this is even possible with your package or not, but I have followed your start guide and installed the package in the latest laravel 7. When the map shows, everything is working except the drag / move feature. I get this hand grap icon, but clicking it is not closing the hand, and I cant move around in the map. 

Can you please help me, if there is something else I should do?

**Comment by bradcornford** [comment]
Hi there,

Are you seeing any console errors? It should work out of the box. If all else fails, try dropping back a version, and report back.

**Comment by CloseToDie** [comment]
I am sorry, but I ended up deleting the project. What I remember, there were no console errors. I followed the setup guide from you. Using laravel 7. I just used the google api in javascript, and it all worked fine there. It might have been an isolated issue. Thx again :)

**Comment by StyxOfDynamite** [comment]
Noticing the same issue, nothing logged to the console. but no interactivity on click / drag. UI controls for zoom work

**Comment by StyxOfDynamite** [comment]
Needed to enable 
```
'gestureHandling' => 'auto',
```

**Comment by bradcornford** [comment]
Ah, that was added in a recent update. However it should be backwards compatible. Let me investigate.

**Comment by bradcornford** [comment]
Okay, the default was `none`, where as it should have been `auto`. This has been fixed in current version 3.3.1.
