### ISSUE TITLE
view problem

### ISSUE THREAD

**Issue by dotfusion-min** [bradcornford/Googlmapper#36]
hi brad,

I use {{ $map }} in my blade view but it failed to show a map, instead a bunch of code shows as text. what is a proper way to show your map in view?

thank you!

**Comment by bradcornford** [comment]
Hi,

You need to use for Laravel 5.*:

```
{!! Mapper::render() !!}

```

You need to use for Laravel 4.*:

```
{{ Mapper::render() }}

```

**Comment by dotfusion-min** [comment]
Hi Brad,

Thank you!! :+1:  After reading your answer, I found it in documentation. 


Displaying Unescaped Data

By default, Blade {{ }} statements are automatically sent through PHP's htmlentities function to prevent XSS attacks. If you do not want your data to be escaped, you may use the following syntax:

Hello, {!! $name !!}.

from https://laravel.com/docs/5.1/blade

**Comment by bradcornford** [comment]
Great, glad things worked out for you.
