### ISSUE TITLE
It shows only Gray Map

### ISSUE THREAD

**Issue by jeundekie** [bradcornford/Googlmapper#361]
I am using the latest package for Googlmapper but once I load the map it only shows gray box and the marker.

Code for the Controller

use Mapper;

class MapController extends Controller
{
    public function mapper()
    {
        Mapper:: map(
        151.23064,
        -33.91722,
        [
            'draggable' => true,
            'marker' => true,
            'eventAfterLoad' =>
            'circleListener(maps[0].shapes[0].circle_0);'
        ]
        );
        return view('map');
    }
}

In the Blade file
  <style>
      /* Set the size of the div element that contains the map */
      #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>
  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    
    <div id="map">{!! Mapper::render() !!}</div>

I already saw related issues about this it says it was 
![gray](https://user-images.githubusercontent.com/67977645/86832645-04399c80-c0cb-11ea-8284-25bbaf1acf86.PNG)
fixed in the 3.*. I hope you can help me. I'm really new to this any suggestion will help. Thank you very much

**Comment by jeundekie** [comment]
Is this available in laravel 7? this package? Thank you

**Comment by bradcornford** [comment]
Hi,

Yes this package is available in Laravel 7.

**Comment by bradcornford** [comment]
That map looks correct, are you zoomed in too far? Are you seeing any console errors?
