### ISSUE TITLE
Facilitate integration (Level of events) with livewire.

### ISSUE THREAD

**Issue by gabeta** [bradcornford/Googlmapper#362]
I use laravel livewire I would like to know if there is a possibility of directly using methods like callback when I graft an event on a marker.
`public function mount() 
{
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventClick' => 'myDraggableMethod']);
}

public function myDraggableMethod(event) 
{
}`

**Comment by bradcornford** [comment]
Hi,

Yes, you should be able to create markers dynamically, however you may need to load the data from an endpoint itself.
