### ISSUE TITLE
Offset the label from the marker ?

### ISSUE THREAD

**Issue by t-prod** [bradcornford/Googlmapper#365]
Hi,

Thanks for your package, do you know how can we offset the label from the marker ?
I'm using informationWindow like this but it doesn't works :
```
Mapper::informationWindow(
                $client->latitude,
                $client->longitude,
                $html,
                [
                    'maxWidth'=> 350,
                    'autoClose' => true,
                    'label' => PHP_EOL.PHP_EOL.$client->title,
                    'markers' => [
                        'icon' => [
                            'labelOrigin' => [-100, -100], // nope
                            'origin' => [-50, -50], // nope
                        ]
                    ]
                ]
            );
```

See the example above :
![image](https://user-images.githubusercontent.com/1824638/93707952-e8bf2900-fb32-11ea-93d9-9fe7e51a6248.png)

Thanks for your help,

Regards

**Comment by bradcornford** [comment]
Hi there,

That should be how it works. I'll have to take a look at this to see if there's a issue. What version are you using?

Can you try removing the markers array item, and putting the icon array at the base of the array.

**Comment by t-prod** [comment]
Hi,

Thanks for your answer, I'm using :

`"cornford/googlmapper": "^3.3",`

Change to this but it doesn't works :

```
Mapper::informationWindow(
                $client->latitude,
                $client->longitude,
                $html,
                [
                    'maxWidth'=> 350,
                    'autoClose' => true,
                    'label' => $client->title,
                    'icon' => [
                        'origin' => [-5, -10],
                    ]
                ]
            );
```

![image](https://user-images.githubusercontent.com/1824638/93708381-ffb34a80-fb35-11ea-8730-49d92763c0a7.png)

**Comment by t-prod** [comment]
Other thing, do you know what changes to do to show infowindows on mouseover ?
This script worked years ago on one of my web app :

```
'eventMouseOver' => 'new google.maps.event.trigger(maps[0].markers['.$cpt.'], "click");',
'eventMouseOut' => 'maps[0].infowindows['.$cpt.'].close();',
```

Close still works but not mouseover (triggered to be a click)

**Comment by bradcornford** [comment]
Okay, i've spotted the issue with the icon, it's in two parts, the code wasn't adding the correct configuration for the icon, but also, Google only allow you to set label origin's on custom icons, The following should now work in current version v3.3.2:

```

Mapper::informationWindow(
                $client->latitude,
                $client->longitude,
                $html,
                [
                    'maxWidth'=> 350,
                    'autoClose' => true,
                    'label' => PHP_EOL.PHP_EOL.$client->title,
                    'markers' => [
                        'icon' => [
                           'url' => 'https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi-dotless2.png',
                            'labelOrigin' => [-10, -10],
                            'origin' => [0, 0], 
                        ]
                    ]
                ]
            );
```

**Comment by bradcornford** [comment]
As for the mouse events, you should be able to call as follows:

```
'eventMouseOver' => 'maps[0].infowindows['.$cpt.'].open(maps[0], this);',
'eventMouseOut' => 'maps[0].infowindows['.$cpt.'].close();',
```

**Comment by t-prod** [comment]
Hi and thanks for the fix. Mouse events working well thanks for this ;)
Unfortunately I do not have any difference with label position it's still centered and above the marker like this :

![image](https://user-images.githubusercontent.com/1824638/93813569-9cb7d580-fc53-11ea-99a1-60b4037d95cb.png)

If it's possible the have the label below the marker it woud be great ;)

I use the same code you give me above.

**Comment by bradcornford** [comment]
Did you update the package, and re-publish the assets?

**Comment by bradcornford** [comment]
Yes, you should be able to move the label origin below using the following:

```
 'labelOrigin' => [0, 10],
```

**Comment by t-prod** [comment]
Yep, I already try this but nothing changes :

![image](https://user-images.githubusercontent.com/1824638/93861039-31f0b380-fcc0-11ea-9e9c-3f4b215b618e.png)

As you can see I have updated the package and redo a :

` php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper`

Icon array is missing and I think it's the problem. What do you think ?

**Comment by t-prod** [comment]
OK I figured it out by analyzing the source code. The markers array is not necessary. The icon dimension directly in the array is OK and it's working. In the documentation you have a dimensions markers so I don't know what's the best for you ;)

```
Mapper::informationWindow(
                $client->latitude,
                $client->longitude,
                $html,
                [
                    'eventMouseOver' => 'maps[0].infowindows['.$cpt.'].open(maps[0], this);',
                    'eventMouseOut' => 'maps[0].infowindows['.$cpt.'].close();',
                    'maxWidth'=> 350,
                    'autoClose' => true,
                    'label' => $client->title,
                    'icon' => [
                        'url' => 'https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi-dotless2.png',
                        'labelOrigin' => [10, 50]
                    ]
                ]
            );
```

Thanks again for your help

**Comment by bradcornford** [comment]
Yes, it should work either way. 

You can add --force to the publish command to force an update of assets.

**Comment by t-prod** [comment]
It's working so I close this issue thanks again for your help ;)
