### ISSUE TITLE
Display different type of icons

### ISSUE THREAD

**Issue by A-Oda1973** [bradcornford/Googlmapper#368]
Hi!
Could you please give me a help with my project?
I'd like to display two different type of icons and make a code bellow.
But it is not working and shows same type of icons.
Is there any way to display different icons?

    Mapper::map($my_lat, $my_lng, ['zoom' => 10,]);

    foreach ($ruin_list as $ruin) {
        Mapper::informationWindow($ruin->lat, $ruin->lng, '<a href="/ruin/show/'.$ruin->id.'">'.$ruin->name.'</a>', ['open' => false, 'maxWidth'=> 300, 'autoClose' => true, 'markers' => ['title' => $ruin->name, 'icon' => ['symbol' => 'CIRCLE', 'scale' => 10]]]);
    }

    foreach ($museum_list as $museum) {
      Mapper::informationWindow($museum->lat, $museum->lng, '<a href="/museum/show/'.$museum->id.'">'.$museum->name.'</a>', ['open' => false, 'maxWidth'=> 300, 'autoClose' => true, 'markers' => ['title' => $museum->name]]);}

**Comment by bradcornford** [comment]
Hi,

Something like this should work:

```
Mapper::map($my_lat, $my_lng, ['zoom' => 10,]);

foreach ($ruin_list as $ruin) {
    Mapper::informationWindow($ruin->lat, $ruin->lng, '<a href="/ruin/show/'.$ruin->id.'">'.$ruin->name.'</a>', ['open' => false, 'maxWidth'=> 300, 'autoClose' => true, 'title' => $ruin->name, 'icon' => ['symbol' => 'CIRCLE', 'scale' => 10]]);
}

foreach ($museum_list as $museum) {
  Mapper::informationWindow($museum->lat, $museum->lng, '<a href="/museum/show/'.$museum->id.'">'.$museum->name.'</a>', ['open' => false, 'maxWidth'=> 300, 'autoClose' => true, 'title' => $museum->name]);
}
```
