### ISSUE TITLE
 How can the buttons be removed from the map?

### ISSUE THREAD

**Issue by xbfast** [bradcornford/Googlmapper#369]
Good evening and thanks for your show. Is it possible to remove the control buttons from the map?

```
Mapper::map($ubicacion->latitud, $ubicacion->longitud, ['marker' => false, 'zoom' => 15, 'markers' => ['title' => 'You are here', 'animation' => 'DROP', 'icon' => 'http://app.sesami.fr/images/marker-black.svg']]);
        Mapper::informationWindow($ubicacion->latitud, $ubicacion->longitud, 'Location 1', ['open' => true, 'markers' => ['title' => 'Title']]);
```

**Comment by bradcornford** [comment]
Hi,

Yes, buttons can be removed from the maps using the following config options and setting their values to false:

- zoomControl
- mapTypeControl
- scaleControl
- streetViewControl
- rotateControl
- fullscreenControl
