### ISSUE TITLE
auto-center map with multiple markers

### ISSUE THREAD

**Issue by jozeflambrecht** [bradcornford/Googlmapper#37]
How can I auto-center the map when I have multiple markers?
e.g.
```
Mapper::map(null, null);
		$collection = Trip::all();
		
		
		$collection->each(function($trip)
        {
            $content = $trip->name;

            Mapper::informationWindow($trip->lat, $trip->lng, $content);
        });
```
Based on the lat-lng values of the trips, I want the map be centered around these information windows...

**Comment by bradcornford** [comment]
Hi,

The map should update its bounds based on all the markers added to it. However, you are required to set a location for the map for initialisation. As such, it may be easier for you to focus the map on the first trip location, then let the map fit to bounds automatically.

**Comment by jozeflambrecht** [comment]
thank you for the explanation!
