### ISSUE TITLE
Can you get lat/lng of clicked location?

### ISSUE THREAD

**Issue by mokhosh** [bradcornford/Googlmapper#371]
Sorry to ask questions in issues section. I'm not sure if this package is concerned with selecting location as well, but I couldn't find anything related in the readme.

Can you get the latitude and longitude for the location that the User has clicked on?

**Comment by bradcornford** [comment]
Hi,

Yes this is possible, you can do something similar to:

```
Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'maps[0].map.addListener("click", (event) => { console.log(event.latLng); });']);

```
