### ISSUE TITLE
Map not rendering when parent element is hidden

### ISSUE THREAD

**Issue by arumcomputer** [bradcornford/Googlmapper#372]
I am trying to render the map in a hidden livewire component. The div element only gets visible when clicking a button and then a simple livewire model changes state and the div is rendered. But the Map inside of that div is empty. Outside of that div everything works as expected.

**Comment by bradcornford** [comment]
Hi, 

I think you need to use the `async` option. 

```
Mapper::map(53.381128999999990000, -1.470085000000040000, ['async' => true]);
```

You may even need to call the initialise method yourself when the state changes:

```
google.maps.event.addDomListener(window, 'load', initialize_0);
```
