### ISSUE TITLE
Map disappers when changing livewire model

### ISSUE THREAD

**Issue by arumcomputer** [bradcornford/Googlmapper#373]
Hi, i am including the map inside od a livewire component. Thats fine so far, but when I make changes to any livewire model (changing input oder radio) the map disappers. It is working with wire:ignore to the parents div of the map, but then i cannot interact with the map the way i like.

**Comment by snggh** [comment]
Hi, I also have the same problem.

**Comment by bradcornford** [comment]
Hi,

I've not used livewire components myself. However you may even need to call the initialise method yourself when the state changes:

google.maps.event.addDomListener(window, 'load', initialize_0);

**Comment by arbendev** [comment]
> Hi, i am including the map inside od a livewire component. Thats fine so far, but when I make changes to any livewire model (changing input oder radio) the map disappers. It is working with wire:ignore to the parents div of the map, but then i cannot interact with the map the way i like.

Where you able to find a solution? having the same issue.

**Comment by arumcomputer** [comment]
> > Hi, i am including the map inside od a livewire component. Thats fine so far, but when I make changes to any livewire model (changing input oder radio) the map disappers. It is working with wire:ignore to the parents div of the map, but then i cannot interact with the map the way i like.
> 
> Where you able to find a solution? having the same issue.

I was not able to. Had a lot of work to do and so i could not test with it.

**Comment by wrabit** [comment]
You should be able to incorporate $wire calls to your events (assuming that's how you are integrating with it) like so:

```
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventDragEnd' => '$wire.setSomething(event)']);
```

**Comment by arbendev** [comment]
> In theory you should be able to incorporate $wire calls to your events (assuming that's how you are integrating with it) like so:
> 
> ```
> Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventDragEnd' => '$wire.setSomething(event)']);
> ```

Hi,

Thank you for the reply... this is what I'm currently doing:

`    public function render()
    {

        $venues = Venue::where('category_id', $this->category)->get();
   
        Mapper::map(40.75653332919923, -73.98020256160748, ['zoom' => 12, 'eventAfterLoad' => 'kmlLayers();', 'async' => true, 'clusters' => ['size' => 20, 'center' => true, 'zoom' => 14]]);

        foreach ($venues as $venue) {
            Mapper::marker($venue->latitude, $venue->longitude);
            Mapper::informationWindow($venue->latitude, $venue->longitude, '<a href="/concierge/summary/venue/'.$venue->slug.'">'.$venue->name.'</a>', ['open' => false, 'maxWidth'=> 350, 'autoClose' => true]);
        }

        return view('livewire.show-map', [
            'venues' => $venues
        ]);
    }
`

Thanks!

**Comment by wrabit** [comment]
Cool, I got round it like:

```
// ... marker([
// ...
'eventDragEnd' => 'window.Livewire.emit("updateLatLng", event.latLng);',
// ...
```

And then in component:

```
    public function updateLatLng($value)
    {
        $this->address->lat = $value['lat'];
        $this->address->lng = $value['lng'];
    }
```
