### ISSUE TITLE
Cornford\Googlmapper\Exceptions\MapperInstanceException No map found to add a polyline to.

### ISSUE THREAD

**Issue by RafianR23** [bradcornford/Googlmapper#377]
i use laravel 6, i follow your step but view in my php file is eror and show

Cornford\Googlmapper\Exceptions\MapperInstanceException
No map found to add a polyline to.

i search and dont know the solve.

**Comment by bradcornford** [comment]
Hi, 

You first need to create a map instance to be able to use the polyline method, for example:

```
Mapper::map(53.381128999999990000, -1.470085000000040000);
Mapper::polyline([['latitude' => 53.381128999999990000, 'longitude' => -1.470085000000040000], ['latitude' => 52.381128999999990000, 'longitude' => 0.470085000000040000]]);
```

**Comment by RafianR23** [comment]
thank you sir, i've finished my problem

and i just use this code and solve it
Mapper::map(52.381128999999990000, 0.470085000000040000)->polygon([['latitude' => 53.381128999999990000, 'longitude' => -1.470085000000040000], ['latitude' => 52.381128999999990000, 'longitude' => 0.470085000000040000]], ['strokeColor' => '#000000', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);

**Comment by bradcornford** [comment]
Excellent, glad you could get it working for you.
