### ISSUE TITLE
Issue on displaying the map using 'location'

### ISSUE THREAD

**Issue by rcadhikari** [bradcornford/Googlmapper#38]
Hi Bradcornford,
Thanks for the library, however I am unable to load the map when I try below code; any help to make the below code work would be really helpful.

```
Mapper::location('Sheffield');
echo Mapper::render();
```

**Comment by bradcornford** [comment]
Hi,

Mapper::location() returns a location object, which has callable methods for creating a map:

Mapper::location()->map();
Mapper::location()->streetview(1, 1);

**Comment by rcadhikari** [comment]
Just realised that the below code does the job.
```
Mapper::location('Sheffield')->map()'
echo Mapper::render();
```
By the way, do you have any prarameter to control the width x height of the display.

Thanks for help!

**Comment by bradcornford** [comment]
Hi,

No by default it will fill the size of the container. You can use CSS to achieve this.
