### ISSUE TITLE
Render is not showing map

### ISSUE THREAD

**Issue by joaosauer** [bradcornford/Googlmapper#40]
Hi,

I just looked for your issues here and was trying to show google maps in my page.
I just add this code to my blade file:

```
@section('content')
<div class="container">
    <div class="row">
        <div class="mymap">
            {!! Mapper::render() !!}
        </div>
    </div>
</div>
@endsection
```

but nothing is showing...
Then, I looked for the source of the page and I'm getting this:
```
 <div class="row">
        <div class="mymap">
            <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&region=BR&language=pt-br&key=removed_by_me&signed_in=false&libraries=places"></script>


	<script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script>
        </div>
```

As you can see, the javascript part, that is explained in the official google maps helper, it was not included:
```
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>

```

Am I missing something here? The only file that I changed was the blade file. And this is laravel's 5.2 out of the box new project.

Cheers,
Joao

**Comment by joaosauer** [comment]
Ok, just found out the solution.

Only doing the render won't work. 
First, we need to request a map (Mapper::Map) and then use the render.

Closing it...

**Comment by bradcornford** [comment]
Sorry for the late reply! Glad you managed to resolve your issue.

**Comment by sbourdette** [comment]
Sorry but I have exactly the same problem but I have a Mapper::Map in my controller.
AlbumController.php
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Cornford\Googlmapper\Mapper;

class AlbumController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);
        
        return view('album');
    }
}`

album.blade.php :

`                                    <tr>
                                        <td class="table-text"><div>Maps</div></td>
                                        <td>{!! Mapper::render() !!}</td>
                                        <td>&nbsp;</td>
                                    </tr>`

Generate html source :
`

</tr>
--
  | <tr>
  | <td class="table-text"><div>Maps</div></td>
  | <td><script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&region=FR&language=fr&key=XXXXXXXXXXXXXXXXXXXX&signed_in=false&libraries=places"></script>
  |  
  |  
  |  
  | <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script>
  |  
  |  
  |  
  |  
  | </td>
  | <td>&nbsp;</td>
  | </tr>

`
