### ISSUE TITLE
Map Click method?

### ISSUE THREAD

**Issue by joaosauer** [bradcornford/Googlmapper#41]
Hi,

I would like to let the user mark a point in the map. In my particular case, to register a place.

I did notice that we do have the dragable marker, but I would like to also let user click in the map and make the marker move to the place where the map was clicked.

Is this possible? How can I do it?

Thanks,
Joao

**Comment by bradcornford** [comment]
Hi,

You should be able to achieve this, with somehting along the lines of:

```js

google.maps.event.addListener(maps[0].map, 'click', function(event) {
  var marker = new google.maps.Marker({
        position: event.latLng, 
        map: map
    });
});

```

**Comment by joaosauer** [comment]
Yes, this was the solution.
But, if you just add this in the end of the blade file, you will get 'map not defined', because the map is not loaded it.
So, what I did was:
```
        google.maps.event.addDomListener(window, 'load', new function() {
            setTimeout(function () {
                google.maps.event.addListener(maps[0].map, 'click', function(event) {
                    maps[0].markers[0].setPosition(event.latLng);
                });
            }, 500);
        });
```

Where I also add my code to the load of the google maps and wait just half second to be sure that the main load (the one from GoogImapper) is finished.

Also, I'm moving the existent marker in instead of just create a new one.

Cheers,
Joao

**Comment by bradcornford** [comment]
Yeah, that is very true. There also now is two options for the map for before and after load events, introduced in version 2.8.0:

'eventBeforeLoad' and 'eventAfterLoad'

These can be used as follows:

```php

Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventBeforeLoad' => 'console.log("before load");']);

Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'console.log("after load");']);

```

**Comment by joaosauer** [comment]
Weird.
I just following the explanations in the github to install the googImapper, but Apparently, I'm not using 2.8.0.
My line is:
`Mapper::map($lat, $lng, ['zoom' => 12, 'draggable' => true, 'eventDrag' => 'newMarkerPosition(event);', 'eventAfterLoad' => 'eventAfterLoad(event);']);`

But I also tried your code above, and nothing happens.
Is there a way to check which version I'm using?

Cheers,
joao

**Comment by joaosauer** [comment]
Ok, for some reason, using the 
`        "cornford/googlmapper": "2.*"`
in composer.json
was getting the 2.7.0 version
When I explicit said:
`        "cornford/googlmapper": "2.8.0"`

I got the latest version and the code worked. :)

Closing again.

**Comment by bradcornford** [comment]
Are you using the command 'composer update' to fetch the latest version?

**Comment by joaosauer** [comment]
yep

**Comment by bradcornford** [comment]
Very strange, composer should pull the latest minor version / bug fix version when using 1.* notation. Glad you got this to work!
