### ISSUE TITLE
InvalidValueError: setIcon: not a string; and no url property; and no path property

### ISSUE THREAD

**Issue by d3vnu77** [bradcornford/Googlmapper#43]
Getting this javascript error in the console when running:

`<?php $content = $marker['count'].' '.str_replace("'", "\\'", $marker['city']).' Customers<br />'; ?>
            <?php $map->informationWindow($marker['latitude'], $marker['longitude'], $content, ['markers' => ['title'=>'Title','symbol' => 'circle', 'scale' => 1000]]); ?>`

**Comment by bradcornford** [comment]
Hi there,

Can you provide me me more information, what you have in you controller, what you have in your view?

**Comment by d3vnu77** [comment]
Sorry it took awhile to get back, haven't been at my computer at all today.

Here is my controller and view

http://kopy.io/F7Y19

**Comment by bradcornford** [comment]
Hi,

I would move the code below into your controller, there is no reason the controller cant handle this, and it also cleans up your views to only having to render.

```php
$map = GoogleMapper::map(current($markers)['latitude'], current($markers)['longitude']);
````

```php
foreach ($markers as $marker) {
    $content = $marker['count'].' '.str_replace("'", "\\'", $marker['city']).' Customers<br />';
    $map->informationWindow($marker['latitude'], $marker['longitude'], $content, ['markers' => ['symbol' => 'circle', 'scale' => 2000]]);
}
```

**Comment by paceband** [comment]
Same issue for me using version v2.8.0. Was working fine up to now...

**Comment by bradcornford** [comment]
Can you show all the errors that you see in console please.

**Comment by bradcornford** [comment]
Are you still seeing this issue?
