### ISSUE TITLE
Number of Markers when zoom out

### ISSUE THREAD

**Issue by ifventures** [bradcornford/Googlmapper#44]
Hello,

When zoom out on map markers seem with number. Like this:
![mapimage](https://cloud.githubusercontent.com/assets/7079132/15507107/d9b528e4-21d2-11e6-9f89-d78c2aa0303c.png)

U can see that it is really hard to find this small number in the map. How can we change image type of this numbers?

Also i found this kind of example. 
![map2](https://cloud.githubusercontent.com/assets/7079132/15507188/352b430c-21d3-11e6-8646-1c95794e4ac6.png)

can we change icons like example?

Thanks,

Hakan

**Comment by bradcornford** [comment]
Hi,

By default the configuration is set to achieve the above by default, it can be found within the config.php under the key 'cluster'.

**Comment by ifventures** [comment]
Thanks  a alot man ;)
