### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by silentFred** [bradcornford/Googlmapper#45]
Hey Bradley, 

I'm not too sure this package supports laravel 5.2 (or 5+). Just wondering if it's possible to use in L5. I really dig the functionality. Would be great to use

**Comment by bradcornford** [comment]
Hi,

Yeah this package does support L5. However I haven't check compatability for 5.2 as of yet. Glad you like the package!

**Comment by silentFred** [comment]
I wasn't importing the facade due to an outdated ide helper file. All sorted now and having plenty of fun with it! Well done!

**Comment by tedmasterweb** [comment]
I'm sorry but could you please clarify how you are importing the Facade? I've tried
`use Cornford\Googlmapper\Facades\MapperFacade;`
but that doesn't seem to work.

TIA

**Comment by bradcornford** [comment]
You will have to do the following:

```php
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
```

**Comment by tedmasterweb** [comment]
That did the trick! Thank you for the prompt reply!

And while I've got your attention ;-) Which Google Maps API should I be getting a key for? There are 16 different Maps APIs. I assume it would be either [Google Maps JavaScript API](https://console.developers.google.com/apis/api/maps_backend/overview) or [Google Maps Embed API](https://console.developers.google.com/apis/api/maps_embed_backend/overview).

The API included with the sample config doesn't seem to work (but it could also be my lack of patience in configuring things).

**Comment by silentFred** [comment]
@tedmasterweb it should be the Google maps javascript api

**Comment by bradcornford** [comment]
Yeah that's correct, it's for the Javascript API. The key used in the config is one I setup with Google which I believe is keyed up to a localhost domain.

**Comment by tedmasterweb** [comment]
Thank you both. I've got it working now and it's great, really great. Thank you!

**Comment by kreativjamesz** [comment]
Please **update** the description and add laravel 5.0.x to 5.2.x version, so that even more colleagues would ever love your work. Peace. ^_^

**Comment by bradcornford** [comment]
I have now changed the composer.json to use 5.*.

**Comment by MuhammadRamzan1** [comment]
Is this package supports laravel 5.2?I am using this package but it shown a blank page to me.

**Comment by bradcornford** [comment]
Yes, this package supports Laravel 5.2. Ensure that you have added the provider, and facade to you application config, along with publishing the packages items too.

**Comment by MuhammadRamzan1** [comment]
When I run this command:
> php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"

it shows me:
>Nothing to publish for tag [].

**Comment by MuhammadRamzan1** [comment]
I have added service provider and aliases in config/app.php too.

**Comment by bradcornford** [comment]
Is that the only thing it shows for you?

I receive:

```
Copied Directory [/vendor/cornford/googlmapper/src/views] To [/resources/views/cornford/googlmapper]
Publishing complete for tag []!
```

Try this: 

```
composer dump-autoload -o
php artisan vendor:publish --tag="googlmapper"
```

**Comment by MuhammadRamzan1** [comment]
Now it shows

`Copied Directory [\vendor\cornford\googlmapper\src\views] To [\resources\views\cornford\googlmapper]
Publishing complete for tag [googlmapper]!`

But still shows me blank page.I set GOOGLE_API_KEY in config.php and other method too as you described.

**Comment by bradcornford** [comment]
What code have you got in your controller? What do you have in your view?

**Comment by MuhammadRamzan1** [comment]
My controller is:

     `class MapController extends Controller
       {
       public function map()
       {

     Mapper::map(40.59726025535419, 80.02503488467874, ['marker' => false]);

        // Add information window for each address
        $collection = \App\Address::all();

        $collection->each(function($address)
        {
            $content = $address->users->name;

            Mapper::informationWindow($address->latitude, $address->longitude, $content);
        });

        return view('googlmapper', compact('collection'));

       }`

And in view:

       `@extends('layouts.app')

        @section('content')

         {!! Mapper::render() !!}

         @stop`

**Comment by MuhammadRamzan1** [comment]
And route is:
        `Route::get('googlmapper', 'MapController@map');`

**Comment by bradcornford** [comment]
Okay, you need to add a width / height onto the containing item. For example:

```
<div style="height: 400px; width: 400px;">{!! Mapper::render() !!}</div>
```

**Comment by MuhammadRamzan1** [comment]
Still it shows blank page.

**Comment by bradcornford** [comment]
Are there any errors in console?

**Comment by MuhammadRamzan1** [comment]
There is error "Uncaught ReferenceError: google is not defined" in googlemapper:232

Also

 "GET http://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js net::ERR_CONNECTION_REFUSED" in googlemaper:175

**Comment by bradcornford** [comment]
Can you not access that resource? http://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js?

**Comment by MuhammadRamzan1** [comment]
Yes,there is problem with this.

**Comment by bradcornford** [comment]
You could save the resource markercluster.js, from https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js locally, then update your view mapper.balde.php to utilise this file.

**Comment by MuhammadRamzan1** [comment]
I saved the js file in public/js folder.But what I have to update in mapper.blade.php?

**Comment by bradcornford** [comment]
Replace line 5 with:

```
	<script type="text/javascript" src="{!!  URL::asset('js/markerclusterer.js') !!}"></script>
```

**Comment by MuhammadRamzan1** [comment]
This error remains there:

 `Uncaught ReferenceError: google is not defined(anonymous function) @ googlmapper:70`

**Comment by MuhammadRamzan1** [comment]
Screenshot of console:

![1](https://cloud.githubusercontent.com/assets/20591478/17406731/24035dc4-5a7e-11e6-9f0d-479f004c0509.png)

**Comment by bradcornford** [comment]
It looks like your request to get the Google maps api is failing. This is likely causing your issue.

**Comment by MuhammadRamzan1** [comment]
I tried by changing the Google Api Key but these errors remains there.

**Comment by bradcornford** [comment]
Something is blocking your connection to Google to retrieve the api js file.

**Comment by ferreralan** [comment]
Hi!
I can't get this working,
I added: "cornford/googlmapper": "2.*"
Run the: composer update
Add to app.php: 
Cornford\Googlmapper\MapperServiceProvider::class,
and
'Mapper'         => Cornford\Googlmapper\Facades\MapperFacade::class,

when I try tu run : php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper

I get this error: [Symfony\Component\Debug\Exception\FatalErrorException]       
  Class 'Cornford\Googlmapper\MapperServiceProvider' not found

**Comment by bradcornford** [comment]
Hi there,

What version of Laravel are you using?

**Comment by ferreralan** [comment]
I fixit! Thanks!

**Comment by hkerssies** [comment]
How did you fixed this?
I still have this error laravel 5.4!

**Comment by Playbert** [comment]
Error laravel 5.3

FatalErrorException in web.php line 16:
Class 'Cornford\Googlmapper\Facades\MapperFacade' not found


in web.php (routes)

i do called  : 

Mapper::map(
    	[
    		'zoom' => 16,
    		'draggable' => true,
    		'marker' => false,
    		'eventAfterload' =>
    		'circleListener(maps[0].shapes[0].circle_0);'
    	]
    );

**Comment by bradcornford** [comment]
Hi there,

Can you try the following:

```
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider" --tag=googlmapper
```

**Comment by xandedj** [comment]
Bom dia.

1 -Estou com um problema na infowindow, quando adiciono a função os meus icones personalizados somem aparecendo somente o maker padrão e mesmo assim a janela de informações não abre, preciso que ela fique fixa mostrando o nome do dispositivo.

2- Preciso exibir o percurso executado por um determinado dispositivo

pode me ajudar?


  Mapper::map(-22.886449, -43.118474,
              [   'marker'=>false,
                  'zoom' => 10,
                  'draggable' => true,
                  'center' => true,
                  'cluster' => false,
                  'informationWindow' => 'Teste da Janela', [
                  'open' => true,
                  'maxWidth'=> 300,
                  'markers' => [
                  'icon' =>'img/ida_22.png',
                  'title' => '166001',
                  'animation' => 'DROP']],

              ]);

              $markers = array(['lat' => -22.886449,'lng' => -43.118474],
                                ['lat' => -22.885632,'lng' => -43.118143],
                                ['lat' => -22.883990,'lng' => -43.119513],
                                ['lat' => -22.885734,'lng' => -43.124988]);
            //  dd($markers);
              foreach ($markers as $marker) {
               //dd($marker['lat'], $marker['lng']);
                  Mapper::marker($marker['lat'], $marker['lng']);

              }

**Comment by dougblackjr** [comment]
@MuhammadRamzan1 Have you figured out a fix to this?

For me, I was calling the map asynchronously and needed to set the async to true in the config file.

**Comment by bradcornford** [comment]
If you still are having this issue, try the following:

```php
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

Mapper::map(
[
'zoom' => 16,
'draggable' => true,
'marker' => false,
'eventAfterload' =>
'circleListener(maps[0].shapes[0].circle_0);'
]
);

```

**Comment by mj-isip23** [comment]
Is this still compatible with Laravel 5.6?
