### ISSUE TITLE
Cluster icon

### ISSUE THREAD

**Issue by messi89** [bradcornford/Googlmapper#46]
Hi

how to set an icon to a cluster of markers ?

**Comment by messi89** [comment]
problem solved

**Comment by bradcornford** [comment]
Excellent, what was your solution?

**Comment by messi89** [comment]
@bradcornford 
by using a local markerclusterer.js
<script type="text/javascript" src="/plugins/markerclusterer/markerclusterer.js"></script>

upload images folder and modified the MARKER_CLUSTER_IMAGE_PATH_ to '/plugins/markerclusterer/images/m';

**Comment by bradcornford** [comment]
@messi89 that seems a good solution. Are there not any config values that can be written? Rather than re-writing the source?

**Comment by messi89** [comment]
@bradcornford I take a quick look on the script, I think we can pass the path as option on the constructor

```javascript
function MarkerClusterer(map, opt_markers, opt_options) {
.....
this.imagePath_ = options['imagePath'] || this.MARKER_CLUSTER_IMAGE_PATH_;

}
```

on mapper we have 
```php
public function map($latitude, $longitude, array $options = [])
{
}
```

what do you think ?

**Comment by bradcornford** [comment]
Yeah that could be a good way to do it, but may be better to do it in config as then it would be universal. I'm not sure how the plug in handles multiple constructor calls.

**Comment by messi89** [comment]
Yes it will be better !

**Comment by bradcornford** [comment]
Okay, so i've implemented the cluster marker settings in config, and for map instantiation. This can be found in the develop branch if you would like to take a look.

For usage when creating a map:

```php

Mapper::map(53.3, -1.4, ['zoom' => 10, 'clusters' => ['icon' => '../images/m', 'size' => 4]]);

```

For usage in config:

```php

'clusters' => array (
    'icon' => '//googlemaps.github.io/js-marker-clusterer/images/m',
    'grid' => 60,
    'zoom' => null,
    'center' => false,
    'size' => 2
)

```

**Comment by bradcornford** [comment]
This has now been merged to master, and versioned as current version 2.9.0.
