### ISSUE TITLE
How to show information window after load ?

### ISSUE THREAD

**Issue by messi89** [bradcornford/Googlmapper#47]
Hi

I'm looking to show the information window of an marker after the map loading

how can I do it with eventAfterLoad ? 

Thanks

**Comment by bradcornford** [comment]
Hi,

You should be able to do something along the lines of:

```php

$mapper->map(53.3, -1.4, ['zoom' => 10, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 'eventAfterLoad' => 'infowindow_1.open(maps[0], maps[0].markers[1]);']);

$mapper->informationWindow(53.4, -1.5, 'Content');

$mapper->informationWindow(52.4, -1.4, 'Content');

$mapper->informationWindow(51.4, -1.3, 'Content');

```

Where maps[0] is the first map, maps[0].markers[1] is the second marker, and infowindow_X is the item count of information windows, from a base of 1.

For example if you wanted the second information window to show, you would use:

```php

'eventAfterLoad' => 'infowindow_2.open(maps[0], maps[0].markers[2]);'

```

**Comment by bradcornford** [comment]
This has now been merged to master, and versioned as current version 2.9.0.
