### ISSUE TITLE
Accessing map variable in JavaScript

### ISSUE THREAD

**Issue by tedmasterweb** [bradcornford/Googlmapper#49]
Hi,

Awesome project, very helpful. Thanks!

I'm writing to ask how I can access the "map" variable via JavaScript. I need to update the map with new coordinate (following a search via the JS API) but I'm doing something wrong. I'm wondering if you can provide a pointer on how to do this, on how to hook into your JS code. 

Specifically, I'd like to trigger a new search (against a postcode, for example) and update the map to drop the pin in the new location).

I know this isn't the best place to ask but perhaps others will find it useful.

Thanks again for the great library.

PS: in a worst-case scenario I know I can always to an AJAX call and replace the map element with the response but that seems kludgy.

**Comment by bradcornford** [comment]
Hi,

You should have access to a global maps array variable, each item is an object which contains the keys key, map, and markers. You should be able to hook events into the maps using this.

```js
console.log(maps[0].key);
console.log(maps[0].map);
console.log(maps[0].markers);
```

**Comment by tedmasterweb** [comment]
Thanks a bunch. That was my suspicion but I wasn't exactly clear on the method (wasn't sure that maps was an array). I think I can figure out the rest from here. Thanks a bunch!

**Comment by bradcornford** [comment]
Great stuff. Let me know how you get on, or if you require any further help.

**Comment by danilosantosdev** [comment]
@bradcornford How can i change the content of a informationWindow in JS?

I need to add information on it after some events.

**Comment by bradcornford** [comment]
Hi @danilosantosdev,

You can access the information windows as follows:

```js
console.log(maps[0].infowindows);
maps[0].infowindows[0].setContent('hello');
```
