### ISSUE TITLE
Add option to access map in Javascript

### ISSUE THREAD

**Issue by iamgoodbytes** [bradcornford/Googlmapper#5]
Is there a way to add an extra option to Googlmapper like "$enableGlobalAccess" that allows developers to access the created map through Javascript after rendering? 

The only thing this would have to do is create the var map outside of the initialize() function and now use the "var" map keyword inside of the function. That way, developers can manipulate the map after rendering by using javascript.

**Comment by bradcornford** [comment]
Hi there,

I don't think this requires an option to enable, however it should just be default functionality. 

I have added a "maps" variable, which contains an array of map objects, key, and map.

This has been pushed to the develop branch if you want to give it a test.

**Comment by iamgoodbytes** [comment]
Thanks, the array you added seems to be fine! I've coded my way around the previous limitation, but I'll definitely make use of this feature the next time. Works for me!
