### ISSUE TITLE
displaying the mapper

### ISSUE THREAD

**Issue by lakachew** [bradcornford/Googlmapper#51]
hello,

i am using Laravel 5.2 for viewing google maps along with different markers. but i couldn't manage to use it (view the map)

i think i have understood how this api works but i couldn't manage to see the map (render the map) but i do see the values i have retrieved using the var_dump() method.

could you please show me how i use it in my view page (php with blade).

it is not working but this is how i thought it would work:
 ****** in my controller class ********
`$mapper = \Mapper::map($workGPSLocations[0], $workGPSLocations[1]);`

`return view('home')->with('mapper', $mapper);`

***** view ****
```
<ifram width="100%" height="600" frameborder="0" style="border:0"
                            src="{!! $mapper->render(0) !!}"></ifram>
```

and

```
<ifrme width="100%" height="600" frameborder="0" style="border:0">
{!! $mapper->render(0) !!}</ifrme>
```

and

`{!! $mapper->render(0) !!}`

.
.
..

Nothing is working for me. could you please give a sample code.

Thank you!!!

**Comment by bradcornford** [comment]
Hi, it's as simple as creating a map in your controller, then rendering in you view. The below should work:

```php
// In your controller
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

Mapper::map($workGPSLocations[0], $workGPSLocations[1]);

// In your view
{!! Mapper::render () !!}
```

**Comment by lakachew** [comment]
i get the following content when using
`<div>{{ \Mapper::render(0) }}</div>`

***************

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&region=GB&language=en-gb&key=AIzaSyAfYOov7QNu9s56k0&signed_in=false&libraries=places"></script> <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js"></script> <div id="map-canvas-0" style="height: 100%; margin: 0; padding: 0;"></div> <script type="text/javascript"> var maps = []; function initialize_0() { var bounds = new google.maps.LatLngBounds(); var infowindow = new google.maps.InfoWindow(); var position = new google.maps.LatLng(36.5677206, 139.9033588); var mapOptions_0 = { center: position, mapTypeId: google.maps.MapTypeId.ROADMAP, disableDefaultUI: false , scrollwheel: true }; var map_0 = new google.maps.Map(document.getElementById('map-canvas-0'), mapOptions_0); map_0.setTilt(90); var markers = []; var markerPosition_0 = new google.maps.LatLng(36.5677206, 139.9033588); var marker_0 = new google.maps.Marker({ position: markerPosition_0, title: '', animation: '' , icon: '' }); bounds.extend(marker_0.position); marker_0.setMap(map_0); markers.push(marker_0); var idleListener = google.maps.event.addListenerOnce(map_0, "idle", function () { map_0.setZoom(8); }); var markerClusterOptions = { imagePath: '//googlemaps.github.io/js-marker-clusterer/images/m', gridSize: 60, maxZoom: null , averageCenter: false , minimumClusterSize: 2 }; var markerCluster = new MarkerClusterer(map_0, markers, markerClusterOptions); maps.push({ key: 0, markers: markers, map: map_0 }); } google.maps.event.addDomListener(window, 'load', initialize_0); </script>

**Comment by bradcornford** [comment]
Make sure you render to anew element with a width and height.

```html

<div style="height: 500px; width: 500px;">{!! Mapper::render () !!}</div>

```

**Comment by lakachew** [comment]
it worked ... Thank you !!

**Comment by baqirfarooq** [comment]
its worked ... Thank you !!
