### ISSUE TITLE
Setting marker color and other marker attributes

### ISSUE THREAD

**Issue by tedmasterweb** [bradcornford/Googlmapper#53]
Hi again,

Really, really loving this module, btw…

I'm trying to set the color of markers. I've reviewed the [Google Docs on the subject](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Marker) but I can't quite see where or how to modify the color (and other attributes) of markers.

Given:
`Mapper::informationWindow($lat, $lng, 'content')`

It looks like I could do something like:
`Mapper::informationWindow($lat, $lng, 'content', ['markers' => ['symbol' => 'circle', 'fillColor' => 'red']])`

But I'm missing something. Any help would be greatly appreciated.

Thanks and if it means extending one of your classes, I'll gladly contribute whatever I produce.

Ted

**Comment by bradcornford** [comment]
Hi,

I'm glad your loving the module.

You can't actually set the fill colour attribute on a marker, you can however pass an image url like this:

```php
Mapper::informationWindow($lat, $lng, 'content', ['markers' => ['symbol' => 'circle', 'icon' => '/path/to/image.png']]);
```
In order to achieve fill colour, both the model for maker, and the view would need to be updated. I don't think that would require too much work either. Let me know if you require any help implementing the above if you require it.

**Comment by bradcornford** [comment]
Did you make any progress with this?

**Comment by tedmasterweb** [comment]
No, I didn't. Just haven't had time. I will say I think updating the view would be my approach. If I do do that, I'll submit my changes for review.

**Comment by jpmurray** [comment]
@tedmasterweb on a related not, if I want to use [styled maps](https://developers.google.com/maps/documentation/javascript/styling?hl=fr#styling_the_default_map), do I simply need to pass the needed parameters like you pass the markers array two comments earlier?

**Comment by bradcornford** [comment]
After looking into this furter, it doesnt appear that markers have available style options. They can only be changed via another image, see: http://stackoverflow.com/questions/7095574/google-maps-api-3-custom-marker-color-for-default-dot-marker.

**Comment by bradcornford** [comment]
@jpmurray You should be albe to pass the settings on the before/afterload functions.

```php
Mapper::map(42.5,41.8, ['center' => true, 'eventBeforeLoad' => 'function ()  {styleMap(map_0); }', 'markers' => ['title' => 'My Location', 'animation' => 'DROP']]);
```

```php
Mapper::map(42.5,41.8, ['center' => true, 'eventAfterLoad' => 'styleMap(maps[0].map);', 'markers' => ['title' => 'My Location', 'animation' => 'DROP']]);
```

```js

function styleMap(map)
{
var styles = [
  {
    stylers: [
      { hue: "#00ffe6" },
      { saturation: -20 }
    ]
  },{
    featureType: "road",
    elementType: "geometry",
    stylers: [
      { lightness: 100 },
      { visibility: "simplified" }
    ]
  },{
    featureType: "road",
    elementType: "labels",
    stylers: [
      { visibility: "off" }
    ]
  }
];

map.setOptions({styles: styles});
}
```

**Comment by xitude** [comment]
I'm unable to get `eventBeforeLoad` to run.
`Uncaught SyntaxError: Unexpected token (`
`function ()  {styleMap(map_0); }`

**Comment by bradcornford** [comment]
Hi there,

Can you show me your controller please.

**Comment by xitude** [comment]
```
<?php

namespace App\Http\Controllers;

use Cornford\Googlmapper\Facades\MapperFacade as Mapper;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventBeforeLoad' => 'function ()  {styleMap(maps[0].map); }']);
        return view('home');
    }
}
```

**Comment by bradcornford** [comment]
How about your view?

**Comment by xitude** [comment]
```
@extends('layouts.app')

@section('content')
<section class="map " style="height: 80vh;">
{!! Mapper::render() !!}
</section>

<script>
    function styleMap(map)
    {
        var styles = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}];

        map.setOptions({styles: styles});
    }
</script>
@endsection
```

It works it is do `'eventAfterLoad' => 'styleMap(maps[0].map);'`

**Comment by bradcornford** [comment]
I'll take a look into the before action. The after action should be fine too. The map itself is accessed differently for before and after. The before evebt would requires maps_0, the after event requires maps [0].map

**Comment by haubix** [comment]
Hello.
About the styled map - this works for me:
`'eventBeforeLoad' => 'styleMap(map);'`

Then you add a function in Javascript:
`function styleMap(map) {

&nbsp;&nbsp;&nbsp;&nbsp;style = [

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;your style settings&gt;

&nbsp;&nbsp;&nbsp;&nbsp;];

&nbsp;&nbsp;&nbsp;&nbsp;map.setOptions({styles: styles});

}`

Kind regards
