### ISSUE TITLE
Data passed to views is not escaped

### ISSUE THREAD

**Issue by miken32** [bradcornford/Googlmapper#54]
Tried setting a marker title with an apostrophe in it, and it broke badly:

    Mapper:map($lat, $lon, ["markers"=>["title"=>"John's Place", "animation"=>"DROP"], "zoom"=>14]);

I was looking at how best to solve the problem, it seems like building the options as a PHP object inside the `Marker::render()` method would work well, and allow you to remove a lot of if/else logic from the view. You could simply encode it as JSON and pass the whole thing directly to the JavaScript constructor.

While investigating this, I also noticed there's a function close on line 58 of `marker.blade.php` that's inside an `@if` block. I don't think it's getting inserted if the `@if` isn't true.

**Comment by bradcornford** [comment]
Hi,

Thanks for this. I'll look into resolving this.

**Comment by bradcornford** [comment]
Hi there,

I've now pushed a simple fix for this on versions v2.10.2 / v1.5.2.

**Comment by miken32** [comment]
This is still affecting me in 2.12.0. You need to call `json_encode($options['title'], JSON_HEX_APOS)` if you want apostrophes escaped. They aren't special characters in JSON, which uses double quotes as string delimiters.

**Comment by miken32** [comment]
Scratch that, I just forgot to do `artisan vendor:publish`. It's all good. Thanks for the fix!
