### ISSUE TITLE
Setting values to Lat and Long, How to capture this values? is possible?

### ISSUE THREAD

**Issue by lavy** [bradcornford/Googlmapper#55]
hi man, i have a problem, i need to capture the Lat and Long from the marker draggable, this is possible to do with that library?

**Comment by bradcornford** [comment]
Hi there, 

Yes this is possible. You can use the marker dragable events to achieve this. Something along the lines of this should suffice:

```php

Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventDragEnd' => 'console.log(event.latLng.lat()); console.log(event.latLng.lng());']);
```

**Comment by bradcornford** [comment]
Did you have any luck with this?

**Comment by tedmasterweb** [comment]
Interesting. I was using this:

var mylat = this.getPosition().lat()

Is there a preference of one over the other?

Thanks,

Ted

**Comment by lavy** [comment]
Hi man, yes i solve the problem, thanks a lot

**Comment by bradcornford** [comment]
No, there is no preference, however I personally like taking the latitude and longitude from the event itself.
