### ISSUE TITLE
Auto Suggest and Display Particular property 

### ISSUE THREAD

**Issue by tisuchi** [bradcornford/Googlmapper#57]
Hay there.. 
Without doubt, its a nice work. However, I am planning to get location autosuggest option. Is there any way to do so?

Again, if I need to collect any particular property from Mapper::location, how can I do so?
For example, when I render location I get following result -
`Location {#276 ▼
  #search: "Kuala Lumpur, Malaysia "
  #address: "Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia"
  #type: "locality"
  #latitude: 3.139003
  #longitude: 101.686855
  #placeId: "ChIJ5-rvAcdJzDERfSgcL1uO2fQ"
}`

From there, I just wanna get **latitude** and **longitude** result. How can I get it?

**Comment by bradcornford** [comment]
Hi there,

You could possibly achieve this by using Ajax, calling onto the location with the search, with something like:

```php

$location = Mapper::location('SEARCH STRING');

$search = $location->getSearch();
$address = $location->getAddress();

```

The location call returns a location object, this object has methods which can be used to get both latitude and longitude. See here for reference https://github.com/bradcornford/Googlmapper/blob/master/src/Cornford/Googlmapper/Models/Location.php. Something along the lines of this would suffice:


```php

$location = Mapper::location('Sheffield');
$latitude = $location->getLatitude();
$longitude = $location->getLongitude();

```

**Comment by tisuchi** [comment]
thank you for prompt response. However, 1 issue settle down already. 

How about auto suggest part in search box. For example, if I type "Shef..." then automatically suggest "Sheffield, UK" where user has flexibility to choose.

**Comment by bradcornford** [comment]
Thats not something that rhis package cureently offers. You might want to look into https://developers.google.com/maps/documentation/javascript/places-autocomplete.
