### ISSUE TITLE
Facade Call

### ISSUE THREAD

**Issue by willycornelissen** [bradcornford/Googlmapper#6]
I am trying to call Mapper facade from my controller, but I am receiving the following error message:

Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically, assuming $this from incompatible context

I added Mapper::render() on my view, but I am receiving lines of HTML code instead.
What am I doing wrong?

**Comment by bradcornford** [comment]
Hi there,

I'm assuming your running Laravel? What version? 

If your not, you won't be able to call the methods statically, you'd have to construct a new Mapper and called methods upon the constructed object.

**Comment by bradcornford** [comment]
Also if your using use statements, use the facade rather than the class itself.

**Comment by willycornelissen** [comment]
Hello Brad.

I am using Laravel 5.1 and I am leaning how to develop using the framework. although I am a long time PHP developer. Here is my call to the package in my controller:

class PontoController extends \Mitul\Controller\AppBaseController
{
      public function map($id)
	{
		dd(Mapper::map(53.381128999999990000, -1.470085000000040000));		
	}
}

Can I find an example somewhere on the web?

**Comment by bradcornford** [comment]
I'll have to setup an new Laravel installation and follow the install steps to see if i can re-create this issue.

```php
use Cornford\Googlmapper\Facades\MapperFacade as Mapper;

class PontoController extends \Mitul\Controller\AppBaseController
{
    public function map($id)
    {
        Mapper::map(53.381128999999990000, -1.470085000000040000);
        dd(Mapper::render());
    }
}
```
Is a simple example I would use, the map method returns an instance of Mapper for method chaining purposes, so that in theory should have worked. 

One thing I would suggest is adding a use statement to ensure the facade is being called rather than the Mapper class itself.

Another idea I can think of is running a 'composer dump-autoload' -o to ensure the autoloader has been generated successfully.

**Comment by bradcornford** [comment]
I've setup a clean installation of Laravel 5.1, and added Googlmapper to the composer json require block.

I then added the below to the providers array:
```
Cornford\Googlmapper\MapperServiceProvider::class,
```

I then added the below to the aliases array:
```
'Mapper'    => Cornford\Googlmapper\Facades\MapperFacade::class,
```

I then edited the default route to:
```php
Route::get('/', function () {
    dd(Mapper::map(53.381128999999990000, -1.470085000000040000));
});
```

**Comment by willycornelissen** [comment]
Thank you Brad. I will work on this.

**Comment by bradcornford** [comment]
Have you had an luck with this issue?

**Comment by willycornelissen** [comment]
Yes, thank you Brad!

**Comment by rcaf** [comment]
I did everything that you discussed, but I have an error with this code:

```
dd(Mapper::map(53.381128999999990000, -1.470085000000040000));
```

Non-static method Cornford\Googlmapper\Mapper::map() should not be called statically, assuming $this from incompatible context

I'm using Laravel 5.1.24
