### ISSUE TITLE
circle event radius_changed

### ISSUE THREAD

**Issue by giresse21** [bradcornford/Googlmapper#60]
hi, how can i get the new radius and center of circle when radius or center changed
thanks

**Comment by bradcornford** [comment]
Hi there,

I will need to push a change to allow shapes to be visible externally. I am on with this change now, and will report back with usage.

**Comment by bradcornford** [comment]
Okay, i've pushed a change and versioned it as v2.12.0/v1.8.0, with the require changes. 

You can achieve what you need with the following:

```php

Mapper::map(53.3, -1.4, ['eventAfterLoad' => 'circleListener(maps[0].shapes[0].circle_0);']);


```

```html

<script type='text/javascript'>

function circleListener(circle) {
    circle.addListener('radius_changed', function()
    {
        console.log(circle.getRadius());
        console.log(circle.getCenter().lat());
        console.log(circle.getCenter().lng());
    });
    
    circle.addListener('center_changed', function()
    {
        console.log(circle.getRadius());
        console.log(circle.getCenter().lat());
        console.log(circle.getCenter().lng());
    });
}

</script>

```

**Comment by giresse21** [comment]
thank you very much
i am waiting for you

2016-07-27 8:43 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Does the above work for you?

**Comment by giresse21** [comment]
I have not yet tested,
i will give you a feedback

2016-07-27 13:31 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
hi Bradley,
it did not work

2016-07-27 13:33 GMT+01:00 arouna perez <giresseayefou@gmail.com>:

**Comment by giresse21** [comment]
are you missing something?

2016-07-27 15:04 GMT+01:00 arouna perez <giresseayefou@gmail.com>:

**Comment by bradcornford** [comment]
Have you run 'composer update cornford/googlmapper' ?

**Comment by giresse21** [comment]
yes i update my composer

here is my code in controller
$map=Mapper::map($response->getLatitude(), $response->getLongitude(),
['zoom' => 16,'draggable' => true, 'marker' => false],['eventAfterLoad' =>
'circleListener(maps[0].shapes[0].circle_0);'])->circle([['latitude' =>
$response->getLatitude(), 'longitude' => $response->getLongitude()]],
['editable' => 'true','draggable' => true,'strokeColor' => '#000000',
'strokeOpacity' => 0.1, 'strokeWeight' => 3, 'fillColor' => '#FFFFFF',
'radius' => $radius]);



2016-07-27 15:06 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Try this:

```php

$map=Mapper::map(
	$response->getLatitude(),
	$response->getLongitude(),
	[
		'zoom' => 16,
		'draggable' => true,
		'marker' => false,
		'eventAfterLoad' => 'circleListener(maps[0].shapes[0].circle_0);'
	]
)->circle(
	[
		[
			'latitude' => $response->getLatitude(),
			'longitude' => $response->getLongitude()
		]
	],
	[
		'editable' => 'true',
		'draggable' => true,
		'strokeColor' => '#000000',
		'strokeOpacity' => 0.1,
		'strokeWeight' => 3,
		'fillColor' => '#FFFFFF',
		'radius' => $radius
	]
);

```

**Comment by giresse21** [comment]
i try it
but the javascript function does not react

2016-07-27 15:12 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
​when I change the radius or center on map  nothing happens in
javascript function



2016-07-27 15:27 GMT+01:00 arouna perez <giresseayefou@gmail.com>:

**Comment by bradcornford** [comment]
I've just run the following, and it working as expected:

```php

use \Cornford\Googlmapper\Facades\MapperFacade as Mapper;

Route::get('/test', function () {

    Mapper::map(
        53.3,
        -1.4,
        [
            'zoom' => 16,
            'draggable' => true,
            'marker' => false,
            'eventAfterLoad' => 'circleListener(maps[0].shapes[0].circle_0);'
        ]
    )
        ->circle(
            [
                [
                    'latitude' => 53.3,
                    'longitude' => -1.4
                ]
            ],
            [
                'editable' => true,
                'draggable' => true,
                'strokeColor' => '#000000',
                'strokeOpacity' => 0.1,
                'strokeWeight' => 3,
                'fillColor' => '#FFFFFF',
                'radius' => 100
            ]
        );

    print Mapper::render();

    print "<script type='text/javascript'>
    
    function circleListener(circle) {
        circle.addListener('radius_changed', function()
        {
            console.log(circle.getRadius());
            console.log(circle.getCenter().lat());
            console.log(circle.getCenter().lng());
        });
    
        circle.addListener('center_changed', function()
        {
            console.log(circle.getRadius());
            console.log(circle.getCenter().lat());
            console.log(circle.getCenter().lng());
        });
    }
    
    </script>";
    
});

```

And received this in console:

```

/test:94 331.2584943954244
/test:95 53.3
/test:96 -1.3999999999999773
/test:94 502.5610827158245
/test:95 53.3
/test:96 -1.3999999999999773


```

**Comment by giresse21** [comment]
dit

Excuse me for disturbing you , when I move the circle on  map or
change the raduis , the console does not display anything. i run
composer update this time.

​

2016-07-27 15:43 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Can you provide your composer.json, your controller method, and view please. 

Just to confirm, does the map load?

**Comment by giresse21** [comment]
yes the map load very well with circle
the problem it was i drag circle change radius or center the javascript
function does not show the new raduis or center it look like the event
"eventAfterLoad" does not respond

2016-07-27 18:25 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
Route::get('/testtest', function () {

    Mapper::map(
        53.3,
        -1.4,
        [
            'zoom' => 16,
            'draggable' => true,
            'marker' => false,
            'eventAfterLoad' =>
'circleListener(maps[0].shapes[0].circle_0);'
        ]
    )
        ->circle(
            [
                [
                    'latitude' => 53.3,
                    'longitude' => -1.4
                ]
            ],
            [
                'editable' => true,
                'draggable' => true,
                'strokeColor' => '#000000',
                'strokeOpacity' => 0.1,
                'strokeWeight' => 3,
                'fillColor' => '#FFFFFF',
                'radius' => 100
            ]
        );

    print Mapper::render();

    print "<script type='text/javascript'>

    function circleListener(circle) {
        circle.addListener('radius_changed', function()
        {
            console.log(circle.getRadius());
            console.log(circle.getCenter().lat());
            console.log(circle.getCenter().lng());
        });

        circle.addListener('center_changed', function()
        {
            console.log(circle.getRadius());
            console.log(circle.getCenter().lat());
            console.log(circle.getCenter().lng());
        });
    }

    </script>";

});

2016-07-27 18:51 GMT+01:00 arouna perez <giresseayefou@gmail.com>:

**Comment by bradcornford** [comment]
What about your composer.json.

**Comment by giresse21** [comment]
2016-07-27 19:06 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Which version of Laravel are you using? If its 5.* can you also run:

```
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
```

**Comment by giresse21** [comment]
i use version 5.1
i already remove cornford googlImapper and install again,
it still does'nt work

2016-07-28 9:29 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
Hello,
I always unable to retrieve the new coordinates of the circle when I
edit the circle on the map.
don't you have another solution for me please . I don't understand why
it does not work.


2016-07-28 12:06 GMT+01:00 arouna perez <giresseayefou@gmail.com>:

**Comment by bradcornford** [comment]
Can you confirm you have run the following commands:

```
composer update cornford/googlemapper
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
```

**Comment by giresse21** [comment]
thank you very much
the comand php artisan vendor:publish
--provider="Cornford\\Googlmapper\\MapperServiceProvider"
was'nt copy the views in the ressources folder. i have it manually do and
everything work now.
thank you again

2016-08-01 11:45 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by bradcornford** [comment]
Did you receive an error when running the command?

**Comment by giresse21** [comment]
yes the first time
the errors was in my config/compile.php


2016-08-01 12:42 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
hi bradley, i am working in another project
when i do print Mapper::render(); in my controller the map appear
but when i do {!! Mapper::render() !!} in view nothing appear
how can i fix it

2016-08-02 14:21 GMT+01:00 Bradley Cornford <notifications@github.com>:

**Comment by giresse21** [comment]
sorry, it is work fine now

2016-08-03 14:44 GMT+01:00 arouna perez <giresseayefou@gmail.com>:
