### ISSUE TITLE
[Help] Add Directions and Link To Full Google Maps Page

### ISSUE THREAD

**Issue by KayTokyo** [bradcornford/Googlmapper#64]
Hi,

I am embedding an event location on my website. I'd like to give the users the opportunity to go to the  add direction AND/OR go to the google maps website to view the full page is it possible to do this with this plugin?

```
Mapper::location($event->address_postcode)->map(['zoom' => '10', 'center' => true, 'marker' => true, 'overlay' => 'ROADMAP']);
```

**Comment by bradcornford** [comment]
Hi there,

You could use information windows to display any data / links to relevant items you like, for example:

```php

$location = Mapper::location($event->address_postcode);

$location->map(['zoom' => '10', 'center' => true, 'marker' => false, 'overlay' => 'ROADMAP'])
    ->informationWindow($location->getLatitude(), $location->getLongitude(), '<a href="https://www.google.co.uk/maps/dir/Current%20Location/' . $location->getLatitude() . ',' . $location->getLongitude() . '/?dirflg=w|location" title="Directions">Directions</a>');

```

The second item is possible, but events would have to be used. This will require a option of event after load a section of JavaScript to enable the fullscreen control:

```php

Mapper::location($event->address_postcode)->map(['zoom' => '10', 'center' => true, 'marker' => true, 'overlay' => 'ROADMAP', 'eventAfterLoad' => 'maps[0].map.set("fullscreenControl", true);']);

```

I may look at natively allowing this option to be set in the future.

**Comment by bradcornford** [comment]
I have implemented the 'fullscreenControl' option in versions v2.13.0/v1.9.0. This can now be achieved as follows:

```php
Mapper::location($event->address_postcode)->map(['zoom' => '10', 'center' => true, 'marker' => true, 'overlay' => 'ROADMAP', 'fullscreenControl' =>true]);
```
