### ISSUE TITLE
map is displayed grey when I put it inside bootstrap modal

### ISSUE THREAD

**Issue by shgelenidze** [bradcornford/Googlmapper#66]
when I put {!! Mapper::render() !!} inside bootstrap modal, the map is displayed grey, so that I see only marker icon. I've tried

```
$('#myModal').on('shown.bs.modal', function () {
    google.maps.event.trigger(map, "resize");
});

```

in my js file, and many other things but nothing works, map starts working only if I press f12 on keyboard and show chrome developer tools.

any ideas?

thanks

**Comment by bradcornford** [comment]
Hi there,

Can you possible send over you view, so i can test it myself. What version of Laravel are you using? Also what browser are you using?

**Comment by bradcornford** [comment]
Your code is a little off too:

```js
$('#myModal').on('shown.bs.modal', function () {
    google.maps.event.trigger(maps[0].map, "resize");
});
```

**Comment by shgelenidze** [comment]
in Controller I have following:
`
    public function showRegions(){
      $regions=Regions::paginate(3);
      Mapper::map(42.5151079,41.8381684,['draggable' => true,'eventClick' => '$("#region_lng").val(this.position.lng()); $("#region_lat").val(this.position.lat());']);
      return view('locations.regions', ['regions' => $regions] );
    }
`
in View I have following:

`
                  
                  <div id="myModal" class="modal fade" role="dialog">
                    <div class="modal-dialog modal-lg">
                      
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">{{trans('language-main.MARKONMAP')}}</h4>
                        </div>
                        <div class="modal-body">
                          <p>
                            <div id="map">{!! Mapper::render() !!}</div>
                          </p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">{{trans('language-main.CLOSE')}}</button>
                        </div>
                      </div>
                    </div>

                  </div>

                  <div class="form-group">
                      <label for="map_modal" class="col-md-4 control-label">
                        {{trans('language-main.MARKONMAP')}}
                      </label>
                      <div class="col-md-6">
                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">{{trans('language-main.MARKONMAP')}}</button>
                      </div>
                  </div>


                  <div class="form-group{{ $errors->has('region_lat') ? ' has-error' : '' }}">
                      <label for="region_lat" class="col-md-4 control-label">{{ trans('language-main.LATITUDE') }}</label>
                      <div class="col-md-6">
                          <input id="region_lat" type="text" class="form-control" name="region_lat" value="{{ old('region_lat') }}">
                          @if ($errors->has('region_lat'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('region_lat') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  <div class="form-group{{ $errors->has('region_lng') ? ' has-error' : '' }}">
                      <label for="region_lng" class="col-md-4 control-label">{{ trans('language-main.LONGITUDE') }}</label>
                      <div class="col-md-6">
                          <input id="region_lng" type="text" class="form-control" name="region_lng" value="{{ old('region_lng') }}">
                          @if ($errors->has('region_lng'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('region_lng') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>

`

Although I find Out that if I add 

'
$('#myModal').on('shown.bs.modal', function () {
  google.maps.event.trigger(maps[0].map, 'resize');
});

OR


$('#myModal').on('shown.bs.modal', function () {
  initialize_0();
});

'

It is working

**Comment by bradcornford** [comment]
Okay, ill see if i can replicate, What version of Laravel are you using? Also what browser are you using?

**Comment by shgelenidze** [comment]
I'm using Laravel Framework version 5.2.41

browser Google Chrome Version 52.0.2743.116 , but I've tested it on Mozilla as well as Microsoft Edge and Internet Explorer, the result was the same

**Comment by bradcornford** [comment]
I've recreated the issue, i believe because the map is rendered when the modal is set to display none, causing the map to render incorrectly. I cant seem to fix this without calling the resize method once its display block.

**Comment by bradcornford** [comment]
I'm going mark this as invalid, as i don't think this is currently something that the plugin is capable of fixing. Due to the way in which the modals are created and rendered.

Gkad you got it work though!
