### ISSUE TITLE
Show only my current location

### ISSUE THREAD

**Issue by reals79** [bradcornford/Googlmapper#67]
Hi,
I can show only my current location in browser?
Because now the results displayed of which only are specified in the Mapper::map(lat, lng), and after loading the map is centered in my current position (of course with option 'locate' => true in config file), but only the marker is set where it is set in the Mapper::map(lat, lng). I need to see marker only in my current position. Its possible?

Thank you.

**Comment by bradcornford** [comment]
Hi,

Yes, this would be possible, however you would have to write something custom in JavaScript to achieve this, as your current location is parsed by the server. However something like below would work:

```php
Mapper::location('Sheffield')->map(['zoom' => 18, 'center' => true, 'eventAfterLoad' => 'onMapLoad(maps[0].map);']);
```

```html
<script type="text/javascript">
    
    function onMapLoad(map)
    {   
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                            
                    var marker = new google.maps.Marker({
                      position: pos,
                      map: map,
                      title: "Location found."
                    });
                    
                    map.setCenter(pos);
                }
            );
        }
    }
</script>
```

**Comment by reals79** [comment]
Thanks. Its works.
But one small problem: I can't remove zero marker from map.
var marker = maps[0].markers[0];
marker.setMap(null);

Can something suggest?

**Comment by bradcornford** [comment]
Try this:

```php
Mapper::location('Sheffield')->map(['zoom' => 18, 'center' => true, 'marker' => false, 'eventAfterLoad' => 'onMapLoad(maps[0].map);']);
```

**Comment by reals79** [comment]
Thank you so much! That's works.

**Comment by bradcornford** [comment]
That's okay, glad its working for you.

**Comment by Strayko** [comment]
> 
> 
> Hi,
> 
> Yes, this would be possible, however you would have to write something custom in JavaScript to achieve this, as your current location is parsed by the server. However something like below would work:
> 
> ```
> Mapper::location('Sheffield')->map(['zoom' => 18, 'center' => true, 'eventAfterLoad' => 'onMapLoad(maps[0].map);']);
> ```
> 
> ```
> <script type="text/javascript">
> 
>     function onMapLoad(map)
>     {   
>         if (navigator.geolocation) {
>             navigator.geolocation.getCurrentPosition(
>                 function(position) {
>                     var pos = {
>                         lat: position.coords.latitude,
>                         lng: position.coords.longitude
>                     };
> 
>                     var marker = new google.maps.Marker({
>                       position: pos,
>                       map: map,
>                       title: "Location found."
>                     });
> 
>                     map.setCenter(pos);
>                 }
>             );
>         }
>     }
> </script>
> ```

Mapper::location() goes to Route::post() because i search cities on search, but where is goes JS code on wich page? I put it on the home page and search page, nothing happend?

**Comment by bradcornford** [comment]
@Strayko You would need to put the above script on the page in which is displaying the map.
