### ISSUE TITLE
No map found to add markers

### ISSUE THREAD

**Issue by jpmurray** [bradcornford/Googlmapper#68]
Hello!

Trying to use your example to add markers results in a ` no map found to add markers error`.

(This is the code I tried from your readme)
```
Mapper::marker(53.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['symbol' => 'circle', 'scale' => 1000]);
Mapper::map(52.381128999999990000, 0.470085000000040000)->marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']]);
```

I tried another time, this time with my own locations, just to try and it still gives the same error.

```
Mapper::map(46.8137424, -71.2258207, ['zoom' => 17, 'markers' => ['title' => 'My title', 'animation' => 'DROP']])
            ->marker(52.9399159,-73.5491361);
```

What's more, that last example, the initial marker will show, but not the added one. Am I doing something wrong?

**Comment by bradcornford** [comment]
Hi there,

You have to create a map, before adding markers to it. The below should work:

```php
Mapper::map(52.381128999999990000, 0.470085000000040000)->marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']]);
Mapper::marker(53.381128999999990000, -1.470085000000040000);
Mapper::marker(53.381128999999990000, -1.470085000000040000, ['symbol' => 'circle', 'scale' => 1000]);
```

**Comment by jpmurray** [comment]
AH! My bad, I really blidnly followed the readme, and the `mapper:map` method was placed after the `mapper:marker` one! :)

![screen shot 2016-08-16 at 15 20 40](https://cloud.githubusercontent.com/assets/1550428/17712697/1b11bc7e-63c5-11e6-9469-cf327b75655a.png)

**Comment by bradcornford** [comment]
Ah yes, was just trying to show the different ways to call the marker method. Glad its working for you!
