### ISSUE TITLE
i need to use one map to display more than place

### ISSUE THREAD

**Issue by engsamar** [bradcornford/Googlmapper#74]
i need to use one map to display more than place ,, can u help me ,please :)

**Comment by bradcornford** [comment]
Hi there,

Can explain what exactly you are trying to achieve, I don't understand from your previous comment.

**Comment by engsamar** [comment]
i have more than latitude and longitude ,i want to them on one map 
i tried but every address make map such as
![screenshot at 2016-08-28 14-17-01](https://cloud.githubusercontent.com/assets/16509556/18033623/5d63d418-6d2a-11e6-9e2b-ad10cc3d7241.png)

i want them on one map

**Comment by bradcornford** [comment]
Create a map for the first latitude, then add a marker for each location you want to display.

**Comment by engsamar** [comment]
i try but display the first place only 
```
Mapper::map($lat[0],$long[0],['strokeColor' => '#000000', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF','markers' => ['title' =>'Driver Name' , 'animation' => 'DROP'],'clusters' => ['size' => 10, 'center' => true, 'zoom' => 20],'zoom' => 16]);
        for($i=0;$i<count($lat);$i++){
           // echo $lat[$i],$long[$i];

         Mapper::marker($lat[$i],$long[$i]);
        }
```

**Comment by engsamar** [comment]
how can i display information about each place

**Comment by bradcornford** [comment]
That code snippet looks correct. You could make them information windows, then add content to them.

**Comment by engsamar** [comment]
Thank a lot for your help ,, ^_^
it is very useful for me

**Comment by engsamar** [comment]
how can make direction with start latitude and end latitude

**Comment by bradcornford** [comment]
Here is some information on that, see: https://github.com/bradcornford/Googlmapper/issues/64

**Comment by engsamar** [comment]
`    foreach($drivers_last_locations as $drivers_last_location){
        if($drivers_last_location->status=="on"){
        array_push($long,$drivers_last_location->last_long);
        array_push($lat,$drivers_last_location->last_lat);
        array_push($name,$drivers_last_location->driver_id);
        }
          if($drivers_last_location->status=="off"){
        array_push($long_off,$drivers_last_location->last_long);
        array_push($lat_off,$drivers_last_location->last_lat);
        }
          if($drivers_last_location->status=="busy"){
        array_push($long_busy,$drivers_last_location->last_long);
        array_push($lat_busy,$drivers_last_location->last_lat);
        }
      }

         Mapper::map($lat[0],$long[0],['strokeColor' => '#003400', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#65638ea','clusters' => ['size' => 10, 'center' => true, 'zoom' => 20],'zoom' => 8]);

        
        for($i=0;$i<count($lat);$i++){
           // echo $lat[$i],$long[$i];
         Mapper::marker($lat[$i],$long[$i],['markers' => ['title' =>'Online','symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']])->informationWindow($lat[$i],$long[$i],"echo $name[$i];", ['markers' => ['animation' => 'DROP']])->rectangle([['latitude' => $lat[$i], 'longitude' => $long[$i]], ['latitude' => $lat[$i], 'longitude' => $long[$i]]], ['strokeColor' => '#ea234a', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
        }
                for($i=0;$i<count($lat_off);$i++){
           // echo $lat[$i],$long[$i];

         Mapper::marker($lat_off[$i],$long_off[$i],['markers' => ['title' =>'Offline','symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']])->informationWindow($lat_off[$i],$long_off[$i],"$long_off[$i]", ['markers' => ['animation' => 'DROP']]);
        }

        for($i=0;$i<count($lat_busy);$i++){
           // echo $lat[$i],$long[$i];

         Mapper::marker($lat_busy[$i],$long_busy[$i],['markers' => ['title' =>'Busy','symbol' => 'rectangle', 'scale' => 1000, 'animation' => 'DROP']])->informationWindow($lat_busy[$i],$long_busy[$i],"Hi", ['markers' => ['animation' => 'DROP']]);
        }`

i want each group take color and display data such as name but it is varaible

**Comment by bradcornford** [comment]
Hi,

You dont need to create a marker and an information window. An information window will add a marker to the map itself. The below should achieve what you want:

```php
for($i=0;$i<count($lat);$i++){
	Mapper::informationWindow($lat[$i],$long[$i], "{$name[$i]}", ['markers' => ['title' =>'Online', 'symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']])
	->rectangle([['latitude' => $lat[$i], 'longitude' => $long[$i]], ['latitude' => $lat[$i], 'longitude' => $long[$i]]], ['strokeColor' => '#ea234a', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
}
```
