### ISSUE TITLE
No Popups if I click on Marker

### ISSUE THREAD

**Issue by mikeberb** [bradcornford/Googlmapper#76]
Awesome project, Thanks!
How I can display the information pop up (Info windows)  when I click on a marker.!
Do I missing something?
I am on L5.2

Thanks 
Mike

**Comment by mikeberb** [comment]
My mistake.!
I used Mapper::informationWindow($la, $lo, 'content');

Everything is working
Thanks again mate

Mike

**Comment by bradcornford** [comment]
Sorry its taken me a while to reply. Glad you got this working.
