### ISSUE TITLE
How to dismiss previously opened info window?

### ISSUE THREAD

**Issue by akosijiji** [bradcornford/Googlmapper#77]
Hi @bradcornford 
How can we dismiss previously opened info window to display another info window?

Here's my code:

foreach ($customers as $c) {
Mapper::informationWindow($space->latitude, $space->longitude,
          'Content', ['open' => true, 'markers' => ['title' => 'Title']]);
}

**Comment by bradcornford** [comment]
Hi there,

I'll look at ways to implement this feature.

**Comment by akosijiji** [comment]
@bradcornford thanks! Looking forward to it.

**Comment by bradcornford** [comment]
Some code along the lines of:

```js
var infowindows = [];

infowindows.push(infowindow_{!! $id !!}); 

for (var i = 0; i < infowindows.length; i++) {
    infowindows[i].close();				
}
```

**Comment by bradcornford** [comment]
This has now been implemented in current version 2.18.0/1.14.0.

I can be used on either a map as a whole:


```

Mapper::map(53.3, -1.4, ['cluster' => true, 'zoom' => 10, 'center' => false, 'markers' => ['title' => 'My Location', 'animation' => 'DROP', 'autoClose' => true]]);

```

Or on each individual marker:

```

Mapper::informationWindow(51.4, -0.5, 'Content', ['autoClose' => true]);

```

**Comment by akosijiji** [comment]
@bradcornford if you don't mind how do I update this change?

**Comment by bradcornford** [comment]
Hi there,

On your map method, add a markers array that contains the key autoClose and the value true.

For example:

```php
Mapper::map (1, 1, ["markers" => ["autoClose" => true]]);

```

**Comment by akosijiji** [comment]
@bradcornford yeah I added autoclose to markers. However, I'm not getting any result.

**Comment by bradcornford** [comment]
Have you run composer update?

**Comment by akosijiji** [comment]
@bradcornford yeah I have.

**Comment by bradcornford** [comment]
What do you have in your controller?

**Comment by akosijiji** [comment]
@bradcornford here's a snippet of my code: 

Mapper::map($lat,
        $long, ['center' => true, 'marker' => false,
            'type' => 'ROADMAP', 'overlay' => 'TRAFFIC']);

      foreach ($records as $record) {
          Mapper::informationWindow($record->latitude, $record->longitude,
          '<div id="content">' .
            '<a href="/view/' . $record->id . '"><h5><b>' . $record->location . '</b></h5></a>' .
            '<div>' .
              '<div class="wrapper">
                  <a href="/view/' . $record->id . '"><img src="../'. $record->img . '" width="150px" height="100px" >
                  </a>
               </div> <br />'.
            '</div>' .
          '</div>', ['open' => true, 'markers' => ['title' => $space->area], ['autoClose' => true]]);
      }

**Comment by bradcornford** [comment]
You need to move the auto close into the markers array.

**Comment by akosijiji** [comment]
@bradcornford I did that but didn't work as well

**Comment by bradcornford** [comment]
What version of the package are you running?

**Comment by akosijiji** [comment]
@bradcornford what package do you refer to? Sorry not familiar

**Comment by bradcornford** [comment]
This package.

**Comment by bradcornford** [comment]
Okay, so i've tested this at versions 2.19.0/1. When an information window is open, and another is clicked, all information windows are closed, and the clicked marker displays its information window. I tested this with the following, and its working as expected:

```php

Mapper::map(53.3, -1.4, ['cluster' => false, 'zoom' => 10, 'markers' => ['title' => 'My Location', 'autoClose' => true]]);

Mapper::informationWindow(53.4, -1.5, 'Content 1');
Mapper::informationWindow(52.4, -1.0, 'Content 2');
Mapper::informationWindow(51.4, -0.5, 'Content 3');

Mapper::render();

```

**Comment by akosijiji** [comment]
@bradcornford my current version is 2.*

**Comment by bradcornford** [comment]
Can you send me your controller and view please.

**Comment by akosijiji** [comment]
@bradcornford here's my controller:

`Mapper::map($lat,
    $long, ['center' => true, 'marker' => false,
        'type' => 'ROADMAP', 'overlay' => 'TRAFFIC']);

  foreach ($records as $record) {
      Mapper::informationWindow($record->latitude, $record->longitude,
      '<div id="content">' .
        '<a href="/view/' . $record->id . '"><h5><b>' . $record->location . '</b></h5></a>' .
        '<div>' .
          '<div class="wrapper">
              <a href="/view/' . $record->id . '"><img src="../'. $record->img . '" width="150px" height="100px" >
              </a>
           </div> <br />'.
        '</div>' .
      '</div>', ['open' => true, 'markers' => ['title' => $space->area], ['autoClose' => true]]);
  }`

View: 

`<div class="col-sm-12">
        <div id="map-holder">
          {!! Mapper::render(0) !!}
        </div>
      </div>`

**Comment by bradcornford** [comment]
Update your controller as follows:

```php
Mapper::map($lat, $long, ['center' => true, 'marker' => false, 'type' => 'ROADMAP', 'overlay' => 'TRAFFIC', 'markers' => ['autoClose' => true]]);
```

```php
foreach ($records as $record) {
      Mapper::informationWindow($record->latitude, $record->longitude,
      '<div id="content">' .
        '<a href="/view/' . $record->id . '"><h5><b>' . $record->location . '</b></h5></a>' .
        '<div>' .
          '<div class="wrapper">
              <a href="/view/' . $record->id . '"><img src="../'. $record->img . '" width="150px" height="100px" >
              </a>
           </div> <br />'.
        '</div>' .
      '</div>', ['open' => true, 'markers' => ['title' => $space->area]]);
  }
```

**Comment by akosijiji** [comment]
Still not working :(

**Comment by bradcornford** [comment]
Out of interest what are you expecting to happen? As you have all markers open already?
