### ISSUE TITLE
Passing a $variable on Information Window

### ISSUE THREAD

**Issue by mikeberb** [bradcornford/Googlmapper#79]
Hi @bradcornford,

How can I pass a variable to display information on Info window
Here is my code
``Mapper::informationWindow( $customer->Latitude, $customer->Longitude,'$variable');``

This way does not work. Just writes $variable on Info Window

Thanks

**Comment by bradcornford** [comment]
Hi there,

You can pass it as you would normally to a method, such as:

```php
Mapper::informationWindow( $customer->Latitude, $customer->Longitude, $variable);
```

**Comment by mikeberb** [comment]
Thank you for you reply,
Forgive my ignorance but I am unable to do it..
With the following code the Info Window does not popup at all
`$name = $user->name;`
`Mapper::informationWindow($user->Latitude, $user->Longitude, $name);`

With the following code the Info window does popup but it is saying $user->name and not the value.
`$name = '$user->name';`
`Mapper::informationWindow($user->Latitude, $user->Longitude, $name);`
					
Kind Regards.
