### ISSUE TITLE
Nothing to publish for tag

### ISSUE THREAD

**Issue by tanhs** [bradcornford/Googlmapper#8]
I tried to publish in laravel 5 but I getting this error.

c:\xampp\htdocs\laravel>php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
Nothing to publish for tag [].

**Comment by bradcornford** [comment]
Can you try this:

```
php artisan vendor:publish --provider="Cornford\\Googlmapper\\MapperServiceProvider"
```

**Comment by tanhs** [comment]
still the same

**Comment by bradcornford** [comment]
What version of Laravel are you using?

**Comment by tanhs** [comment]
laravel 5

**Comment by bradcornford** [comment]
5.0? 5.1? 5.2?

**Comment by bradcornford** [comment]
Try the below:

```
php artisan vendor:publish --tag=googlmapper
```

```
php artisan vendor:publish --tag=googlmapper  --provider="Cornford\\Googlmapper\\MapperServiceProvider"
```

**Comment by tanhs** [comment]
Laravel Framework version 5.1.10 (LTS)
php artisan vendor:publish --tag=googlmapper
solved my problem.  tq.
