### ISSUE TITLE
markerclusterer.js not always included when needed.

### ISSUE THREAD

**Issue by leewillis77** [bradcornford/Googlmapper#80]
If you set clustering off by default in config/googlmapper.php, but then turn on clustering for a specific map, e.g. 

```
Mapper::map(
            $lat,
            $lng,
            [
                'cluster' => true
            ]
        );
```

Then the JS will attempt to create a clusterer with:
```
var markerCluster = new MarkerClusterer(map_0, markers, markerClusterOptions);
```

However MarkerClusterer will not exist as the JS file is only included if the default options have clustering on, leading to no clustering and the following error in the console:

Uncaught ReferenceError: MarkerClusterer is not defined

**Comment by bradcornford** [comment]
Hi there,

I've looked into this, and i can see three solutions:

- The first would be to include the marker cluster js by default as each map sets up its own marker cluster options.

- Alternatively each map could render the marker cluster js for themselves if the cluster setting is true. 

- Finally, i could merge map configuration with mappers configuration, and then keep the rest of the implementation the same.

I'm more inclined to go with the first option, as it doesn't really add too much load in general. What are your thoughts?

**Comment by leewillis77** [comment]
Hi Brad; 

Option 1 is definitely the easiest - in fact that's what I'm doing right now in my local instance of the view. However - it's definitely not the "best" approach. Creating additional requests for no good reason is "Bad". 

Option 2 could easily lead to duplicate output if you had > 1 map with clustering enabled. 

Option 3 seems like the right solution, and sounds like it would address other issues that might come up in a similar vein?

**Comment by bradcornford** [comment]
Yeah i do agree its bad in practice. I did have a similar thought too, but thinking about it more, it would have to merge configurations from each of its children items, but only in the case where an option is different to the default configuration value.

**Comment by leewillis77** [comment]
Is there any way you could do option [2] but avoid duplicates by somehow keeping track of whether the JS has already been included by another map? [Sorry - not familiar with the internals enough to suggest specifics!]

**Comment by bradcornford** [comment]
I'm just looking into option three at the moment, as i agree it would be the best solution. The others all fall short in some respect.

**Comment by bradcornford** [comment]
Okay, i've put something together in the develop branch, if you want to check it out and give it a whirl.

**Comment by leewillis77** [comment]
Hi Brad; 

Develop branch works for me without any local changes - thanks!

**Comment by bradcornford** [comment]
Excellent, i'll get this merged into a bugfix version soon.

**Comment by bradcornford** [comment]
All previous versions have now been back patched.
