### ISSUE TITLE
Using Polyline

### ISSUE THREAD

**Issue by mikeberb** [bradcornford/Googlmapper#81]
Hi, @bradcornford ,

I am trying to implement the  Polyline feature.
Here is my code..

`$points    = TrackingData::where('gpson', 1)->get();`
`foreach($points as $point ){`
`Mapper::polyline([['latitude' => $point->Latitude, 'longitude' => $point->Longitude], ['latitude' => $point->Latitude, 'longitude' => $point->Longitude]]);`

Unfortunately this way I am only getting all the points on map but without the drawing line. I am getting only dots.

Any help will be appreciated

**Comment by bradcornford** [comment]
Hi there,

It looks to me like your drawing a line from the current location to the current location. 

The first array in the containing array is the starting location, the second array in the containing array is the ending location.

See the example below:

```php
Mapper::map(53.3, -1.4, ['zoom' => 10, 'center' => false]);

Mapper::polyline([['latitude' => 53.4, 'longitude' => -1.5], ['latitude' => 52.4, 'longitude' => -1.0]]);
```

**Comment by mikeberb** [comment]
Yes you are right I am ..
And what if I want to draw a line using a lot of points..? 
In your example you are using only 2 points.

Thanks

**Comment by bradcornford** [comment]
You can keep adding to the array. For example:

```php
Mapper::polyline([['latitude' => 53.4, 'longitude' => -1.5], ['latitude' => 52.4, 'longitude' => -1.0], ['latitude' => 51.4, 'longitude' => -0.5]]);
```

**Comment by bradcornford** [comment]
So for what you are trying to achieve, try this:

```php
$points = [];

foreach(TrackingData::where('gpson', 1)->get() as $point){
    $points[] = ['latitude' => $point->Latitude, 'longitude' => $point->Longitude];
}

Mapper::polyline($points);

```

**Comment by mikeberb** [comment]
You are  awesome mate.! ;)
Thank you very much for this.
