### ISSUE TITLE
Return location of draggable marker based on current location.

### ISSUE THREAD

**Issue by Mrkars** [bradcornford/Googlmapper#83]
Hi,

So I would like to return the location of a marker after it has been dragged, also this marker is originally created based on the users location. I have the code working up to this point:

https://github.com/bradcornford/Googlmapper/issues/67

I was able to set the marker as draggable in in the JS function you provided by adding 'draggable: true'.

I'm assuming I'm also going to need to add 'eventDragEnd' and provide another JS function that will be called? Once here I'm also not sure how I could reference the final position of the marker?

Let me know if this is doable with the current state of the framework, thanks for your time.

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply!

Yes this is possible, and you care correct, you can use the event 'eventDragEnd':


```php

Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventDragEnd' => 'console.log(event.latLng.lat()); console.log(event.latLng.lng());']);

```

**Comment by bradcornford** [comment]
Did the above work for you?

**Comment by Mrkars** [comment]
Hey Brad,

Sorry for not responding, we ended up going in a completely different direction. So I'm not sure what the outcome would be.

Thanks for your time!

**Comment by bradcornford** [comment]
Okay. No worries.
