### ISSUE TITLE
assuring that google maps main api script gets loaded once for each page 

### ISSUE THREAD

**Issue by akramabdulrahman** [bradcornford/Googlmapper#84]
![image](https://cloud.githubusercontent.com/assets/1550238/19021447/0763fe92-88ca-11e6-8b35-4631442e0846.png)

this happened after i did a map->render() for multiple items in the page. i have each model presenter rendering their own version of google maps 
, my solution so far is removing the map importing part to the layout file 
the most proper solution i think is making it a part of the config and including that into whatever layout file just by including a partial view

**Comment by bradcornford** [comment]
Hi there,

I'll look into this, it may be that I have to implement a separate method to introduce the required JS files, which then disabled the automatic inclusion of the JS when calling render.

**Comment by akramabdulrahman** [comment]
to solve this , i got my script tags in a a separate view , and i would manually include the js file in each view or layout that has google maps , the problem is that i have to always put the js files in the head of the page because all scripts are written within page . 
one improvement for version two is generating js files and including injecting them to the page :D

**Comment by bradcornford** [comment]
Okay, so i've put something together on the develop branch of you want to check that out and give it a whirl.

**Comment by bradcornford** [comment]
I have now merged this into master, under current versions v2.17.0/v1.13.0.
