### ISSUE TITLE
"An error occurred performing the location search." is not very specific

### ISSUE THREAD

**Issue by ksdev-pl** [bradcornford/Googlmapper#86]
Hi

I'm using such a fragment to later show the map:
```php
\Mapper::location($company->address)->map(['zoom' => 10]);
```
And the map shows great, everything OK.

But when there is a problem an exception is thrown with such a message: "An error occurred performing the location search.". This message doesn't tell me anything specific, especially when the client send me this message and I have no access to the server.

The real problem description is for example: "The provided API key is invalid." with status code, etc. You can search for such a problem in google documentation.

Am I doing something wrong and is it possible to get a real problem description without forking this package and changing the Mapper class (lines ~111, where the exception is thrown)?

Thanks for your work.

**Comment by bradcornford** [comment]
The location method does throw different exceptions based on the results it receives, however it doesn't currently throw a certain exception for invalid api key, i will implement this. I will also separate the exception thrown for invalid status codes into a new exception type rather than re-using the current MapperSearchResultException exception, which will also show the error message Google provide if one exists.

Below are the current exception throw:

```
MapperArgumentException
MapperSearchException
MapperSearchLimitException
MapperSearchResultException
MapperException
```

Below are the new exceptions that i will create:

```
MapperSearchKeyException
MapperSearchResponseException
```

**Comment by bradcornford** [comment]
I have now pushed this work to the develop branch if you want to see the change before it gets versioned and merged into master.

**Comment by bradcornford** [comment]
Does the change on develop look okay? Will this solve your issue?

**Comment by ksdev-pl** [comment]
Thank you for the answer, I cannot check it until evening, I will let you know.

Btw. there is also for example such an error hidden under "An error occurred performing the location search":

>This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https:\/\/console.developers.google.com\/apis\/api\/geocoding_backend?project=_

The raw message from google is helpful.

**Comment by bradcornford** [comment]
With the error_message field noted by Google as "Note: This field is not guaranteed to be always present, and its content is subject to change." i don't really want to tie to many of these to throw exceptions. I think it would be easier to just show the error_message response if it exists.

**Comment by bradcornford** [comment]
I have now merged this into current versions v2.19.0/v1.15.0.

**Comment by ksdev-pl** [comment]
Updated version works great, the message is helpful now. Thank you very much!

**Comment by bradcornford** [comment]
Great, glad it's useful! Does make a lot more sense to display a more specific message.
