### ISSUE TITLE
Multiple Mapper::Render in different containers

### ISSUE THREAD

**Issue by M-Blobby** [bradcornford/Googlmapper#87]
Thanks for your API, it works like a charm. But now I would like to insert 2 maps, each of them in different `<div>` (I'm using Laravel 5.3).

My controller has :
```
foreach ($items as $item) {
     Mapper::map($item->latitude, $item->longitude);
}
```
And my view :
```
@foreach($items as $item)
    <div class="location-map">
         {!! Mapper::render () !!}
    </div>
@endforeach
```
But now I see my maps only visibles in the first div. There is an easy way to do that ?

**Comment by M-Blobby** [comment]
Sorry, I find the solution just after to publish my issue ... It was well mentionned in the readme : 

> The render method allows all maps to be rendered to the page, this method can be included in Views or added as controller passed parameter, and optional parameter for item.

```
Mapper::render();
Mapper::render(0);
```

**Comment by bradcornford** [comment]
Glad you figured it out. I would just add a key to your foreach in the view, and pass that to the render method. For example:

@foreach ($items as $key => $item)

{!! Mapper::render ($key) !!}

@endforeach
