### ISSUE TITLE
how can make map clickable 

### ISSUE THREAD

**Issue by engsamar** [bradcornford/Googlmapper#88]
i want to click on marker to redirect another page ,
and i want to make such as in pic 
![14803123_937131683085910_2115434706_o](https://cloud.githubusercontent.com/assets/16509556/19626829/b990a6c2-9939-11e6-8c98-f5d88c39e50d.jpg)

**Comment by bradcornford** [comment]
Hi there,

This should be possible with styling, and information windows. There is a setting variable 'markers.icon' which allows a path to an image for a marker.

**Comment by bradcornford** [comment]
Did this work for you?
