### ISSUE TITLE
Maps Async

### ISSUE THREAD

**Issue by akosijiji** [bradcornford/Googlmapper#90]
Hello @bradcornford can you give me instructions how to set async defer in the javascript? Currently, GMaps is displaying so slow on my webpage. Hoping to hear from you. Regards.

**Comment by bradcornford** [comment]
Hi there, you can update the template javascript.blade.php and add the attributes async defer to it. See: https://developers.google.com/maps/documentation/javascript/tutorial

**Comment by akosijiji** [comment]
@bradcornford thanks. I added the async defer attribute here:

`@if (!$view->shared('javascript', false))

    @if ($view->share('javascript', true)) @endif

    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v={!! $options['version'] !!}&region={!! $options['region'] !!}&language={!! $options['language'] !!}&key={!! $options['key'] !!}&signed_in={!! $options['user'] ? 'true' : 'false' !!}&libraries=places" async defer></script>

    @if ($options['cluster'])

        <script type="text/javascript" src="//googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js" async defer></script>

    @endif

@endif
`

But when I inspect element the attribute is not added.

**Comment by bradcornford** [comment]
Okay, now update the mapper.balde.php include line to:

```php
@include('cornford.googlmapper.javascript')
```

**Comment by akosijiji** [comment]
@bradcornford I've done this but not effect at all. FYI, am I updating the correct file? vendor>cornford>src>views>javascript.blade.php

**Comment by bradcornford** [comment]
No it should be in your resources views folder.

**Comment by bradcornford** [comment]
I have now added this to current versions 2.20.0 / 1.16.0. A configuration key of 'async' can be set globally via config, or set on a map creation using the same key as a parameter, using a boolean value.
