### ISSUE TITLE
Rendering map in bootstrap inactive tabs not working.

### ISSUE THREAD

**Issue by lckamal** [bradcornford/Googlmapper#92]
If the tab where googlmapper is rendered is hidden by default, the map won't work after clicking the tab.

**Comment by bradcornford** [comment]
Hi there,

Sorry for the late reply!

This is a know issue around using Google Maps and Bootstrap tabs.

Here is a solution. Replace the '#profile' with the href for the tabpanel with the map:

```html

<script type="text/javascript">

$('a[href="#profile"]').on('shown.bs.tab', function(e)
    {
        google.maps.event.trigger(maps[0].map, 'resize');
    });
</script>

```

**Comment by bradcornford** [comment]
Did this work for you?
