### ISSUE TITLE
Making mapper responsive with bootstrap

### ISSUE THREAD

**Issue by TheRavingViking** [bradcornford/Googlmapper#95]
Hi There,

I've been trying to get mapper working on a responsive website with bootstrap, the code works and I get to see the map when I add height and width like this:

        <div style="height: 576px; width: 1024px;">
            {!! Mapper::render () !!}
        </div>

I would like to make the map responsive like the usual way.

example:

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {!! Mapper::render () !!}
            </div>
        </div>
    </div>

If i use this way off bootstrap it does not show the map, how is this possible?

thanks in advance

**Comment by bradcornford** [comment]
Hi there,

This is a common problem with Google Maps, for some strange reason they require a width / height being set to display the map, rather than taking it from the container.

Try this:

```

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="embed-responsive embed-responsive-16by9">
            <div id="map_canvas" class="embed-responsive-item">
                {!! Mapper::render () !!}
            </div>
        </div>
    </div>
</div>

```

**Comment by TheRavingViking** [comment]
Ah yes! you're the best! thank you so much!
