### ISSUE TITLE
I have a problem with Googlmapper

### ISSUE THREAD

**Issue by shooter27** [bradcornford/Googlmapper#96]
Hi everyone! Could you somebody help me with my issue please?
When I use URL with additional parameters everything is ok. For example
Route::get('exits', 'HomeController@exits');
and it's working

BUT  when I use parameter  Route::get('exits/{code}', 'HomeController@exits');  - the map is there, BUT markers are not.

 ```
public function exits(Request $request){
    
    	Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 10, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 'clusters' => ['size' => 10, 'center' => true, 'zoom' => 20]]);
        
    	return view('front.exitinfo');
    }
```

Thanks

**Comment by bradcornford** [comment]
Hi there,

Try adding the parameter marker with the value true to your input array:

```
Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 10, 'marker' => true, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 'clusters' => ['size' => 10, 'center' => true, 'zoom' => 20]]);
       
```

**Comment by bradcornford** [comment]
Or you can add individual markers like:

```
Mapper::marker(53.381128999999990000, -1.470085000000040000);
```

**Comment by shooter27** [comment]
Hi Brad. Thanks you for quick response. I tried bot and it's not working.
Maybe it because I used custom icon for the marker.
What default value in the config file?
Thank you very match

**Comment by shooter27** [comment]
Just tried   set  to  'icon' => '',  and deault marker there now. So it was cause. But I need my custom marker, I use 'icon' => 'images/orange.png',   
How I can fix it?

**Comment by shooter27** [comment]
In this case we should use an absolute path to an image

**Comment by bradcornford** [comment]
I believe an absolute uri is needed for the marker icon.

**Comment by shooter27** [comment]
Yes, it solved the issue. Thank you very match!
