### ISSUE TITLE
Set Y position

### ISSUE THREAD

**Issue by martingg88** [bradcornford/Googlmapper#98]
is that possible to pan Y position in order to show the map at very top position?

**Comment by bradcornford** [comment]
Hi there,

I'm not entirely sure what you mean, you can set the position of the map as follows:


```php

Mapper::map(45, 18, ['eventAfterLoad' => 'maps[0].map.setCenter({lat: 45, lng: 19});']);

```

**Comment by martingg88** [comment]
Thank for your reply here. I wish you happy new year. 

What I what here is to pan the map to Y position . So all the relevant markers will be shown on top  instead of bottom. 

Thank You.

**Comment by bradcornford** [comment]
Hi there,

Could you provide me with your controller and view code please.

**Comment by martingg88** [comment]
here is the code. how do you pan it to Y position?

             $map = Mapper::map(3.152109, 101.666041, ['zoom' => 11, 'cluster' => false, 'center' => false]);

                    //$map->marker(3.152109, 101.666041);
                    $map->informationWindow(3.152109, 101.666041, Translator::transSmart('app.WISMA UOA DAMANSARA II', 'WISMA UOA DAMANSARA II'), ['open' => true]);
                    $map->marker(3.146512, 101.625098);
                    $map->informationWindow(3.146512, 101.625098, Translator::transSmart('app.TTDI', 'TTDI'), ['open' => true]);
                    $map->marker(3.149311, 101.762975);
                    $map->informationWindow(3.149311, 101.762975, Translator::transSmart('app.AMPANG', 'AMPANG'), ['open' => true]);
                    $map->marker(3.056992, 101.583237);
                    $map->informationWindow(3.056992, 101.583237, Translator::transSmart('app.SUBANG', 'SUBANG'), ['open' => true]);

**Comment by bradcornford** [comment]
Hi there,

I believe something along the lines of this would be work:

```php

$map = Mapper::map(3.152109, 101.666041, ['zoom' => 11, 'cluster' => false, 'center' => false, 'eventAfterLoad' => 'maps[0].map.setCenter(new google.maps.LatLng(3.152109, 101.666041));']);

```
