### ISSUE TITLE
Google Maps API warning: SignedInDeprecated

### ISSUE THREAD

**Issue by gezzeg** [bradcornford/Googlmapper#99]
Hi, 

I have succesfully installed this package.

I just exactly follow the documentation given but it dont show anything. Insted i got error like this "Google Maps API warning: SignedInDeprecated" when i inspect my browser.

![screen shot 2017-01-02 at 12 37 25 am](https://cloud.githubusercontent.com/assets/876838/21582014/b4204cca-d083-11e6-8c60-880c591d0a7a.png)

**Comment by bradcornford** [comment]
Hi there, 

This is nothing to worry about, it's just a warning as Google have deprecated the siggned in parameter. This will be removed in a later version. 

The other error you are getting is because bootstrap requires jquery.

**Comment by gezzeg** [comment]
Ok. Thanks for fast reply.

Ive found my solution. I need to set the div height and width.

Thanks.
